//+------------------------------------------------------------------+
//|                                       asian_breakout_V1.016.mq4 |
//|                                      Generated by Antigravity |
//|                                   Revisado y corregido         |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.016"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input bool     UseDynamicLot     = true;       // Activar Lote Dinámico (1%)
input double   RiskPercent       = 1;        // Riesgo por operación (%)
input bool     InpSendPush       = true;       // Enviar Notificación al Móvil

input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input bool     WaitCandleClose   = true;       // Esperar Cierre de Vela M5
input int      MinBoxPips        = 10;         // Tamaño Mínimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamaño Máximo Caja (pips)
input int      MagicNumber       = 100100;     // Magic Number
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling)
input int      EndHour           = 8;          // Hora fin Asia (08:00 Skilling)
input int      MaxEntryHour      = 23;         // Hora máxima para cazar ruptura (Fin Londres)

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = false;      // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = true;       // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = false;      // Activar Trailing Stop (False = Purista)
input int      TrailingPips      = 0;          // Distancia del Trailing (pips)

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      SLBufferPips      = 3;          // Pips extra de margen (spread)
input int      MinSLPips         = 5;          // Stop Loss mínimo (pips)

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = false;      // Activar Auto Break-Even por PIPS FIJOS (ignorado si UseBreakEvenAt1R=true)
input int      BreakEvenActivation = 10;         // Pips ganancia para activar BE (solo si UseBreakEvenAt1R=false)
input int      BreakEvenExtraPips  = 1;          // Pips extra sobre SL para asegurar comisiones
input bool     UseBreakEvenAt1R    = false;      // Mover a BE al alcanzar 1:1 (R) y activar trailing por pips después

input int      MaxTradesPerDay     = 2;          // Maximo de operaciones por dia (Reentradas)
input bool     CloseAtEndOfDay     = false;      // Cerrar todas las operaciones a las 23:00 (Time Stop)
input bool     UsePartialClose     = false;      // Activar Cierre Parcial Automático (False = Purista)
input int      PartialClosePips    = 15;         // Pips ganancia para cerrar parcial
input double   PartialClosePercent = 50.0;       // % del lote original a cerrar (ej. 50%)

input string   Mode_Settings     = "--- MODO DE LIQUIDEZ (SMC) ---";
input bool     AutoFindLiquidity = true;       // Buscar Liquidez en AMBOS sentidos (Modo Auto)
input int      HoursToLookBack   = 12;         // (No usado actualmente - ver Aviso en el log de inicio)
input int      MinBreakoutBodyPips = 2;        // Min pips cuerpo vela de ruptura (Vela Decidida)
input double   MinReversalCandlePips = 8.0;    // Min pips TOTALES de la vela de entrada (Filtro Ruido NY)
input double   MinDojiSizePips   = 2.0;        // Min pips TOTALES para considerar un Doji plano
input int      MaxCandlesOutside = 36;         // Max velas fuera de caja antes de reversión (3h)
input int      MaxMinutesForReversal = 240;    // Máx. minutos absolutos para caducar (4h)
input string   ManualBoxName     = "ZonaLiquidez"; // Nombre del Rectángulo Manual (Modo Manual)



//--- Global variables
int lastTradeDay = -1;        // FIX bug3: ahora guarda una clave de fecha completa (YYYYMMDD), no solo el día del mes
int currentSessionDay = -1;   // FIX bug3: idem
double Pip;                   // Multiplicador dinámico para brokers de 4 o 5 dígitos

bool sweptHigh = false;
bool sweptLow = false;
bool patternFoundHigh = false;
bool patternFoundLow = false;
double peakHigh = 0;
double troughLow = 0;
datetime timeSweptHigh = 0;
datetime timeSweptLow = 0;

// FIX bug6: registro en memoria de tickets ya parcialmente cerrados,
// como respaldo al chequeo de comentario (que depende del broker)
int g_partialClosedTickets[100];
int g_partialClosedCount = 0;

// Seguimiento por ticket para el modo "BE a 1:1 + trailing" (UseBreakEvenAt1R)
// NOTA: al igual que g_partialClosedTickets, esto vive en memoria y se pierde
// si el EA se recarga/reinicia a mitad de una operación abierta.
int    g_mgmtTickets[200];
double g_mgmtRiskPips[200];
bool   g_mgmtBEDone[200];
int    g_mgmtCount = 0;

//+------------------------------------------------------------------+
//| Devuelve una clave de fecha completa AAAAMMDD para comparar días |
//| de forma segura entre distintos meses/años (FIX bug3)            |
//+------------------------------------------------------------------+
int GetDateKey(datetime t)
  {
   return TimeYear(t) * 10000 + TimeMonth(t) * 100 + TimeDay(t);
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Avisos de inputs sin efecto real en la lógica actual (antes fallaban en silencio)
   if(!WaitCandleClose)
      Print("Aviso: 'WaitCandleClose' = false no tiene efecto actualmente. ",
            "La EA siempre evalúa señales al cierre de vela por diseño (usa Close[1]).");
   Print("Aviso: el input 'HoursToLookBack' no está referenciado en la lógica de la EA (sin efecto).");

   if(UseBreakEvenAt1R)
      Print("Modo BE a 1:1 activo: 'UseAutoBreakEven' y 'BreakEvenActivation' quedan ignorados. ",
            "El SL se mueve a breakeven al alcanzar 1:1 y luego usa 'TrailingPips' como distancia de trailing.");

   // Solucionar el problema de "Fractional Pips" (Brokers de 3 o 5 dígitos vs Clásicos)
   Pip = (Digits == 3 || Digits == 5) ? 10.0 * Point : 1.0 * Point;

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;

   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);

   if(tickValue == 0) return FixedLotSize; // Fallback de seguridad

   // Formula: Lote = Riesgo / (SL_Points * TickValue)
   double slPoints = slDistancePips * (Pip / Point);
   double lot = riskAmount / (slPoints * tickValue);

   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;

   // Normalizar al LotStep (ej: 0.01)
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Helpers de seguimiento por ticket para UseBreakEvenAt1R          |
//+------------------------------------------------------------------+
int FindMgmtIndex(int ticket)
  {
   for(int i = 0; i < g_mgmtCount; i++)
      if(g_mgmtTickets[i] == ticket) return i;
   return -1;
  }

void RegisterInitialRisk(int ticket, double riskPips)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx >= 0)
     {
      g_mgmtRiskPips[idx] = riskPips;
      g_mgmtBEDone[idx] = false;
      return;
     }
   if(g_mgmtCount < 200)
     {
      g_mgmtTickets[g_mgmtCount] = ticket;
      g_mgmtRiskPips[g_mgmtCount] = riskPips;
      g_mgmtBEDone[g_mgmtCount] = false;
      g_mgmtCount++;
     }
  }

double GetInitialRisk(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx < 0) return -1;
   return g_mgmtRiskPips[idx];
  }

bool IsBEActivated(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx < 0) return false;
   return g_mgmtBEDone[idx];
  }

void SetBEActivated(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx >= 0) g_mgmtBEDone[idx] = true;
  }

//+------------------------------------------------------------------+
//| Mover a Break-Even al alcanzar 1:1 (R) y activar trailing por    |
//| pips fijos a partir de ahí. Sustituye a ManageAutoBreakEven() +  |
//| ManageTrailingStop() mientras UseBreakEvenAt1R = true.           |
//+------------------------------------------------------------------+
void ManageBreakEvenAt1R()
  {
   if(!UseBreakEvenAt1R) return;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue; // solo posiciones de mercado

            int ticket = OrderTicket();
            double riskPips = GetInitialRisk(ticket);
            if(riskPips <= 0) continue; // no se registró riesgo inicial para este ticket

            double profitPips = 0;
            if(OrderType() == OP_BUY)  profitPips = (Bid - OrderOpenPrice()) / (Pip);
            else                       profitPips = (OrderOpenPrice() - Ask) / (Pip);

            if(!IsBEActivated(ticket))
              {
               // --- Fase 1: esperar a alcanzar 1:1 (profit >= riesgo inicial) ---
               if(profitPips >= riskPips)
                 {
                  double newSL;
                  bool okMove = false;

                  if(OrderType() == OP_BUY)
                    {
                     newSL = NormalizeDouble(OrderOpenPrice() + BreakEvenExtraPips * Pip, Digits);
                     if((OrderStopLoss() < newSL || OrderStopLoss() == 0) && newSL < Bid) okMove = true;
                    }
                  else
                    {
                     newSL = NormalizeDouble(OrderOpenPrice() - BreakEvenExtraPips * Pip, Digits);
                     if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) okMove = true;
                    }

                  if(okMove)
                    {
                     if(OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue))
                       {
                        SetBEActivated(ticket);
                        Print("BE a 1:1 activado en ticket #", ticket, ". SL movido a breakeven+buffer.");
                       }
                    }
                 }
              }
            else
              {
               // --- Fase 2: ya en breakeven, aplicar trailing por pips fijos ---
               if(TrailingPips <= 0) continue;
               double trailingPoints = TrailingPips * Pip;

               if(OrderType() == OP_BUY)
                 {
                  if(Bid - OrderOpenPrice() > trailingPoints)
                    {
                     double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                     if(newSL - OrderStopLoss() > Point * 2)
                       {
                        bool res = OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error modificando SL (Trailing Buy): ", GetLastError());
                       }
                    }
                 }
               else
                 {
                  if(OrderOpenPrice() - Ask > trailingPoints)
                    {
                     double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                     if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0)
                       {
                        bool res = OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error modificando SL (Trailing Sell): ", GetLastError());
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//| (Solo se usa cuando UseBreakEvenAt1R = false)                    |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;

   double trailingPoints = TrailingPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2) // Solo si mejora el SL en más de 2 puntos
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error TrailingStop BUY #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0) // Solo si baja el SL
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error TrailingStop SELL #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;

   double activationPoints = BreakEvenActivation * Pip;
   double extraPoints = BreakEvenExtraPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid) // Solo subir SL si mejora y no choca con el Bid
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                        if(!res) Print("Error AutoBE BUY #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) // Solo bajar SL
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                        if(!res) Print("Error AutoBE SELL #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Comprueba si un ticket ya fue registrado como parcialmente       |
//| cerrado en esta sesión de la EA (FIX bug6)                       |
//+------------------------------------------------------------------+
bool IsAlreadyPartiallyClosed(int ticket)
  {
   for(int k = 0; k < g_partialClosedCount; k++)
      if(g_partialClosedTickets[k] == ticket) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automático                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;

   double targetPoints = PartialClosePips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            // FIX bug6: chequeo doble - comentario (depende del broker) + registro propio en memoria
            if(StringFind(OrderComment(), "from #") >= 0) continue;
            if(IsAlreadyPartiallyClosed(OrderTicket())) continue;

            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;

            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;

               // Asegurar que el lote a cerrar es válido y deja algo abierto
               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  int origTicket = OrderTicket();
                  bool res = OrderClose(origTicket, lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
                  if(res)
                    {
                     // FIX bug6: registrar el ticket para no volver a cerrar parcialmente
                     if(g_partialClosedCount < 100)
                       {
                        g_partialClosedTickets[g_partialClosedCount] = origTicket;
                        g_partialClosedCount++;
                       }
                     Print("SMC Cierre Parcial Automático ejecutado: ", lotToClose, " lotes.");
                     if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Cierre Parcial alcanzado ✅");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   return true; // Filtro de tendencia eliminado (las EMAs arruinan el Judas Swing)
  }

//+------------------------------------------------------------------+
//| Limpiar ordenes pendientes al final del día                      |
//+------------------------------------------------------------------+
void CleanPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT)
              {
               bool del = OrderDelete(OrderTicket());
               if(!del) Print("Error borrando orden: ", GetLastError());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//| FIX bug3: compara fecha completa (año/mes/día), no solo el día   |
//| FIX bug4: deduplica cierres parciales que generan un ticket extra|
//|           en el historial con el mismo OpenTime/Type que la      |
//|           operación original                                     |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int todayKey = GetDateKey(TimeCurrent());

   datetime seenTimes[100];
   int seenTypes[100];
   ArrayInitialize(seenTimes, 0);   // FIX: elimina warning "possible use of uninitialized variable"
   ArrayInitialize(seenTypes, -1);  // FIX: idem
   int seenCount = 0;
   int count = 0;

   // --- Operaciones abiertas ---
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }

   // --- Historial (incluye fragmentos de cierres parciales, que se deduplican) ---
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Patrones de Reversion SMC (Alex Ruiz)                            |
//+------------------------------------------------------------------+
bool isBearishReversal(int shift)
  {
   double open = Open[shift];
   double close = Close[shift];
   double high = High[shift];
   double low = Low[shift];

   // Filtro de ruido EXCLUSIVO para la tarde (Nueva York):
   // Por la mañana (Londres) cualquier vela es válida porque la manipulación es más fiable.
   double totalSize = (high - low) / (Pip);
   if(TimeHour(Time[shift]) >= 13 && totalSize < MinReversalCandlePips) return false;

   // La vela de gatillo idealmente debe cerrar bajista o plana
   if(close > open) return false;

   double body = MathAbs(open - close);
   double upperWick = high - MathMax(open, close);
   double lowerWick = MathMin(open, close) - low;

   // 1. Pinbar Bajista (Martillo invertido / Shooting star)
   bool isPinbar = false;
   if(body > 0)
     {
      if(upperWick >= 1.5 * body && lowerWick <= body * 1.5) isPinbar = true;
     }
   else
     {
      // Si es un Doji plano
      if(upperWick > MinDojiSizePips * Pip && lowerWick < upperWick * 0.5) isPinbar = true;
     }

   // 2. Envolvente Bajista (Bearish Engulfing) - Ajustado para Forex
   double prevOpen = Open[shift+1];
   double prevClose = Close[shift+1];
   bool isBullishPrev = prevClose >= prevOpen; // Permite que la anterior sea un Doji plano
   bool isEngulfing = isBullishPrev && (close < prevOpen) && (body > MathAbs(prevClose - prevOpen));

   return isPinbar || isEngulfing;
  }

bool isBullishReversal(int shift)
  {
   double open = Open[shift];
   double close = Close[shift];
   double high = High[shift];
   double low = Low[shift];

   // Filtro de ruido EXCLUSIVO para la tarde (Nueva York):
   // Por la mañana (Londres) cualquier vela es válida porque la manipulación es más fiable.
   double totalSize = (high - low) / (Pip);
   if(TimeHour(Time[0]) >= 13 && totalSize < MinReversalCandlePips) return false;

   // La vela de gatillo idealmente debe cerrar alcista o plana
   if(close < open) return false;

   double body = MathAbs(close - open);
   double upperWick = high - MathMax(open, close);
   double lowerWick = MathMin(open, close) - low;

   // 1. Pinbar Alcista (Martillo)
   bool isPinbar = false;
   if(body > 0)
     {
      if(lowerWick >= 1.5 * body && upperWick <= body * 1.5) isPinbar = true;
     }
   else
     {
      // Si es un Doji plano
      if(lowerWick > MinDojiSizePips * Pip && upperWick < lowerWick * 0.5) isPinbar = true;
     }

   // 2. Envolvente Alcista (Bullish Engulfing) - Ajustado para Forex
   double prevOpen = Open[shift+1];
   double prevClose = Close[shift+1];
   bool isBearishPrev = prevOpen >= prevClose; // Permite que la anterior sea un Doji plano o roja
   bool isEngulfing = isBearishPrev && (close > prevOpen) && (body > MathAbs(prevOpen - prevClose));

   return isPinbar || isEngulfing;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Gestión de posiciones abiertas: BE a 1:1 + trailing (nuevo) o el esquema
   // antiguo de pips fijos, nunca ambos a la vez para evitar que se pisen.
   if(UseBreakEvenAt1R)
     {
      ManageBreakEvenAt1R();
     }
   else
     {
      ManageTrailingStop();
      ManageAutoBreakEven();
     }
   ManagePartialClose();

   int currentHour = Hour();
   int currentDay = GetDateKey(TimeCurrent()); // FIX bug3: clave de fecha completa, no solo Day()

   // Si es el final del día (ej. hora 23), limpiamos ordenes pendientes que no se activaron y, opcionalmente, cerramos activas
   if(currentHour >= 23)
     {
      CleanPendingOrders();
      if(CloseAtEndOfDay)
        {
         for(int i = OrdersTotal() - 1; i >= 0; i--)
           {
            if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
              {
               if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
                 {
                  if(OrderType() == OP_BUY)
                    {
                     bool res = OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrOrange);
                     if(res) Print("SMC: Cierre de fin de día (Time Stop) ejecutado para orden BUY #", OrderTicket());
                     else Print("SMC Error: Falló Cierre de fin de día BUY #", OrderTicket(), " Error: ", GetLastError());
                    }
                  else if(OrderType() == OP_SELL)
                    {
                     bool res = OrderClose(OrderTicket(), OrderLots(), Ask, 3, clrOrange);
                     if(res) Print("SMC: Cierre de fin de día (Time Stop) ejecutado para orden SELL #", OrderTicket());
                     else Print("SMC Error: Falló Cierre de fin de día SELL #", OrderTicket(), " Error: ", GetLastError());
                    }
                 }
              }
           }
        }
     }

   // Limpiamos pendientes si ya llegamos al limite del dia o hay activas
   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      CleanPendingOrders();
     }

   // Solo buscar operaciones despues de cerrar la caja asiatica y antes del limite (Killzone Londres)
   if(currentHour >= EndHour && currentHour < MaxEntryHour)
     {
      // Resetear variables de barrido cada nuevo día
      if(currentDay != currentSessionDay)
        {
         sweptHigh = false;
         sweptLow = false;
         patternFoundHigh = false;
         patternFoundLow = false;
         peakHigh = 0;
         troughLow = 0;
         timeSweptHigh = 0;
         timeSweptLow = 0;
         
         // Fix Bug: Solo resetear memoria de gestión si no hay operaciones vivas
         if(!HasActiveTrades())
           {
            g_partialClosedCount = 0; // Limpiar memoria de cierres parciales
            g_mgmtCount = 0;          // Limpiar memoria de gestión BreakEven/Trailing
           }
         currentSessionDay = currentDay;
        }

      // Filtro de días de la semana
      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      // Comprobar si el dia fue ignorado, o alcanzamos limite, o hay trades activos
      if(!isTradingDay)
        {
         if(currentDay != lastTradeDay)
           {
            Print("Día desactivado en ajustes. Se ignora la operativa hoy.");
            lastTradeDay = currentDay;
           }
         return;
        }

      if(currentDay == lastTradeDay) { return; }
      if(GetTradesTodayCount() >= MaxTradesPerDay) { return; }
      if(HasActiveTrades()) { return; }

      // Calcular inicio y fin de la sesion asiatica para HOY
      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + StartHour * 3600;
      datetime timeEnd = currentDayStart + EndHour * 3600;

      int shiftStart = iBarShift(Symbol(), Period(), timeStart);
      // Restamos 1 segundo para no incluir la vela que empieza EXACTAMENTE a las 08:00
      int shiftEnd = iBarShift(Symbol(), Period(), timeEnd - 1);

      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd)
        {
         return;
        }

      // FIX bug2: +1 para incluir también la vela de shiftStart (apertura de la sesión asiática),
      // que antes quedaba excluida del rango de iHighest/iLowest
      int barsCount = shiftStart - shiftEnd + 1;

      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), Period(), MODE_LOW, barsCount, shiftEnd);

      if(highestIdx < 0 || lowestIdx < 0)
        {
         return;
        }

      double asianHigh = High[highestIdx];
      double asianLow  = Low[lowestIdx];

      // Filtro de Tamano de Caja
      double boxSizePips = (asianHigh - asianLow) / (Pip);
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         Print("Caja asiatica ignorada por tamano: ", DoubleToStr(boxSizePips, 1), " pips.");
         return;
        }

      if(AutoFindLiquidity)
        {
         // MODO AUTOMATICO: Vigilar Ruptura y Reversión (Asian Sweep - Alex Ruiz SMC)
         bool triggerSell = false;
         bool triggerBuy = false;

         static datetime lastBarTime = 0;
         bool isNewBar = false;
         if(Time[0] != lastBarTime)
           {
            isNewBar = true;
            lastBarTime = Time[0];
           }

         if(isNewBar)
           {
            // 1. Detectar si la vela anterior rompió CON ENERGIA (Cerrando fuera)
            // Se requiere Close[2] dentro de la caja para garantizar que es el momento EXACTO de la ruptura,
            // evitando que se reinicien trampas caducadas si el precio sigue flotando fuera.
            if(Close[1] > asianHigh && Close[2] <= asianHigh)
              {
               if(!sweptHigh)
                 {
                  double bodyPips = MathAbs(Close[1] - Open[1]) / (Pip);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptHigh = Time[1]; // Registrar inicio de la manipulación
                     sweptHigh = true;
                     peakHigh = High[1];
                     Print("SMC: Ruptura Alcista detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
              }
            else if(sweptHigh && Close[1] > asianHigh)
              {
               if(High[1] > peakHigh) peakHigh = High[1]; // Mantener el pico más alto mientras estemos fuera
              }

            if(Close[1] < asianLow && Close[2] >= asianLow)
              {
               if(!sweptLow)
                 {
                  double bodyPips = MathAbs(Close[1] - Open[1]) / (Pip);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptLow = Time[1]; // Registrar inicio de la manipulación
                     sweptLow = true;
                     if(troughLow == 0 || Low[1] < troughLow) troughLow = Low[1];
                     Print("SMC: Ruptura Bajista detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
              }
            else if(sweptLow && Close[1] < asianLow)
              {
               if(troughLow == 0 || Low[1] < troughLow) troughLow = Low[1]; // Mantener el valle más bajo mientras estemos fuera
              }

            // 1.5 Validar si la trampa ha caducado por tiempo o velas (Killzones)
            if(sweptHigh)
              {
               int barsPassed = iBarShift(Symbol(), Period(), timeSweptHigh);
               if(barsPassed > MaxCandlesOutside || (Time[0] - timeSweptHigh > MaxMinutesForReversal * 60)) // Usamos Time[0] actual
                 {
                  sweptHigh = false;
                  patternFoundHigh = false; // Reset
                 }
               else
                 {
                  // Buscar el patrón MIENTRAS estamos fuera (al cierre de cada vela)
                  if(!patternFoundHigh && isBearishReversal(1)) patternFoundHigh = true;
                 }
              }
            if(sweptLow)
              {
               int barsPassed = iBarShift(Symbol(), Period(), timeSweptLow);
               if(barsPassed > MaxCandlesOutside || (Time[0] - timeSweptLow > MaxMinutesForReversal * 60))
                 {
                  sweptLow = false;
                  patternFoundLow = false; // Reset
                 }
               else
                 {
                  // Buscar el patrón MIENTRAS estamos fuera (al cierre de cada vela)
                  if(!patternFoundLow && isBullishReversal(1)) patternFoundLow = true;
                 }
              }

            // 2. Esperar Gatillo: Cierre dentro de la caja HABIENDO encontrado el patrón previamente
            if(sweptHigh && Close[1] < asianHigh)
              {
               if(patternFoundHigh || isBearishReversal(1)) triggerSell = true;
               else
                 {
                  sweptHigh = false; // Si volvió a entrar sin haber hecho un patrón nunca, invalidar
                  patternFoundHigh = false;
                 }
              }

            if(sweptLow && Close[1] > asianLow)
              {
               if(patternFoundLow || isBullishReversal(1)) triggerBuy = true;
               else
                 {
                  sweptLow = false; // Si volvió a entrar sin haber hecho un patrón nunca, invalidar
                  patternFoundLow = false;
                 }
              }
           } // CIERRE DEL BLOQUE isNewBar

         if(triggerSell)
           {
            if(!IsTrendAligned(false))
              {
               Print("Venta SMC Bloqueada: Tendencia macro alcista detectada.");
               triggerSell = false; // Bloquear
               sweptHigh = false; // Invalidar para no entrar tarde si la tendencia cambia luego
               patternFoundHigh = false;
              }
            else
              {
               // Reversión bajista -> VENDER
               double baseSL = peakHigh + SLBufferPips * Pip;
               double slPips = (baseSL - Bid) / (Pip);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Bid + slPips * Pip;
                 }
               double sl = NormalizeDouble(baseSL, Digits);

               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opción B: Sin límite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Bid - (slPips * Pip * FixedRiskReward), Digits);
                    }

                  if(Bid < sl)
                    {
                     int t = OrderSend(Symbol(), OP_SELL, calculatedLot, Bid, 3, sl, actualTP, "SMC Reversion Sell", MagicNumber, 0, clrRed);
                     if(t > 0)
                       {
                        Print("Venta SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        RegisterInitialRisk(t, slPips); // Necesario para el modo BE a 1:1
                        if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: VENTA Auto abierta a " + DoubleToStr(Bid, Digits));
                        // Resetear el barrido tras entrar para obligar a buscar uno nuevo si hay reentradas
                        sweptHigh = false;
                        patternFoundHigh = false;
                       }
                     else Print("Error abriendo Venta SMC: ", GetLastError());
                    }
                 }
              }
           }

         if(triggerBuy)
           {
            if(!IsTrendAligned(true))
              {
               Print("Compra SMC Bloqueada: Tendencia macro bajista detectada.");
               triggerBuy = false; // Bloquear
               sweptLow = false; // Invalidar para no entrar tarde si la tendencia cambia luego
               patternFoundLow = false;
              }
            else
              {
               // Reversión alcista -> COMPRAR
               double baseSL = troughLow - SLBufferPips * Pip;
               double slPips = (Ask - baseSL) / (Pip);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Ask - slPips * Pip;
                 }
               double sl = NormalizeDouble(baseSL, Digits);

               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opción B: Sin límite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Ask + (slPips * Pip * FixedRiskReward), Digits);
                    }

                  if(Ask > sl)
                    {
                     int t = OrderSend(Symbol(), OP_BUY, calculatedLot, Ask, 3, sl, actualTP, "SMC Reversion Buy", MagicNumber, 0, clrBlue);
                     if(t > 0)
                       {
                        Print("Compra SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        RegisterInitialRisk(t, slPips); // Necesario para el modo BE a 1:1
                        if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: COMPRA Auto abierta a " + DoubleToStr(Ask, Digits));
                        // Resetear el barrido tras entrar para obligar a buscar uno nuevo si hay reentradas
                        sweptLow = false;
                        patternFoundLow = false; // FIX bug1: faltaba este reset (simetría con el caso de venta)
                       }
                     else Print("Error abriendo Compra SMC: ", GetLastError());
                    }
                 }
              }
           }
        }
      else
        {
         // MODO MANUAL (Buscar el rectangulo del usuario)
         int objIdx = ObjectFind(0, ManualBoxName);
         if(objIdx >= 0)
           {
            double price1 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE1);
            double price2 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE2);

            double boxTop = MathMax(price1, price2);
            double boxBottom = MathMin(price1, price2);

            static bool boxDetected = false;
            if(!boxDetected)
              {
               Print("SMC: Caja '", ManualBoxName, "' detectada visualmente. Base: ", boxBottom, " Techo: ", boxTop, " (AsianHigh:", asianHigh, " AsianLow:", asianLow, ")");
               boxDetected = true;
              }

            double limitPrice = 0, stopLoss = 0, takeProfit = 0, slPips = 0;
            int orderType = -1;

            // Si la caja manual esta por encima de la asiatica, queremos VENDER
            if(boxBottom >= asianHigh)
              {
               limitPrice = boxBottom;
               stopLoss = boxTop + SLBufferPips * Pip;
               if((stopLoss - limitPrice) / (Pip) < MinSLPips) stopLoss = limitPrice + MinSLPips * Pip;
               slPips = (stopLoss - limitPrice) / (Pip);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice - (slPips * Pip * FixedRiskReward), Digits);
               else takeProfit = asianLow;
               orderType = OP_SELLLIMIT;
              }
            // Si la caja manual esta por debajo de la asiatica, queremos COMPRAR
            else if(boxTop <= asianLow)
              {
               limitPrice = boxTop;
               stopLoss = boxBottom - SLBufferPips * Pip;
               if((limitPrice - stopLoss) / (Pip) < MinSLPips) stopLoss = limitPrice - MinSLPips * Pip;
               slPips = (limitPrice - stopLoss) / (Pip);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice + (slPips * Pip * FixedRiskReward), Digits);
               else takeProfit = asianHigh;
               orderType = OP_BUYLIMIT;
              }

            if(orderType >= 0 && limitPrice > 0)
              {
               limitPrice = NormalizeDouble(limitPrice, Digits);
               stopLoss = NormalizeDouble(stopLoss, Digits);
               takeProfit = NormalizeDouble(takeProfit, Digits);

               bool validLimit = false;
               if(orderType == OP_BUYLIMIT && Ask > limitPrice) validLimit = true;
               if(orderType == OP_SELLLIMIT && Bid < limitPrice) validLimit = true;

               if(validLimit)
                 {
                  double lot = CalculateLotSize(slPips);
                  int ticket = OrderSend(Symbol(), orderType, lot, limitPrice, 3, stopLoss, takeProfit, "SMC Limit Manual", MagicNumber, 0, (orderType == OP_BUYLIMIT) ? clrBlue : clrRed);
                  if(ticket > 0)
                    {
                     lastTradeDay = currentDay;
                     boxDetected = false; // Reset state
                     RegisterInitialRisk(ticket, slPips); // Necesario para el modo BE a 1:1 (se activa cuando se llene la limit)
                     Print("Orden Limit SMC Manual colocada exitosamente. Lote: ", lot, " TP: ", takeProfit);
                     if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Orden Limit colocada a " + DoubleToStr(limitPrice, Digits));
                     // Ocultar el rectángulo para no duplicar mañana
                     ObjectDelete(0, ManualBoxName);
                    }
                  else
                    {
                     Print("Error al poner la Orden Limit Manual: ", GetLastError());
                    }
                 }
               else
                 {
                  static datetime lastPrint = 0;
                  if(Time[0] != lastPrint)
                    {
                     Print("SMC Esperando... Precio actual no permite colocar Limit. (Bid: ", Bid, " Limit: ", limitPrice, ")");
                     lastPrint = Time[0];
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
