//+------------------------------------------------------------------+
//|                                       AsianBreakout_100D.mq4 |
//|                                      Generated by Antigravity |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.01"
#property strict

//--- Enums
enum ENUM_SL_TYPE {
   SL_MID_BOX=0,      // Mitad de la Caja Asiatica
   SL_OPPOSITE_BOX=1  // Extremo Opuesto de la Caja
};

//--- Input parameters
input int          StartHour         = 1;          // Hora inicio Asia (01:00 en Skilling)
input int          EndHour           = 10;         // Hora fin Asia (10:00 en Skilling)
input ENUM_SL_TYPE StopLossPlacement = SL_MID_BOX; // Ubicacion del Stop Loss
input double       RiskRewardRatio   = 2.0;        // Ratio Riesgo:Beneficio (ej. 2.0 para 1:2)
input double       LotSize           = 0.1;        // Volumen (Lotes)
input int          MagicNumber       = 100100;     // Magic Number

//--- Global variables
int lastTradeDay = -1;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Solo buscar operaciones si estamos despues del cierre asiatico
   if(Hour() >= EndHour)
     {
      // Comprobar si ya operamos hoy
      if(Day() == lastTradeDay) return;

      // Calcular inicio y fin de la sesion asiatica para el dia de HOY
      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + StartHour * 3600;
      datetime timeEnd = currentDayStart + EndHour * 3600;
      
      // Obtener indices de las velas
      int shiftStart = iBarShift(Symbol(), Period(), timeStart);
      int shiftEnd = iBarShift(Symbol(), Period(), timeEnd);
      
      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd) return;
      
      int barsCount = shiftStart - shiftEnd;
      
      // Encontrar Maximo y Minimo
      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), Period(), MODE_LOW, barsCount, shiftEnd);
      
      if(highestIdx < 0 || lowestIdx < 0) return;
      
      double asianHigh = High[highestIdx];
      double asianLow  = Low[lowestIdx];
      
      // Logica de COMPRA (Cruce real por arriba)
      // Usamos Close[1] para asegurarnos de que el rompimiento esta ocurriendo AHORA, 
      // y no hace 6 horas.
      if(Ask > asianHigh && Close[1] <= asianHigh)
        {
         double sl = 0;
         if(StopLossPlacement == SL_MID_BOX)
            sl = asianLow + (asianHigh - asianLow) / 2.0;
         else
            sl = asianLow;
            
         double tp = asianHigh + (asianHigh - sl) * RiskRewardRatio;
         
         // Normalizar precios para MT4
         sl = NormalizeDouble(sl, Digits);
         tp = NormalizeDouble(tp, Digits);
         
         int ticket = OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, sl, tp, "Asian Breakout Buy", MagicNumber, 0, clrBlue);
         if(ticket > 0)
           {
            lastTradeDay = Day();
            Print("Orden de COMPRA ejecutada exitosamente.");
           }
        }
        
      // Logica de VENTA (Cruce real por abajo)
      else if(Bid < asianLow && Close[1] >= asianLow)
        {
         double sl = 0;
         if(StopLossPlacement == SL_MID_BOX)
            sl = asianHigh - (asianHigh - asianLow) / 2.0;
         else
            sl = asianHigh;
            
         double tp = asianLow - (sl - asianLow) * RiskRewardRatio;
         
         // Normalizar precios para MT4
         sl = NormalizeDouble(sl, Digits);
         tp = NormalizeDouble(tp, Digits);
         
         int ticket = OrderSend(Symbol(), OP_SELL, LotSize, Bid, 3, sl, tp, "Asian Breakout Sell", MagicNumber, 0, clrRed);
         if(ticket > 0)
           {
            lastTradeDay = Day();
            Print("Orden de VENTA ejecutada exitosamente.");
           }
        }
     }
  }
//+------------------------------------------------------------------+
