//+------------------------------------------------------------------+
//|                                   anti_asian_breakout_V2.1.mq4 |
//|                                      Generated by Antigravity    |
//|                        Fixes: re-deteccion tras Judas + TrailingStop vs UseFixedRR |
//|                        V2.11: DST auto (caja asiatica fija en hora de Tokio) |
//|                        V2.12: TrailingStepPips anti-spam de OrderModify    |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "2.12" // MQL4 requiere formato "x.xx" máximo 2 decimales
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input bool     UseDynamicLot     = true;       // Activar Lote Dinámico (1%)
input double   RiskPercent       = 1.0;        // Riesgo por operación (%)
input bool     SendPush          = true;       // Enviar Notificación al Móvil
input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input int      MinBoxPips        = 10;         // Tamaño Mínimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamaño Máximo Caja (pips)
input int      MagicNumber       = 200200;     // Magic Number (Distinto para Anti-Breakout)
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling - Se ajustará auto por DST)
input int      EndHour           = 8;          // Hora fin Asia (08:00 Skilling - Se ajustará auto por DST)
input int      MaxEntryHour      = 18;         // Hora MÁXIMA absoluta de la ventana de entrada (cap duro, fija en hora del broker)
input int      RefGMTOffset      = 3;          // Offset GMT del broker al que están calibradas las horas de la caja (3 = GMT+3 verano Skilling)

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = true;       // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = false;      // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = true;       // Activar Trailing Stop (Por defecto en Continuación)
input int      TrailingPips      = 15;         // Distancia del Trailing (pips)
input int      TrailingStepPips  = 3;          // Paso mínimo del trailing (pips) para evitar spam de OrderModify

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      MinSLPips         = 5;          // Stop Loss mínimo (pips)

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = true;       // Activar Auto Break-Even
input int      BreakEvenActivation = 15;         // Pips ganancia para activar BE
input int      BreakEvenExtraPips  = 1;          // Pips extra sobre SL para asegurar comisiones
input bool     UsePartialClose     = false;      // Activar Cierre Parcial Automático
input int      PartialClosePips    = 15;         // Pips ganancia para cerrar parcial
input double   PartialClosePercent = 50.0;       // % del lote original a cerrar (ej. 50%)
input int      MaxTradesPerDay     = 1;          // Solo permitimos 1 entrada buena al día en continuación
input bool     CloseAtEndOfDay     = false;      // Cerrar todas las operaciones al final del día (23:00)

input string   Mode_Settings     = "--- MODO CONTINUACION (SMC) ---";
input double   MinBreakoutTotalPips = 5.0;     // Min pips TOTALES vela ruptura (0 = Inactivo)
input int      MinBreakoutBodyPips = 2;        // Min pips cuerpo vela ruptura M15
input double   MaxPullbackIntoBoxPercent = 40.0; // Max % que el amago puede meterse a la caja (40% = Estricto)
input int      MaxPatternBars      = 8;        // Max velas M15 para que se complete el patrón

input string   News_Settings     = "--- NEWS FILTER (API) ---";
input bool     UseNewsFilter     = true;       // Activar Filtro de Noticias
input int      MinsBeforeNews    = 30;         // Minutos antes de la noticia para pausar
input int      MinsAfterNews     = 30;         // Minutos después de la noticia para pausar
input bool     FilterHighImpact  = true;       // Filtrar Carpetas Rojas (Alta)
input bool     FilterMedImpact   = false;      // Filtrar Carpetas Naranjas (Media)
input string   Trend_Settings    = "--- FILTRO DE TENDENCIA ---";
input bool     UseTrendFilter    = true;       // Activar Filtro EMA (Modo Auto)
input ENUM_TIMEFRAMES TrendTF    = PERIOD_H1;  // Temporalidad de Tendencia
input int      FastEMAPeriod     = 50;         // Periodo EMA Rapida
input int      SlowEMAPeriod     = 200;        // Periodo EMA Lenta

//--- Global variables
int lastTradeDay = -1;
int currentSessionDay = -1;
double Pip;

// State variables for Long pattern
int stateLong = 0; // 0=IDLE, 1=BREAKOUT, 2=PULLBACK
double longBreakoutLow = 0;
datetime timeLongBreakout = 0;

// State variables for Short pattern
int stateShort = 0; // 0=IDLE, 1=BREAKOUT, 2=PULLBACK
double shortBreakoutHigh = 0;
datetime timeShortBreakout = 0;

int g_partialClosedTickets[100];
int g_partialClosedCount = 0;

//+------------------------------------------------------------------+
//| Devuelve una clave de fecha completa AAAAMMDD para comparar días |
//+------------------------------------------------------------------+
int GetDateKey(datetime t)
  {
   return TimeYear(t) * 10000 + TimeMonth(t) * 100 + TimeDay(t);
  }

//+------------------------------------------------------------------+
//| AJUSTE AUTOMATICO DE DST (Horario Verano/Invierno)               |
//| TOKIO no cambia el reloj: la caja asiatica debe cubrir la misma  |
//| franja real (hora de Tokio) todo el ano. El broker europeo       |
//| (Skilling) pasa de GMT+3 (verano) a GMT+2 (invierno).            |
//| Se usa el CALENDARIO europeo de DST (ultimo domingo de marzo ->  |
//| ultimo domingo de octubre) porque es DETERMINISTICO y fiable     |
//| tambien en el Strategy Tester, donde TimeGMT() puede devolver    |
//| valores inconsistentes y desplazar la caja a horas absurdas.     |
//| Offset de invierno = RefGMTOffset - 1.                           |
//| Las horas de CORTE (MaxEntryHour, cierre fin de dia/semana) se   |
//| usan FIJAS en hora del broker: LONDRES sigue el mismo calendario |
//| de DST europeo que el servidor, por lo que su franja real ya es  |
//| constante en hora del broker.                                    |
//+------------------------------------------------------------------+
int GetLastSundayDay(int year, int month)
  {
   int lastDay = 31;
   if(month == 4 || month == 6 || month == 9 || month == 11) lastDay = 30;
   if(month == 2) lastDay = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? 29 : 28;
   string dateStr = StringFormat("%04d.%02d.%02d 00:00:00", year, month, lastDay);
   datetime dt = StrToTime(dateStr);
   int dow = TimeDayOfWeek(dt);
   return lastDay - dow;
  }

bool IsBrokerSummerTime(datetime t)
  {
   int year  = TimeYear(t);
   int month = TimeMonth(t);
   int day   = TimeDay(t);
   if(month < 3 || month > 10) return false;
   if(month > 3 && month < 10) return true;
   int lastSunday = GetLastSundayDay(year, month);
   if(month == 3)  return (day >= lastSunday);
   if(month == 10) return (day < lastSunday);
   return false;
  }

int GetBrokerGMTOffset()
  {
   int refOffset = (RefGMTOffset >= 2 && RefGMTOffset <= 14) ? RefGMTOffset : 3;
   return IsBrokerSummerTime(TimeCurrent()) ? refOffset : (refOffset - 1);
  }

// Ajusta una hora de la caja (calibrada a RefGMTOffset) a la hora del broker actual
int AdjustBoxHour(int hour)
  {
   int h = hour + GetBrokerGMTOffset() - RefGMTOffset;
   h = h % 24;
   if(h < 0) h += 24;
   return h;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   Pip = (Digits == 3 || Digits == 5) ? 10.0 * Point : 1.0 * Point;

   // Log de estado DST al iniciar
   Print("DST Auto: offset actual GMT", GetBrokerGMTOffset(), " (", (IsBrokerSummerTime(TimeCurrent()) ? "verano" : "invierno"),
         "). Caja asiatica en hora del broker: ", AdjustBoxHour(StartHour), ":00-", AdjustBoxHour(EndHour),
         ":00. Ventana de entrada: [", AdjustBoxHour(EndHour), ":00, ", MaxEntryHour,
         ":00). Horas de corte fijas: MaxEntry ", MaxEntryHour, ":00.");

   // --- Validacion de inputs contradictorios ---
   if(StartHour >= EndHour)
      Print("ATENCION: StartHour (", StartHour, ") >= EndHour (", EndHour, "). El rango de la sesion asiatica es invalido/vacio. Revisa los inputs.");

   if(EndHour >= MaxEntryHour)
      Print("ATENCION: EndHour (", EndHour, ") >= MaxEntryHour (", MaxEntryHour, "). No habra ventana de entrada disponible. Revisa los inputs.");

   if(MinBoxPips >= MaxBoxPips)
      Print("ATENCION: MinBoxPips (", MinBoxPips, ") >= MaxBoxPips (", MaxBoxPips, "). Ninguna caja asiatica pasara el filtro de tamano. Revisa los inputs.");

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;
   
   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   
   if(tickValue == 0) return FixedLotSize;
   
   double slPoints = slDistancePips * (Pip / Point);
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   
   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;
   
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   // FIX #2: si el usuario activó TP fijo por Ratio (UseFixedRR), el trailing
   // NO debe tocar el SL, ya que el input dice explícitamente "Sobrescribe Trailing".
   // Antes, ambos podían estar activos a la vez y el trailing modificaba el SL
   // igualmente, contradiciendo la intención declarada del parámetro.
   if(!UseTrailingStop || UseFixedRR || TrailingPips <= 0) return;
   
   double trailingPoints = TrailingPips * Pip;
   double minStep = MathMax(TrailingStepPips * Pip, Point * 2);
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > minStep)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                         OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if((OrderStopLoss() - newSL > minStep || OrderStopLoss() == 0))
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                         OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;
   
   double activationPoints = BreakEvenActivation * Pip;
   double extraPoints = BreakEvenExtraPips * Pip;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                         OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                         OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Comprueba si un ticket ya fue registrado como parcialmente       |
//+------------------------------------------------------------------+
bool IsAlreadyPartiallyClosed(int ticket)
  {
   for(int k = 0; k < g_partialClosedCount; k++)
      if(g_partialClosedTickets[k] == ticket) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automático                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;

   double targetPoints = PartialClosePips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(StringFind(OrderComment(), "from #") >= 0) continue;
            if(IsAlreadyPartiallyClosed(OrderTicket())) continue;

            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;

            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;

               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  int origTicket = OrderTicket();
                  bool res = OrderClose(origTicket, lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
                  if(res)
                    {
                     if(g_partialClosedCount < 100)
                       {
                        g_partialClosedTickets[g_partialClosedCount] = origTicket;
                        g_partialClosedCount++;
                       }
                     Print("SMC Cierre Parcial Automático ejecutado: ", lotToClose, " lotes.");
                     if(SendPush) SendNotification("Anti-Breakout [" + Symbol() + "]: Cierre Parcial alcanzado.");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   if(!UseTrendFilter) return true;
   
   double fastEMA = iMA(Symbol(), TrendTF, FastEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), TrendTF, SlowEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double currentPrice = iClose(Symbol(), TrendTF, 1); 
   
   if(isBuy)
     {
      if(fastEMA > slowEMA && currentPrice > slowEMA) return true;
     }
   else
     {
      if(fastEMA < slowEMA && currentPrice < slowEMA) return true;
     }
     
   return false;
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int todayKey = GetDateKey(TimeCurrent());
   
   datetime seenTimes[100];
   int seenTypes[100];
   ArrayInitialize(seenTimes, 0);
   ArrayInitialize(seenTypes, -1);
   int seenCount = 0;
   int count = 0;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
     
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   ManageTrailingStop();
   ManageAutoBreakEven();
   ManagePartialClose();
   
   int currentHour = Hour();
   int currentDay = GetDateKey(TimeCurrent());
   
   // Cierre al fin del día (Time Stop)
   if(currentHour >= 23 && CloseAtEndOfDay)
     {
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
           {
            if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
              {
               if(OrderType() == OP_BUY)
                 {
                  bool res = OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrOrange);
                  if(res) Print("Anti-Breakout: Cierre de fin de día ejecutado (BUY).");
                 }
               else if(OrderType() == OP_SELL)
                 {
                  bool res = OrderClose(OrderTicket(), OrderLots(), Ask, 3, clrOrange);
                  if(res) Print("Anti-Breakout: Cierre de fin de día ejecutado (SELL).");
                 }
              }
           }
        }
     }

   // Cierre de fin de semana incondicional (Viernes 22:00) para evitar Gaps
   if(TimeDayOfWeek(TimeCurrent()) == 5 && currentHour >= 22)
     {
      for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
         if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
           {
            if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
              {
               if(OrderType() == OP_BUY)
                 {
                  bool res = OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
                  if(res) Print("Anti-Breakout: Cierre de fin de semana ejecutado (BUY).");
                 }
               else if(OrderType() == OP_SELL)
                 {
                  bool res = OrderClose(OrderTicket(), OrderLots(), Ask, 3, clrRed);
                  if(res) Print("Anti-Breakout: Cierre de fin de semana ejecutado (SELL).");
                 }
              }
           }
        }
     }
   
   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      return;
     }

   // Ajuste automatico de DST: la CAJA asiatica se compensa por el offset
   // real del broker (Tokio no cambia el reloj; se mantiene la misma franja
   // real todo el ano). Las horas de CORTE (MaxEntryHour, cierre fin de
   // dia/semana) son FIJAS en hora del broker.
   int adjStartHour = AdjustBoxHour(StartHour);
   int adjEndHour   = AdjustBoxHour(EndHour);

   if(currentHour >= adjEndHour && currentHour < MaxEntryHour)
     {
      if(currentDay != currentSessionDay)
        {
         stateLong = 0;
         stateShort = 0;
         if(!HasActiveTrades())
           {
            g_partialClosedCount = 0;
           }
         currentSessionDay = currentDay;
        }

      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      if(!isTradingDay || currentDay == lastTradeDay) return;

      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + adjStartHour * 3600;
      datetime timeEnd = currentDayStart + adjEndHour * 3600;
      
      int shiftStart = iBarShift(Symbol(), PERIOD_M15, timeStart);
      int shiftEnd = iBarShift(Symbol(), PERIOD_M15, timeEnd - 1); // Excluimos la vela de cierre de la caja
      
      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd) return;
      
      int barsCount = shiftStart - shiftEnd + 1;
      int highestIdx = iHighest(Symbol(), PERIOD_M15, MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), PERIOD_M15, MODE_LOW, barsCount, shiftEnd);
      
      if(highestIdx < 0 || lowestIdx < 0) return;
      
      double asianHigh = iHigh(Symbol(), PERIOD_M15, highestIdx);
      double asianLow  = iLow(Symbol(), PERIOD_M15, lowestIdx);
      
      double boxSizePips = (asianHigh - asianLow) / Pip;
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         return;
        }
      
      static datetime lastBarTimeM15 = 0;
      bool isNewBarM15 = false;
      datetime currentM15Time = iTime(Symbol(), PERIOD_M15, 0);
      if(currentM15Time != lastBarTimeM15)
        {
         isNewBarM15 = true;
         lastBarTimeM15 = currentM15Time;
        }
      
      if(isNewBarM15)
        {
         if(UseNewsFilter && IsNewsTime())
           {
            if(stateLong > 0 || stateShort > 0) Print("Anti-Breakout Entrada Bloqueada: Filtro de Noticias activo. Cancelando patrones.");
            stateLong = 0;
            stateShort = 0;
            return;
           }
         double closeM15 = iClose(Symbol(), PERIOD_M15, 1);
         double openM15 = iOpen(Symbol(), PERIOD_M15, 1);
         double lowM15 = iLow(Symbol(), PERIOD_M15, 1);
         double highM15 = iHigh(Symbol(), PERIOD_M15, 1);
         
         // FIX #1: banderas que indican si el patrón fue invalidado (incluyendo
         // Judas Swing) EN ESTA MISMA VELA. Antes, tras poner stateLong/stateShort
         // a 0, el bloque "PASO 1" de la misma vela podía reactivar el patrón
         // usando el low/high de la vela que originó la invalidación,
         // contaminando el SL base con una vela ya descartada por el filtro Anti-Judas.
         bool longInvalidatedThisBar = false;
         bool shortInvalidatedThisBar = false;

         // --- Mantenimiento de Estados e Invalidador Temprano (Anti-Judas) ---
         if(stateLong > 0)
           {
            int barsPassed = iBarShift(Symbol(), PERIOD_M15, timeLongBreakout) - 1;
            
            // Invalidador Temprano: Si el retroceso cruza profundo hacia adentro de la caja
            double maxAllowedLow = asianHigh - ((asianHigh - asianLow) * (MaxPullbackIntoBoxPercent / 100.0));
            bool isJudasSwing = (lowM15 < maxAllowedLow);
            
            if(barsPassed > MaxPatternBars || lowM15 < longBreakoutLow || isJudasSwing)
              {
               stateLong = 0; 
               longInvalidatedThisBar = true; // FIX #1
               if(isJudasSwing) Print("Anti-Breakout: Judas Swing Alcista detectado. Patron cancelado al instante.");
               else Print("Anti-Breakout: Patron Largo invalidado (Caducidad o Soporte roto).");
              }
           }
           
         if(stateShort > 0)
           {
            int barsPassed = iBarShift(Symbol(), PERIOD_M15, timeShortBreakout) - 1;
            
            // Invalidador Temprano: Si el retroceso cruza profundo hacia adentro de la caja
            double maxAllowedHigh = asianLow + ((asianHigh - asianLow) * (MaxPullbackIntoBoxPercent / 100.0));
            bool isJudasSwing = (highM15 > maxAllowedHigh);
            
            if(barsPassed > MaxPatternBars || highM15 > shortBreakoutHigh || isJudasSwing)
              {
               stateShort = 0;
               shortInvalidatedThisBar = true; // FIX #1
               if(isJudasSwing) Print("Anti-Breakout: Judas Swing Bajista detectado. Patron cancelado al instante.");
               else Print("Anti-Breakout: Patron Corto invalidado (Caducidad o Resistencia rota).");
              }
           }

         // --- STATE MACHINE: LONG (Ruptura Alcista) ---
         // FIX #1: si el patrón se invalidó justo en esta vela, no lo re-evaluamos
         // como nueva ruptura hasta la siguiente vela (evita usar una vela "sucia"
         // como base del nuevo longBreakoutLow).
         if(stateLong == 0 && !longInvalidatedThisBar)
           {
            // PASO 1: Ruptura
            if(closeM15 > asianHigh)
              {
               double bodyPips = MathAbs(closeM15 - openM15) / Pip;
               double totalPips = (highM15 - lowM15) / Pip;
               
               if(bodyPips >= MinBreakoutBodyPips && totalPips >= MinBreakoutTotalPips)
                 {
                  stateLong = 1;
                  longBreakoutLow = lowM15;
                  timeLongBreakout = iTime(Symbol(), PERIOD_M15, 1);
                  Print("Anti-Breakout: Ruptura Alcista genuina (SMC) detectada. SL base en: ", longBreakoutLow);
                 }
              }
           }
         else if(stateLong == 1)
           {
            // PASO 2: Amago (Pullback) - Vela bajista
            if(closeM15 < openM15)
              {
               stateLong = 2;
               Print("Anti-Breakout: Amago bajista detectado, esperando vela de confirmacion.");
              }
           }
         else if(stateLong == 2)
           {
            // PASO 3: Confirmación - Vela alcista envolvente o fuerte
            double prevOpen = iOpen(Symbol(), PERIOD_M15, 2);
            if(closeM15 > openM15 && closeM15 > prevOpen) 
              {
               if(IsTrendAligned(true))
                 {
                  // EJECUCION DE COMPRA
                   double slPips = (Ask - longBreakoutLow) / Pip;
                   if(slPips < MinSLPips) slPips = MinSLPips;
                   double sl = NormalizeDouble(Ask - slPips * Pip, Digits);
                   
                   if(longBreakoutLow >= Ask || sl >= Bid)
                     {
                      stateLong = 0;
                      Print("Anti-Breakout: SL inválido en compra, patrón reiniciado.");
                      return;
                     }
                   
                   double lot = CalculateLotSize(slPips);
                  double tp = 0;
                  if(UseFixedRR) tp = NormalizeDouble(Ask + (slPips * Pip * FixedRiskReward), Digits);
                  
                  int t = OrderSend(Symbol(), OP_BUY, lot, Ask, 3, sl, tp, "Anti-Breakout Buy", MagicNumber, 0, clrBlue);
                  if(t > 0)
                    {
                     Print("Anti-Breakout: Compra Confirmada!");
                      if(SendPush) SendNotification("Anti-Breakout: COMPRA Auto abierta.");
                     lastTradeDay = currentDay;
                     stateLong = 0;
                    }
                  else
                    {
                     Print("Error al abrir COMPRA Anti-Breakout: ", GetLastError());
                    }
                 }
               else
                 {
                  stateLong = 0; 
                  Print("Anti-Breakout: Compra bloqueada por filtro de tendencia. Reiniciando.");
                 }
              }
           }

         // --- STATE MACHINE: SHORT (Ruptura Bajista) ---
         // FIX #1: mismo criterio que en LONG.
         if(stateShort == 0 && !shortInvalidatedThisBar)
           {
            // PASO 1: Ruptura
            if(closeM15 < asianLow)
              {
               double bodyPips = MathAbs(closeM15 - openM15) / Pip;
               double totalPips = (highM15 - lowM15) / Pip;
               
               if(bodyPips >= MinBreakoutBodyPips && totalPips >= MinBreakoutTotalPips)
                 {
                  stateShort = 1;
                  shortBreakoutHigh = highM15;
                  timeShortBreakout = iTime(Symbol(), PERIOD_M15, 1);
                  Print("Anti-Breakout: Ruptura Bajista genuina (SMC) detectada. SL base en: ", shortBreakoutHigh);
                 }
              }
           }
         else if(stateShort == 1)
           {
            // PASO 2: Amago (Pullback) - Vela alcista
            if(closeM15 > openM15)
              {
               stateShort = 2;
               Print("Anti-Breakout: Amago alcista detectado, esperando vela de confirmacion.");
              }
           }
         else if(stateShort == 2)
           {
            // PASO 3: Confirmación - Vela bajista envolvente
            double prevOpen = iOpen(Symbol(), PERIOD_M15, 2);
            if(closeM15 < openM15 && closeM15 < prevOpen) 
              {
               if(IsTrendAligned(false))
                 {
                  // EJECUCION DE VENTA
                   double slPips = (shortBreakoutHigh - Bid) / Pip;
                   if(slPips < MinSLPips) slPips = MinSLPips;
                   double sl = NormalizeDouble(Bid + slPips * Pip, Digits);
                   
                   if(shortBreakoutHigh <= Bid || sl <= Ask)
                     {
                      stateShort = 0;
                      Print("Anti-Breakout: SL inválido en venta, patrón reiniciado.");
                      return;
                     }
                   
                   double lot = CalculateLotSize(slPips);
                  double tp = 0;
                  if(UseFixedRR) tp = NormalizeDouble(Bid - (slPips * Pip * FixedRiskReward), Digits);
                  
                  int t = OrderSend(Symbol(), OP_SELL, lot, Bid, 3, sl, tp, "Anti-Breakout Sell", MagicNumber, 0, clrRed);
                  if(t > 0)
                    {
                     Print("Anti-Breakout: Venta Confirmada!");
                      if(SendPush) SendNotification("Anti-Breakout: VENTA Auto abierta.");
                     lastTradeDay = currentDay;
                     stateShort = 0;
                    }
                  else
                    {
                     Print("Error al abrir VENTA Anti-Breakout: ", GetLastError());
                    }
                 }
               else
                 {
                  stateShort = 0;
                  Print("Anti-Breakout: Venta bloqueada por filtro de tendencia. Reiniciando.");
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
//| Dibuja una línea vertical en el gráfico indicando la noticia     |
//+------------------------------------------------------------------+
void DrawNewsLine(string name, color clr, double minsToNews)
  {
   if(minsToNews == 0) return;
   
   datetime newsTime = TimeCurrent() + (int)(minsToNews * 60);
   
   if(ObjectFind(name) < 0)
     {
      ObjectCreate(0, name, OBJ_VLINE, 0, newsTime, 0);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_DASHDOT);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
     }
   else
     {
      ObjectSetInteger(0, name, OBJPROP_TIME, newsTime);
     }
  }

//+------------------------------------------------------------------+
//| News API Integration (Global Variables from News_Fetcher)        |
//+------------------------------------------------------------------+
bool IsNewsTime()
  {
   bool isNews = false;
   
   if(FilterHighImpact)
     {
      if(GlobalVariableCheck("SMC_News_High"))
        {
         double minsHigh = GlobalVariableGet("SMC_News_High"); 
         DrawNewsLine("SMC_News_High", clrRed, minsHigh);
         if(minsHigh <= MinsBeforeNews && minsHigh >= -MinsAfterNews) isNews = true;
        }
     }
     
   if(FilterMedImpact)
     {
      if(GlobalVariableCheck("SMC_News_Med"))
        {
         double minsMed = GlobalVariableGet("SMC_News_Med"); 
         DrawNewsLine("SMC_News_Med", clrOrange, minsMed);
         if(minsMed <= MinsBeforeNews && minsMed >= -MinsAfterNews) isNews = true;
        }
     }

   return isNews;
  }
//+------------------------------------------------------------------+

