//+------------------------------------------------------------------+
//|                                       asian_breakout_V1.03.mq4 |
//|                                      Generated by Antigravity |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.03"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input bool     UseDynamicLot     = true;       // Activar Lote Dinámico (1%)
input double   RiskPercent       = 1.0;        // Riesgo por operación (%)
input bool     InpSendPush       = true;       // Enviar Notificación al Móvil

input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input bool     WaitCandleClose   = true;       // Esperar Cierre de Vela M5
input int      MinBoxPips        = 10;         // Tamaño Mínimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamaño Máximo Caja (pips)
input int      MagicNumber       = 100100;     // Magic Number
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling = 01:00 Madrid)
input int      EndHour           = 8;          // Hora fin Asia / Inicio Londres (08:00 Skilling = 07:00 Madrid)
input int      MaxTradeHour      = 13;         // Hora LÍMITE en Skilling (13:00 Broker = 12:00 Madrid)

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = false;      // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = true;       // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = false;      // Activar Trailing Stop (False = Purista)
input int      TrailingPips      = 15;         // Distancia del Trailing (pips)

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS & ATR ---";
input bool     UseATRStopLoss    = true;       // Activar Stop Loss dinámico por ATR (Volatilidad)
input int      ATRPeriod         = 14;         // Período del indicador ATR
input double   ATRMultiplier     = 1.5;        // Multiplicador de ATR para Buffer de SL
input ENUM_TIMEFRAMES ATRTF      = PERIOD_M15; // Temporalidad para calcular ATR
input int      SLBufferPips      = 3;          // Pips extra de margen si UseATRStopLoss es false
input int      MinSLPips         = 5;          // Stop Loss mínimo absoluto (pips)

input string   News_Settings     = "--- FILTRO DE NOTICIAS Y VOLATILIDAD ---";
input bool     UseVolatilityFilter = true;     // Bloquear operativas ante Spikes de Noticias
input double   SpikeATRThreshold   = 2.5;      // Vela M15 > X * ATR se considera Noticia / Alta Volatilidad
input int      VolatilityBlackoutMinutes = 30; // Minutos de bloqueo tras detectar Spike

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = false;    // Activar Auto Break-Even (False = Purista)
input int      BreakEvenActivation = 10;       // Pips ganancia para activar BE
input int      BreakEvenExtraPips  = 1;        // Pips extra sobre SL para asegurar comisiones

input int      MaxTradesPerDay     = 2;        // Maximo de operaciones por dia (Reentradas)
input bool     UsePartialClose     = false;    // Activar Cierre Parcial Automático (False = Purista)
input int      PartialClosePips    = 10;       // Pips ganancia para cerrar parcial
input double   PartialClosePercent = 50.0;     // % del lote original a cerrar (ej. 50%)

input string   Mode_Settings     = "--- MODO DE LIQUIDEZ (SMC MTF) ---";
input bool     AutoFindLiquidity = true;       // Buscar Liquidez en AMBOS sentidos (Modo Auto)
input int      HoursToLookBack   = 12;         // Horas previas a la caja (Modo Auto)
input int      MinBreakoutBodyPips = 2;        // Min pips cuerpo vela ruptura M5 (Vela Decidida)
input int      MaxCandlesOutside = 6;          // Max velas M5 fuera de caja antes de reversión
input int      MaxMinutesForReversal = 120;    // Máx. minutos absolutos para caducar
input string   ManualBoxName     = "ZonaLiquidez"; // Nombre del Rectángulo Manual (Modo Manual)

input string   Trend_Settings    = "--- FILTRO DE TENDENCIA ---";
input bool     UseTrendFilter    = true;       // Activar Filtro EMA (Modo Auto)
input ENUM_TIMEFRAMES TrendTF    = PERIOD_H1;  // Temporalidad de Tendencia
input int      FastEMAPeriod     = 50;         // Periodo EMA Rapida
input int      SlowEMAPeriod     = 200;        // Periodo EMA Lenta

//--- Global variables
int lastTradeDay = -1;
int currentSessionDay = -1;
bool sweptHigh = false;
bool sweptLow = false;
double peakHigh = 0;
double troughLow = 0;
datetime timeSweptHigh = 0;
datetime timeSweptLow = 0;
datetime timeAbsoluteSweepHigh = 0;
datetime timeAbsoluteSweepLow = 0;
datetime lastSpikeTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   Print("Asian Breakout V1.03 cargado. Skilling Broker Time: ", EndHour, ":00 a ", MaxTradeHour, ":00 (Equivalente Madrid: 07:00 a 12:00)");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Obtener Buffer de Stop Loss en Pips (ATR o Fijo)                 |
//+------------------------------------------------------------------+
double GetSLBufferPips()
  {
   if(!UseATRStopLoss) return (double)SLBufferPips;
   
   double atrVal = iATR(Symbol(), ATRTF, ATRPeriod, 1);
   if(atrVal <= 0) return (double)SLBufferPips;
   
   double atrPips = (atrVal * ATRMultiplier) / (10.0 * Point);
   return MathMax(atrPips, (double)SLBufferPips);
  }

//+------------------------------------------------------------------+
//| Validar Filtro de Noticias y Spikes de Volatilidad               |
//+------------------------------------------------------------------+
bool IsVolatilitySafe()
  {
   if(!UseVolatilityFilter) return true;
   
   if(lastSpikeTime > 0 && (TimeCurrent() - lastSpikeTime) < VolatilityBlackoutMinutes * 60)
     {
      return false;
     }
     
   double currentATR = iATR(Symbol(), PERIOD_M15, ATRPeriod, 1);
   if(currentATR > 0)
     {
      double lastCandleRange = iHigh(Symbol(), PERIOD_M15, 1) - iLow(Symbol(), PERIOD_M15, 1);
      if(lastCandleRange >= currentATR * SpikeATRThreshold)
        {
         lastSpikeTime = TimeCurrent();
         Print("SMC Proteccion Noticias: Spike de volatilidad detectado (Vela M15: ", 
               DoubleToStr(lastCandleRange / (10.0 * Point), 1), " pips vs Limite ATR: ", 
               DoubleToStr((currentATR * SpikeATRThreshold) / (10.0 * Point), 1), " pips). Operativa bloqueada por ", VolatilityBlackoutMinutes, " minutos.");
         if(InpSendPush) SendNotification("Asian Breakout V1.03 [" + Symbol() + "]: ⚠️ Spike de Noticias detectado. Operativa pausada " + IntegerToString(VolatilityBlackoutMinutes) + "m.");
         return false;
        }
     }
     
   return true;
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;
   
   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   
   if(tickValue == 0) return FixedLotSize;
   
   double slPoints = slDistancePips * 10.0;
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   
   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;
   
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;
   
   double trailingPoints = TrailingPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;
   
   double activationPoints = BreakEvenActivation * 10.0 * Point;
   double extraPoints = BreakEvenExtraPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automático                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;
   
   double targetPoints = PartialClosePips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(StringFind(OrderComment(), "from #") >= 0) continue; 
            
            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;
            
            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
               
               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;
               
               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  bool res = OrderClose(OrderTicket(), lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
                  if(res)
                    {
                     Print("SMC Cierre Parcial Automático ejecutado: ", lotToClose, " lotes.");
                     if(InpSendPush) SendNotification("Asian Breakout V1.03 [" + Symbol() + "]: Cierre Parcial alcanzado ✅");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   if(!UseTrendFilter) return true;
   
   double fastEMA = iMA(Symbol(), TrendTF, FastEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), TrendTF, SlowEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double currentPrice = iClose(Symbol(), TrendTF, 1);
   
   if(isBuy)
     {
      if(fastEMA > slowEMA && currentPrice > slowEMA) return true;
     }
   else
     {
      if(fastEMA < slowEMA && currentPrice < slowEMA) return true;
     }
     
   return false;
  }

//+------------------------------------------------------------------+
//| Limpiar ordenes pendientes al final del día                      |
//+------------------------------------------------------------------+
void CleanPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT)
              {
               bool del = OrderDelete(OrderTicket());
               if(!del) Print("Error borrando orden: ", GetLastError());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int currentDay = Day();
   int count = 0;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay)
              {
               count++;
              }
           }
        }
     }
     
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay)
              {
               count++;
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Patrones de Reversion SMC Multi-Timeframe (Estricto SMC)        |
//+------------------------------------------------------------------+
bool isBearishReversalMTF(ENUM_TIMEFRAMES tf, int shift)
  {
   double open = iOpen(Symbol(), tf, shift);
   double close = iClose(Symbol(), tf, shift);
   double high = iHigh(Symbol(), tf, shift);
   double low = iLow(Symbol(), tf, shift);
   double prevLow = iLow(Symbol(), tf, shift + 1);
   
   if(close >= open) return false;
   
   double totalRange = high - low;
   if(totalRange <= 0) return false;
   
   // 1. Envolvente Bajista (Cierra por debajo del mínimo de la vela anterior)
   if(close <= prevLow) return true;
   
   // 2. Pinbar Bajista (La mecha superior representa al menos el 45% del rango total)
   double upperWick = high - MathMax(open, close);
   if(upperWick / totalRange >= 0.45) return true;
   
   return false;
  }

bool isBullishReversalMTF(ENUM_TIMEFRAMES tf, int shift)
  {
   double open = iOpen(Symbol(), tf, shift);
   double close = iClose(Symbol(), tf, shift);
   double high = iHigh(Symbol(), tf, shift);
   double low = iLow(Symbol(), tf, shift);
   double prevHigh = iHigh(Symbol(), tf, shift + 1);
   
   if(close <= open) return false;
   
   double totalRange = high - low;
   if(totalRange <= 0) return false;
   
   // 1. Envolvente Alcista (Cierra por encima del máximo de la vela anterior)
   if(close >= prevHigh) return true;
   
   // 2. Pinbar Alcista (La mecha inferior representa al menos el 45% del rango total)
   double lowerWick = MathMin(open, close) - low;
   if(lowerWick / totalRange >= 0.45) return true;
   
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   ManageTrailingStop();
   ManageAutoBreakEven();
   ManagePartialClose();
   
   int currentHour = Hour();
   int currentDay = Day();
   
   if(currentHour > MaxTradeHour)
     {
      CleanPendingOrders();
     }

   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      CleanPendingOrders();
     }

   // RESTRICCIÓN DE HORARIO: 08:00 a MaxTradeHour (13:00 Skilling Broker Time = 07:00 a 12:00 Madrid)
   if(currentHour >= EndHour && currentHour <= MaxTradeHour)
     {
      if(currentDay != currentSessionDay)
        {
         sweptHigh = false;
         sweptLow = false;
         peakHigh = 0;
         troughLow = 0;
         timeSweptHigh = 0;
         timeSweptLow = 0;
         timeAbsoluteSweepHigh = 0;
         timeAbsoluteSweepLow = 0;
         currentSessionDay = currentDay;
        }

      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      if(!isTradingDay)
        {
         if(currentDay != lastTradeDay)
           {
            Print("Día desactivado en ajustes. Se ignora la operativa hoy.");
            lastTradeDay = currentDay;
           }
         return;
        }

      if(currentDay == lastTradeDay) { return; }
      if(GetTradesTodayCount() >= MaxTradesPerDay) { return; }
      if(HasActiveTrades()) { return; }

      if(!IsVolatilitySafe()) return;

      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + StartHour * 3600;
      datetime timeEnd = currentDayStart + EndHour * 3600;
      
      int shiftStart = iBarShift(Symbol(), PERIOD_M5, timeStart);
      int shiftEnd = iBarShift(Symbol(), PERIOD_M5, timeEnd);
      
      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd) return;
      
      int barsCount = shiftStart - shiftEnd;
      int highestIdx = iHighest(Symbol(), PERIOD_M5, MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), PERIOD_M5, MODE_LOW, barsCount, shiftEnd);
      
      if(highestIdx < 0 || lowestIdx < 0) return;
      
      double asianHigh = iHigh(Symbol(), PERIOD_M5, highestIdx);
      double asianLow  = iLow(Symbol(), PERIOD_M5, lowestIdx);
      
      double boxSizePips = (asianHigh - asianLow) / (10 * Point);
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         Print("Caja asiatica ignorada por tamano: ", DoubleToStr(boxSizePips, 1), " pips.");
         return;
        }
      
      if(AutoFindLiquidity)
        {
         bool triggerSell = false;
         bool triggerBuy = false;
         
         static datetime lastBarTimeM5 = 0;
         bool isNewBarM5 = false;
         datetime currentM5Time = iTime(Symbol(), PERIOD_M5, 0);
         if(currentM5Time != lastBarTimeM5)
           {
            isNewBarM5 = true;
            lastBarTimeM5 = currentM5Time;
           }
           
         if(isNewBarM5)
           {
            double closeM5_1 = iClose(Symbol(), PERIOD_M5, 1);
            double openM5_1 = iOpen(Symbol(), PERIOD_M5, 1);
            double highM5_1 = iHigh(Symbol(), PERIOD_M5, 1);
            double lowM5_1 = iLow(Symbol(), PERIOD_M5, 1);
            
            if(closeM5_1 > asianHigh)
              {
               if(!sweptHigh)
                 {
                  double bodyPips = MathAbs(closeM5_1 - openM5_1) / (10 * Point);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptHigh = iTime(Symbol(), PERIOD_M5, 1); 
                     timeAbsoluteSweepHigh = TimeCurrent(); 
                     sweptHigh = true;
                     peakHigh = highM5_1;
                     Print("SMC V1.03: Ruptura Alcista M5 detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
               else
                 {
                  if(highM5_1 > peakHigh) peakHigh = highM5_1;
                 }
              }
              
            if(closeM5_1 < asianLow)
              {
               if(!sweptLow)
                 {
                  double bodyPips = MathAbs(closeM5_1 - openM5_1) / (10 * Point);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptLow = iTime(Symbol(), PERIOD_M5, 1);
                     timeAbsoluteSweepLow = TimeCurrent();
                     sweptLow = true;
                     if(troughLow == 0 || lowM5_1 < troughLow) troughLow = lowM5_1;
                     Print("SMC V1.03: Ruptura Bajista M5 detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
               else
                 {
                  if(troughLow == 0 || lowM5_1 < troughLow) troughLow = lowM5_1;
                 }
              }
              
            if(sweptHigh)
              {
               int barsPassedM5 = iBarShift(Symbol(), PERIOD_M5, timeSweptHigh);
               if(barsPassedM5 > MaxCandlesOutside || (TimeCurrent() - timeAbsoluteSweepHigh > MaxMinutesForReversal * 60))
                 {
                  sweptHigh = false;
                  Print("SMC V1.03: Trampa Alcista CADUCADA. Velas M5 fuera: ", barsPassedM5);
                 }
              }
            if(sweptLow)
              {
               int barsPassedM5 = iBarShift(Symbol(), PERIOD_M5, timeSweptLow);
               if(barsPassedM5 > MaxCandlesOutside || (TimeCurrent() - timeAbsoluteSweepLow > MaxMinutesForReversal * 60))
                 {
                  sweptLow = false;
                  Print("SMC V1.03: Trampa Bajista CADUCADA. Velas M5 fuera: ", barsPassedM5);
                 }
              }

            if(sweptHigh && closeM5_1 < asianHigh)
              {
               if(isBearishReversalMTF(PERIOD_M5, 1)) triggerSell = true;
               else sweptHigh = false;
              }
              
            if(sweptLow && closeM5_1 > asianLow)
              {
               if(isBullishReversalMTF(PERIOD_M5, 1)) triggerBuy = true;
               else sweptLow = false;
              }
           }

         double bufferPips = GetSLBufferPips();

         if(triggerSell)
           {
            if(!IsTrendAligned(false))
              {
               Print("Venta SMC V1.03 Bloqueada: Tendencia macro alcista detectada.");
               triggerSell = false;
              }
            else
              {
               double baseSL = peakHigh + bufferPips * 10 * Point;
               double slPips = (baseSL - Bid) / (10 * Point);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Bid + slPips * 10 * Point;
                 }
               double sl = NormalizeDouble(baseSL, Digits);
               
               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0;
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Bid - (slPips * 10 * Point * FixedRiskReward), Digits);
                    }
                  
                  if(Bid < sl)
                    {
                     int t = OrderSend(Symbol(), OP_SELL, calculatedLot, Bid, 3, sl, actualTP, "SMC V1.03 Sell", MagicNumber, 0, clrRed);
                     if(t > 0)
                       {
                        Print("Venta SMC V1.03 ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips (Buffer ATR/Fijo: ", bufferPips, " pips).");
                        if(InpSendPush) SendNotification("Asian Breakout V1.03 [" + Symbol() + "]: VENTA Auto abierta a " + DoubleToStr(Bid, Digits));
                        sweptHigh = false;
                       }
                     else Print("Error abriendo Venta SMC V1.03: ", GetLastError());
                    }
                 }
              }
           }
           
         if(triggerBuy)
           {
            if(!IsTrendAligned(true))
              {
               Print("Compra SMC V1.03 Bloqueada: Tendencia macro bajista detectada.");
               triggerBuy = false;
              }
            else
              {
               double baseSL = troughLow - bufferPips * 10 * Point;
               double slPips = (Ask - baseSL) / (10 * Point);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Ask - slPips * 10 * Point;
                 }
               double sl = NormalizeDouble(baseSL, Digits);
               
               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0;
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Ask + (slPips * 10 * Point * FixedRiskReward), Digits);
                    }
                  
                  if(Ask > sl)
                    {
                     int t = OrderSend(Symbol(), OP_BUY, calculatedLot, Ask, 3, sl, actualTP, "SMC V1.03 Buy", MagicNumber, 0, clrBlue);
                     if(t > 0)
                       {
                        Print("Compra SMC V1.03 ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips (Buffer ATR/Fijo: ", bufferPips, " pips).");
                        if(InpSendPush) SendNotification("Asian Breakout V1.03 [" + Symbol() + "]: COMPRA Auto abierta a " + DoubleToStr(Ask, Digits));
                        sweptLow = false;
                       }
                     else Print("Error abriendo Compra SMC V1.03: ", GetLastError());
                    }
                 }
              }
           }
        }
      else
        {
         int objIdx = ObjectFind(0, ManualBoxName);
         if(objIdx >= 0)
           {
            double price1 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE1);
            double price2 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE2);
            
            double boxTop = MathMax(price1, price2);
            double boxBottom = MathMin(price1, price2);
            
            static bool boxDetected = false;
            if(!boxDetected)
              {
               Print("SMC V1.03: Caja '", ManualBoxName, "' detectada visualmente. Base: ", boxBottom, " Techo: ", boxTop, " (AsianHigh:", asianHigh, " AsianLow:", asianLow, ")");
               boxDetected = true;
              }
            
            double limitPrice = 0, stopLoss = 0, takeProfit = 0, slPips = 0;
            int orderType = -1;
            double bufferPips = GetSLBufferPips();
            
            if(boxBottom >= asianHigh)
              {
               limitPrice = boxBottom; 
               stopLoss = boxTop + bufferPips * 10 * Point; 
               if((stopLoss - limitPrice) / (10 * Point) < MinSLPips) stopLoss = limitPrice + MinSLPips * 10 * Point;
               slPips = (stopLoss - limitPrice) / (10 * Point);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice - (slPips * 10 * Point * FixedRiskReward), Digits);
               else takeProfit = asianLow;  
               orderType = OP_SELLLIMIT;
              }
            else if(boxTop <= asianLow)
              {
               limitPrice = boxTop; 
               stopLoss = boxBottom - bufferPips * 10 * Point; 
               if((limitPrice - stopLoss) / (10 * Point) < MinSLPips) stopLoss = limitPrice + MinSLPips * 10 * Point;
               slPips = (stopLoss - limitPrice) / (10 * Point);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice + (slPips * 10 * Point * FixedRiskReward), Digits);
               else takeProfit = asianHigh; 
               orderType = OP_BUYLIMIT;
              }
              
            if(orderType >= 0 && limitPrice > 0)
              {
               limitPrice = NormalizeDouble(limitPrice, Digits);
               stopLoss = NormalizeDouble(stopLoss, Digits);
               takeProfit = NormalizeDouble(takeProfit, Digits);
               
               bool validLimit = false;
               if(orderType == OP_BUYLIMIT && Ask > limitPrice) validLimit = true;
               if(orderType == OP_SELLLIMIT && Bid < limitPrice) validLimit = true;
               
               if(validLimit)
                 {
                  double lot = CalculateLotSize(slPips);
                  int ticket = OrderSend(Symbol(), orderType, lot, limitPrice, 3, stopLoss, takeProfit, "SMC V1.03 Limit Manual", MagicNumber, 0, (orderType == OP_BUYLIMIT) ? clrBlue : clrRed);
                  if(ticket > 0)
                    {
                     lastTradeDay = currentDay;
                     boxDetected = false;
                     Print("Orden Limit SMC V1.03 Manual colocada exitosamente. Lote: ", lot, " TP: ", takeProfit);
                     if(InpSendPush) SendNotification("Asian Breakout V1.03 [" + Symbol() + "]: Orden Limit colocada a " + DoubleToStr(limitPrice, Digits));
                     ObjectDelete(0, ManualBoxName);
                    }
                  else
                    {
                     Print("Error al poner la Orden Limit V1.03 Manual: ", GetLastError());
                    }
                 }
               else
                 {
                  static datetime lastPrint = 0;
                  if(Time[0] != lastPrint)
                    {
                     Print("SMC V1.03 Esperando... Precio actual no permite colocar Limit. (Bid: ", Bid, " Limit: ", limitPrice, ")");
                     lastPrint = Time[0];
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
