//+------------------------------------------------------------------+
//|                                     anti_asian_breakout_V1.02.mq4 |
//|                                      Generated by Antigravity    |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.02"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input bool     UseDynamicLot     = true;       // Activar Lote Dinámico (1%)
input double   RiskPercent       = 1.0;        // Riesgo por operación (%)
input bool     InpSendPush       = true;       // Enviar Notificación al Móvil
input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input int      MinBoxPips        = 10;         // Tamaño Mínimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamaño Máximo Caja (pips)
input int      MagicNumber       = 200200;     // Magic Number (Distinto para Anti-Breakout)
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling)
input int      EndHour           = 8;          // Hora fin Asia (08:00 Skilling)
input int      MaxTradingHour    = 15;         // Cortafuegos: Máxima hora para buscar patrón

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = true;       // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = false;      // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = true;       // Activar Trailing Stop (Por defecto en Continuación)
input int      TrailingPips      = 15;         // Distancia del Trailing (pips)

input string   Trailing_Adv_Settings = "--- TRAILING ACELERADO ---";
input bool     UseAcceleratedTrailing = true;  // Activar Trailing más ajustado
input int      AccelActivationPips    = 25;    // Pips de ganancia para activarlo
input int      AccelTrailingPips      = 5;     // Nueva distancia del Trailing (muy ajustado)

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      MinSLPips         = 5;          // Stop Loss mínimo (pips)

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = true;       // Activar Auto Break-Even
input int      BreakEvenActivation = 15;         // Pips ganancia para activar BE
input int      BreakEvenExtraPips  = 1;          // Pips extra sobre SL para asegurar comisiones
input int      MaxTradesPerDay     = 1;          // Solo permitimos 1 entrada buena al día en continuación

input string   Mode_Settings     = "--- MODO CONTINUACION ---";
input int      MinBreakoutBodyPips = 2;        // Min pips cuerpo vela ruptura M15 (Intención)
input int      MaxPatternBars      = 8;        // Max velas M15 para que se complete el patrón

input string   Trend_Settings    = "--- FILTRO DE TENDENCIA ---";
input bool     UseTrendFilter    = true;       // Activar Filtro EMA (Modo Auto)
input ENUM_TIMEFRAMES TrendTF    = PERIOD_H1;  // Temporalidad de Tendencia
input int      FastEMAPeriod     = 50;         // Periodo EMA Rapida
input int      SlowEMAPeriod     = 200;        // Periodo EMA Lenta

//--- Global variables
int lastTradeDay = -1;
int currentSessionDay = -1;

// State variables for Long pattern
int stateLong = 0; // 0=IDLE, 1=BREAKOUT, 2=PULLBACK
double longBreakoutLow = 0;
datetime timeLongBreakout = 0;

// State variables for Short pattern
int stateShort = 0; // 0=IDLE, 1=BREAKOUT, 2=PULLBACK
double shortBreakoutHigh = 0;
datetime timeShortBreakout = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;
   
   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   
   if(tickValue == 0) return FixedLotSize;
   
   double slPoints = slDistancePips * 10.0;
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   
   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;
   
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;
   
   double normalTrailingPoints = TrailingPips * 10.0 * Point;
   double accelTrailingPoints  = AccelTrailingPips * 10.0 * Point;
   double accelActivationPoints = AccelActivationPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               double currentProfitPoints = Bid - OrderOpenPrice();
               double activeTrailingPoints = normalTrailingPoints;
               
               if(UseAcceleratedTrailing && currentProfitPoints >= accelActivationPoints)
                 {
                  activeTrailingPoints = accelTrailingPoints;
                 }
                 
               if(currentProfitPoints > activeTrailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - activeTrailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               double currentProfitPoints = OrderOpenPrice() - Ask;
               double activeTrailingPoints = normalTrailingPoints;
               
               if(UseAcceleratedTrailing && currentProfitPoints >= accelActivationPoints)
                 {
                  activeTrailingPoints = accelTrailingPoints;
                 }
                 
               if(currentProfitPoints > activeTrailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + activeTrailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;
   
   double activationPoints = BreakEvenActivation * 10.0 * Point;
   double extraPoints = BreakEvenExtraPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask)
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   if(!UseTrendFilter) return true;
   
   double fastEMA = iMA(Symbol(), TrendTF, FastEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), TrendTF, SlowEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double currentPrice = iClose(Symbol(), TrendTF, 1); 
   
   if(isBuy)
     {
      if(fastEMA > slowEMA && currentPrice > slowEMA) return true;
     }
   else
     {
      if(fastEMA < slowEMA && currentPrice < slowEMA) return true;
     }
     
   return false;
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int currentDay = Day();
   int count = 0;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay) count++;
           }
        }
     }
     
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay) count++;
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   ManageTrailingStop();
   ManageAutoBreakEven();
   
   int currentHour = Hour();
   int currentDay = Day();
   
   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      return;
     }

   // Cancelacion por Cortafuegos Horario
   if(currentHour >= MaxTradingHour)
     {
      if(stateLong > 0 || stateShort > 0)
        {
         stateLong = 0;
         stateShort = 0;
         Print("Anti-Breakout: Cortafuegos Horario (", MaxTradingHour, ":00) alcanzado. Patrones pendientes abortados.");
        }
     }

   if(currentHour >= EndHour && currentHour < MaxTradingHour)
     {
      if(currentDay != currentSessionDay)
        {
         stateLong = 0;
         stateShort = 0;
         currentSessionDay = currentDay;
        }

      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      if(!isTradingDay || currentDay == lastTradeDay) return;

      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + StartHour * 3600;
      datetime timeEnd = currentDayStart + EndHour * 3600;
      
      int shiftStart = iBarShift(Symbol(), PERIOD_M15, timeStart);
      int shiftEnd = iBarShift(Symbol(), PERIOD_M15, timeEnd);
      
      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd) return;
      
      int barsCount = shiftStart - shiftEnd;
      int highestIdx = iHighest(Symbol(), PERIOD_M15, MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), PERIOD_M15, MODE_LOW, barsCount, shiftEnd);
      
      if(highestIdx < 0 || lowestIdx < 0) return;
      
      double asianHigh = iHigh(Symbol(), PERIOD_M15, highestIdx);
      double asianLow  = iLow(Symbol(), PERIOD_M15, lowestIdx);
      
      double boxSizePips = (asianHigh - asianLow) / (10 * Point);
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         return;
        }
      
      static datetime lastBarTimeM15 = 0;
      bool isNewBarM15 = false;
      datetime currentM15Time = iTime(Symbol(), PERIOD_M15, 0);
      if(currentM15Time != lastBarTimeM15)
        {
         isNewBarM15 = true;
         lastBarTimeM15 = currentM15Time;
        }
      
      if(isNewBarM15)
        {
         double closeM15 = iClose(Symbol(), PERIOD_M15, 1);
         double openM15 = iOpen(Symbol(), PERIOD_M15, 1);
         double lowM15 = iLow(Symbol(), PERIOD_M15, 1);
         double highM15 = iHigh(Symbol(), PERIOD_M15, 1);
         
         // --- Mantenimiento de Estados (Invalidados por SL o Tiempo) ---
         if(stateLong > 0)
           {
            int barsPassed = iBarShift(Symbol(), PERIOD_M15, timeLongBreakout) - 1; // -1 porque Shift 1 es la vela actual cerrada
            if(barsPassed > MaxPatternBars || lowM15 < longBreakoutLow)
              {
               stateLong = 0; 
               Print("Anti-Breakout: Patron Largo invalidado (Caducidad o Soporte roto).");
              }
           }
         if(stateShort > 0)
           {
            int barsPassed = iBarShift(Symbol(), PERIOD_M15, timeShortBreakout) - 1;
            if(barsPassed > MaxPatternBars || highM15 > shortBreakoutHigh)
              {
               stateShort = 0;
               Print("Anti-Breakout: Patron Corto invalidado (Caducidad o Resistencia rota).");
              }
           }

         // --- STATE MACHINE: LONG (Ruptura Alcista) ---
         if(stateLong == 0)
           {
            // PASO 1: Ruptura
            if(closeM15 > asianHigh)
              {
               double bodyPips = MathAbs(closeM15 - openM15) / (10 * Point);
               if(bodyPips >= MinBreakoutBodyPips)
                 {
                  stateLong = 1;
                  longBreakoutLow = lowM15;
                  timeLongBreakout = iTime(Symbol(), PERIOD_M15, 1);
                  Print("Anti-Breakout: Ruptura Alcista detectada. SL base en: ", longBreakoutLow);
                 }
              }
           }
         else if(stateLong == 1)
           {
            // PASO 2: Amago (Pullback) - Vela bajista
            if(closeM15 < openM15)
              {
               stateLong = 2;
               Print("Anti-Breakout: Amago bajista detectado, esperando vela de confirmacion.");
              }
           }
         else if(stateLong == 2)
           {
            // PASO 3: Confirmación - Vela alcista envolvente o fuerte
            double prevOpen = iOpen(Symbol(), PERIOD_M15, 2);
            if(closeM15 > openM15 && closeM15 > prevOpen) 
              {
               if(IsTrendAligned(true))
                 {
                  // EJECUCION DE COMPRA
                  double slPips = (Ask - longBreakoutLow) / (10 * Point);
                  if(slPips < MinSLPips) slPips = MinSLPips;
                  double sl = NormalizeDouble(Ask - slPips * 10 * Point, Digits);
                  
                  double lot = CalculateLotSize(slPips);
                  double tp = 0;
                  if(UseFixedRR) tp = NormalizeDouble(Ask + (slPips * 10 * Point * FixedRiskReward), Digits);
                  
                  int t = OrderSend(Symbol(), OP_BUY, lot, Ask, 3, sl, tp, "Anti-Breakout Buy", MagicNumber, 0, clrBlue);
                  if(t > 0)
                    {
                     Print("Anti-Breakout: Compra Confirmada!");
                     if(InpSendPush) SendNotification("Anti-Breakout: COMPRA Auto abierta.");
                     lastTradeDay = currentDay;
                     stateLong = 0;
                    }
                  else
                    {
                     Print("Error al abrir COMPRA Anti-Breakout: ", GetLastError());
                    }
                 }
               else
                 {
                  stateLong = 0; 
                  Print("Anti-Breakout: Compra bloqueada por filtro de tendencia. Reiniciando.");
                 }
              }
           }

         // --- STATE MACHINE: SHORT (Ruptura Bajista) ---
         if(stateShort == 0)
           {
            // PASO 1: Ruptura
            if(closeM15 < asianLow)
              {
               double bodyPips = MathAbs(closeM15 - openM15) / (10 * Point);
               if(bodyPips >= MinBreakoutBodyPips)
                 {
                  stateShort = 1;
                  shortBreakoutHigh = highM15;
                  timeShortBreakout = iTime(Symbol(), PERIOD_M15, 1);
                  Print("Anti-Breakout: Ruptura Bajista detectada. SL base en: ", shortBreakoutHigh);
                 }
              }
           }
         else if(stateShort == 1)
           {
            // PASO 2: Amago (Pullback) - Vela alcista
            if(closeM15 > openM15)
              {
               stateShort = 2;
               Print("Anti-Breakout: Amago alcista detectado, esperando vela de confirmacion.");
              }
           }
         else if(stateShort == 2)
           {
            // PASO 3: Confirmación - Vela bajista envolvente
            double prevOpen = iOpen(Symbol(), PERIOD_M15, 2);
            if(closeM15 < openM15 && closeM15 < prevOpen) 
              {
               if(IsTrendAligned(false))
                 {
                  // EJECUCION DE VENTA
                  double slPips = (shortBreakoutHigh - Bid) / (10 * Point);
                  if(slPips < MinSLPips) slPips = MinSLPips;
                  double sl = NormalizeDouble(Bid + slPips * 10 * Point, Digits);
                  
                  double lot = CalculateLotSize(slPips);
                  double tp = 0;
                  if(UseFixedRR) tp = NormalizeDouble(Bid - (slPips * 10 * Point * FixedRiskReward), Digits);
                  
                  int t = OrderSend(Symbol(), OP_SELL, lot, Bid, 3, sl, tp, "Anti-Breakout Sell", MagicNumber, 0, clrRed);
                  if(t > 0)
                    {
                     Print("Anti-Breakout: Venta Confirmada!");
                     if(InpSendPush) SendNotification("Anti-Breakout: VENTA Auto abierta.");
                     lastTradeDay = currentDay;
                     stateShort = 0;
                    }
                  else
                    {
                     Print("Error al abrir VENTA Anti-Breakout: ", GetLastError());
                    }
                 }
               else
                 {
                  stateShort = 0;
                  Print("Anti-Breakout: Venta bloqueada por filtro de tendencia. Reiniciando.");
                 }
              }
           }
        }
     }
  }
