//+------------------------------------------------------------------+
//|                                                  SessionsBox.mq4 |
//|                                      Generated by Antigravity    |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.10"
#property strict
#property indicator_chart_window

//--- Input parameters
input bool   EnableAsia      = true;         // Mostrar Sesion Asiatica
input int    AsiaStartHour   = 2;            // Inicio Asia (Hora Broker)
input int    AsiaEndHour     = 8;            // Fin Asia (Hora Broker)
input color  AsiaBoxColor    = clrAliceBlue; // Color Caja Asiatica

input bool   EnableLondon    = true;         // Mostrar Sesion Londres
input int    LondonStartHour = 9;            // Inicio Londres (Hora Broker)
input int    LondonEndHour   = 18;           // Fin Londres (Hora Broker)
input color  LondonBoxColor  = clrMistyRose; // Color Caja Londres

input bool   EnableNY        = true;         // Mostrar Sesion Nueva York
input int    NYStartHour     = 14;           // Inicio NY (Hora Broker)
input int    NYEndHour       = 23;           // Fin NY (Hora Broker)
input color  NYBoxColor      = clrHoneydew;  // Color Caja Nueva York

input int    DaysToDraw      = 30;           // Días hacia atrás para dibujar

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   IndicatorShortName("Market Sessions Box");
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Custom indicator deinitialization function                       |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   ObjectsDeleteAll(0, "SessionBox_");
  }

//+------------------------------------------------------------------+
//| Helper function to draw a session box                            |
//+------------------------------------------------------------------+
void DrawSessionBox(string prefix, datetime dayStart, int startH, int endH, color boxColor, datetime currentTime)
  {
   datetime t1 = dayStart + startH * 3600;
   datetime t2 = dayStart + endH * 3600;
   
   if(currentTime < t1) return; // Aún no empieza la sesión
   
   // En el Probador, pintamos siempre la caja completa de t1 a t2 para evitar que se achique
   int shift1 = iBarShift(Symbol(), Period(), t1);
   
   datetime evalEndTime = (currentTime < t2) ? currentTime : t2;
   int shift2 = iBarShift(Symbol(), Period(), evalEndTime);
   
   if(shift1 < 0 || shift2 < 0 || shift1 < shift2) return;
   
   double maxPrice = -1.0;
   double minPrice = 99999.0;
   bool valid = false;
   
   // Bucle robusto para evitar fallos de iHighest en el simulador
   for(int j = shift2; j <= shift1; j++)
     {
      if(j < 0 || j >= Bars) continue;
      if(High[j] > maxPrice) maxPrice = High[j];
      if(Low[j] < minPrice) minPrice = Low[j];
      valid = true;
     }
     
   if(valid)
     {
      string objName = "SessionBox_" + prefix + "_" + TimeToString(dayStart, TIME_DATE);
      
      if(ObjectFind(0, objName) < 0)
        {
         ObjectCreate(0, objName, OBJ_RECTANGLE, 0, t1, maxPrice, t2, minPrice);
         ObjectSetInteger(0, objName, OBJPROP_COLOR, boxColor);
         ObjectSetInteger(0, objName, OBJPROP_BACK, true);
         ObjectSetInteger(0, objName, OBJPROP_SELECTABLE, false);
         ObjectSetInteger(0, objName, OBJPROP_HIDDEN, true);
        }
      else
        {
         // Si la sesion no ha terminado, actualizamos su dimension vertical
         if(currentTime <= t2)
           {
            ObjectSetDouble(0, objName, OBJPROP_PRICE1, maxPrice);
            ObjectSetDouble(0, objName, OBJPROP_PRICE2, minPrice);
            ObjectSetInteger(0, objName, OBJPROP_TIME1, t1);
            ObjectSetInteger(0, objName, OBJPROP_TIME2, t2); // Siempre anclado a t2
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   if(prev_calculated == 0)
     {
      ObjectsDeleteAll(0, "SessionBox_");
     }
     
   datetime currentTime = TimeCurrent();
   
   // Si es la primera vez, dibuja todos los días. Si no, actualiza solo hoy y ayer.
   int daysLimit = (prev_calculated == 0) ? DaysToDraw : 2;
   
   for(int i = 0; i < daysLimit; i++)
     {
      datetime dayStart = iTime(Symbol(), PERIOD_D1, i);
      if(dayStart == 0) continue;
      
      if(EnableAsia)   DrawSessionBox("Asia", dayStart, AsiaStartHour, AsiaEndHour, AsiaBoxColor, currentTime);
      if(EnableLondon) DrawSessionBox("London", dayStart, LondonStartHour, LondonEndHour, LondonBoxColor, currentTime);
      if(EnableNY)     DrawSessionBox("NY", dayStart, NYStartHour, NYEndHour, NYBoxColor, currentTime);
     }
     
   return(rates_total);
  }
//+------------------------------------------------------------------+
