//+------------------------------------------------------------------+
//|                                                 CandleTime.mq4   |
//|                                         Generated by Antigravity |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.00"
#property strict
#property indicator_chart_window

input color  TextColor = clrWhite;     // Color del texto
input int    TextSize  = 12;           // Tamaño de la fuente
input int    Corner    = CORNER_RIGHT_LOWER; // Esquina (0=Izq-Sup, 1=Der-Sup, 2=Izq-Inf, 3=Der-Inf)
input int    X_Offset  = 20;           // Distancia X desde la esquina
input int    Y_Offset  = 20;           // Distancia Y desde la esquina

string labelName = "CandleTime_Label";

//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
  {
   if(ObjectFind(0, labelName) < 0)
     {
      ObjectCreate(0, labelName, OBJ_LABEL, 0, 0, 0);
      ObjectSetInteger(0, labelName, OBJPROP_CORNER, Corner);
      ObjectSetInteger(0, labelName, OBJPROP_XDISTANCE, X_Offset);
      ObjectSetInteger(0, labelName, OBJPROP_YDISTANCE, Y_Offset);
      ObjectSetInteger(0, labelName, OBJPROP_COLOR, TextColor);
      ObjectSetInteger(0, labelName, OBJPROP_FONTSIZE, TextSize);
      ObjectSetString(0, labelName, OBJPROP_FONT, "Arial");
      ObjectSetInteger(0, labelName, OBJPROP_SELECTABLE, false);
      ObjectSetInteger(0, labelName, OBJPROP_HIDDEN, true);
     }
     
   EventSetTimer(1); // Actualizar cada segundo
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Custom indicator deinitialization function                       |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   EventKillTimer();
   ObjectDelete(0, labelName);
  }

//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
  {
   UpdateTimer();
   return(rates_total);
  }

//+------------------------------------------------------------------+
//| Timer event function                                             |
//+------------------------------------------------------------------+
void OnTimer()
  {
   UpdateTimer();
  }

//+------------------------------------------------------------------+
//| Update the timer label                                           |
//+------------------------------------------------------------------+
void UpdateTimer()
  {
   datetime nextCandleTime = Time[0] + PeriodSeconds();
   int secondsLeft = (int)(nextCandleTime - TimeCurrent());
   
   if(secondsLeft < 0) secondsLeft = 0;
   
   int h = secondsLeft / 3600;
   int m = (secondsLeft % 3600) / 60;
   int s = secondsLeft % 60;
   
   string timeText = "";
   if(h > 0)
      timeText = StringFormat("Vela cierra en: %02d:%02d:%02d", h, m, s);
   else
      timeText = StringFormat("Vela cierra en: %02d:%02d", m, s);
      
   ObjectSetString(0, labelName, OBJPROP_TEXT, timeText);
   ChartRedraw(0);
  }
//+------------------------------------------------------------------+
