//+------------------------------------------------------------------+
//|                                                ORB_NewYork_V1.01.mq4 |
//|                                                   Generated by Antigravity |
//|                                                                      |
//| V1.01: anadidos los 3 filtros de Alex (RVol, VWAP, solo NAS100)     |
//| V1.00: estrategia ORB estandar del video (9:30 NY, M5 rango, M15    |
//|        confirmacion, SL en el medio del rango, TP 1:1 / 2:1).       |
//| Estrategia de Scalping ORB (Opening Range Breakout) segun Alex Ruiz  |
//| Video: https://www.youtube.com/watch?v=yFUJ9p8mC_Y                   |
//|                                                                      |
//| REGLAS ESTANDAR DEL VIDEO:                                           |
//|  1) Operar la apertura de Nueva York (9:30 EST). Los primeros 15     |
//|     minutos (9:30-9:45) forman el rango de apertura.                 |
//|  2) Usar velas M5 durante esos 15 minutos para marcar el maximo y    |
//|     el minimo del rango.                                             |
//|  3) Pasados los 15 minutos, pasar a M15 y esperar a que una vela     |
//|     CIERRE fuera del rango (rompe y cierra por arriba o por abajo).  |
//|  4) Entrar en la APERTURA de la siguiente vela: COMPRA si rompe por  |
//|     arriba, VENTA si rompe por abajo.                                |
//|  5) SL en el punto MEDIO del rango. TP a ratio 1:1. Opcional del     |
//|     video: cerrar el 75% a 1:1 y el 25% restante a 2:1.              |
//|                                                                      |
//| MEJORA DEL VIDEO (la "opcion inteligente"): filtrar las falsas       |
//| rupturas. El propio video muestra que las dobles rupturas ocurren    |
//| ~40% de las veces y dan esperanza matematica negativa. Alex anade    |
//| TRES filtros a la estrategia base (V1.00 con filtros Alex):          |
//|  1) RVol (Volumen Relativo): la ruptura solo se opera si el volumen  |
//|     de la vela de ruptura esta POR ENCIMA del promedio historico     |
//|     para esa misma hora del dia (ej. 1.50x en el video). Volumen     |
//|     debil = falsa ruptura (no se opera).                             |
//|  2) VWAP (equilibrio del dia): ruptura al alza exige precio POR      |
//|     ENCIMA del VWAP; ruptura a la baja exige precio POR DEBAJO.      |
//|  3) Operar SOLO el Nasdaq 100 (volatilidad, amplitud y               |
//|     concentracion en tecnologicas). Este filtro es de SELECCION DE   |
//|     ACTIVO: ejecuta el EA en el simbolo de tu broker del NAS100      |
//|     (US100, USTEC, NAS100...).                                       |
//| En la version mejorada el R:R objetivo es 2:1 (SL sigue en el punto  |
//| medio del rango), con gestion mixta opcional (ej. 75% a 1:1 y 25% a  |
//| 2:1). Filtros adicionales incluidos: UNA sola entrada al dia, rango  |
//| dentro de limites, hora limite de entrada y noticias (opcional).     |
//|                                                                      |
//| HORARIO: la ventana se define en HORA DEL BROKER. Para brokers       |
//| GMT+2/GMT+3 (Skilling, RoboMarkets, etc.) las 9:30 NY = 16:30 hora   |
//| del broker, y la diferencia broker-NY es constante (~7h) todo el     |
//| anio (ambos cambian el reloj en fechas similares). Si tu broker usa  |
//| otro offset, ajusta SessionStartHour/SessionStartMinute para que     |
//| coincida con las 9:30 de Nueva York en tu terminal.                  |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.01"
#property strict

//--- Input parameters
input string   General_Settings     = "--- AJUSTES GENERALES ---";
input int      MagicNumber          = 301001;     // Magic Number
input bool     UseDynamicLot        = true;       // Activar Lote Dinamico (1%)
input double   RiskPercent          = 1.0;        // Riesgo por operacion (%)
input double   FixedLotSize         = 0.10;       // Lote Fijo (si Auto es false)
input bool     InpSendPush          = true;       // Enviar Notificacion al Movil
input bool     OnlyNasdaq           = true;       // Operar SOLO el Nasdaq 100 (filtro #3 de Alex)

input string   Session_Settings     = "--- VENTANA ORB (hora del broker) ---";
input int      SessionStartHour     = 16;         // Hora de apertura NY (broker). 16 = 9:30 NY en GMT+2/+3
input int      SessionStartMinute   = 30;         // Minutos de apertura NY (broker)
input int      OrbMinutes           = 15;         // Duracion del rango de apertura (min)
input ENUM_TIMEFRAMES OrbTF         = PERIOD_M5;  // Timeframe del rango (video: M5)
input ENUM_TIMEFRAMES BreakoutTF    = PERIOD_M15; // Timeframe de confirmacion de ruptura (video: M15)

input string   Days_Settings        = "--- FILTRO DE DIAS ---";
input bool     TradeMonday          = true;       // Operar Lunes
input bool     TradeTuesday         = true;       // Operar Martes
input bool     TradeWednesday       = true;       // Operar Miercoles
input bool     TradeThursday        = true;       // Operar Jueves
input bool     TradeFriday          = true;       // Operar Viernes

input string   Range_Settings       = "--- FILTROS DEL RANGO ---";
input double   MinRangePips         = 8.0;        // Rango minimo valido (pips)
input double   MaxRangePips         = 60.0;       // Rango maximo valido (pips)
input int      MinSLPips            = 5;          // Stop Loss minimo (pips)
input int      MaxEntryHour         = 19;         // Hora limite de entrada (broker). 19 ~ 12:00 NY

input string   Target_Settings      = "--- OBJETIVO Y GESTION ---";
input bool     UsePartialClose      = true;       // Cerrar % a TP1 (1:1) y el resto a TP2 (2:1)
input double   PartialClosePercent  = 75.0;       // % del lote a cerrar en TP1 (ej. 75%)
input double   TP1Ratio             = 1.0;        // Ratio TP1 (1:1) -> cierre parcial
input double   TP2Ratio             = 2.0;        // Ratio TP2 (2:1) -> resto de la posicion
input bool     UseAutoBreakEven     = true;       // Activar Auto Break-Even
input int      BreakEvenActivation  = 15;         // Pips ganancia para activar BE
input int      BreakEvenExtraPips   = 1;          // Pips extra sobre SL para asegurar comisiones
input bool     UseTrailingStop      = false;      // Trailing Stop (solo si TP = 0)
input int      TrailingPips         = 15;         // Distancia del Trailing (pips)
input int      MaxTradesPerDay      = 1;          // Max. entradas al dia (1 = primera ruptura, anti doble ruptura)
input bool     CloseAtEndOfDay      = true;       // Cerrar posiciones al final del dia
input int      EndOfDayHour         = 23;         // Hora de cierre de fin de dia (broker)

input string   Trend_Settings       = "--- FILTRO DE TENDENCIA ---";
input bool     UseTrendFilter       = false;      // Activar Filtro EMA (opcional)
input ENUM_TIMEFRAMES TrendTF       = PERIOD_M15; // Timeframe de las EMAs
input int      FastEMAPeriod        = 50;         // Periodo EMA Rapida
input int      SlowEMAPeriod        = 200;        // Periodo EMA Lenta

input string   AlexFilters_Settings = "--- MEJORA ALEX: FILTROS RVol + VWAP ---";
input bool     UseRVolFilter        = true;       // Activar filtro Volumen Relativo (RVol)
input double   MinRVol              = 1.0;        // RVol minimo exigido (1.0 = sobre promedio; el video usa ~1.50)
input int      RVolDays             = 20;         // Dias historicos para el promedio del RVol
input bool     UseVWAPFilter        = true;       // Activar filtro VWAP (precio vs equilibrio del dia)

input string   News_Settings        = "--- NEWS FILTER (API) ---";
input bool     UseNewsFilter        = false;      // Activar Filtro de Noticias
input int      MinsBeforeNews       = 30;         // Minutos antes de la noticia para pausar
input int      MinsAfterNews        = 30;         // Minutos despues de la noticia para pausar
input bool     FilterHighImpact     = true;       // Filtrar Carpetas Rojas (Alta)
input bool     FilterMedImpact      = false;      // Filtrar Carpetas Naranjas (Media)

input string   Visual_Settings      = "--- VISUAL ---";
input bool     DrawORBBox           = true;       // Dibujar el rectangulo del rango ORB

//--- Global variables
double Pip;
double g_orbHigh  = 0;
double g_orbLow   = 0;
double g_orbMid   = 0;
double g_orbSizePips = 0;
datetime g_windowStart = 0;
datetime g_windowEnd   = 0;
int g_state   = 0;      // 0=esperando, 1=dentro de la ventana, 2=armado (esperando ruptura), 3=terminado/hoy
int g_dayKey  = 0;
bool g_entered = false;
datetime g_lastBreakoutBar = 0;
int g_partialClosedTickets[100];
int g_partialClosedCount = 0;

//+------------------------------------------------------------------+
//| Devuelve una clave de fecha completa AAAAMMDD para comparar dias |
//+------------------------------------------------------------------+
int GetDateKey(datetime t)
  {
   return TimeYear(t) * 10000 + TimeMonth(t) * 100 + TimeDay(t);
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   Pip = (Digits == 3 || Digits == 5) ? 10.0 * Point : 1.0 * Point;

   // Los indices (NASDAQ) se cotizan en puntos (ej. 28075.00, Point=0.01),
   // no en pips FX. Para que los filtros "pips" de la estrategia operen en
   // puntos del indice (el rango ORB del video es 8-60 puntos, no 8-60
   // decimas), definimos 1 pip = 1 punto del indice (= 100 * Point).
   string sym = Symbol();
   bool isNasdaq = (StringFind(sym, "NAS") >= 0) ||
                   (StringFind(sym, "US100") >= 0) ||
                   (StringFind(sym, "USTEC") >= 0) ||
                   (StringFind(sym, "NDX") >= 0);
   if(isNasdaq)
      Pip = 100.0 * Point;

   int totalStart = SessionStartHour * 60 + SessionStartMinute;
   int totalEnd   = totalStart + OrbMinutes;
   int endHour = totalEnd / 60;
   int endMin  = totalEnd % 60;

   Print("ORB New York V1.01: ventana ", SessionStartHour, ":", StringFormat("%02d", SessionStartMinute),
         " a ", endHour, ":", StringFormat("%02d", endMin),
         " (hora del broker). Para brokers GMT+2/GMT+3 eso es 9:30-9:45 NY.");

   // Filtro #3 de Alex: este EA SOLO opera el Nasdaq 100
   if(OnlyNasdaq)
     {
      if(!isNasdaq)
        {
         Print("ORB: este EA SOLO opera el Nasdaq 100 (filtro Alex). Simbolo actual: ", sym, ". EA desactivado.");
         return INIT_FAILED;
        }
      Print("ORB: simbolo ", sym, " verificado como Nasdaq 100. OK.");
     }

   g_lastBreakoutBar = iTime(Symbol(), BreakoutTF, 0);

   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   DeleteORBBox();
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;

   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);

   if(tickValue == 0) return FixedLotSize;

   double slPoints = slDistancePips * (Pip / Point);
   double lot = riskAmount / (slPoints * tickValue);

   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;

   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;

   double trailingPoints = TrailingPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderTakeProfit() > 0) continue; // con TP estructural el trailing no pisa
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;

   double activationPoints = BreakEvenActivation * Pip;
   double extraPoints = BreakEvenExtraPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask)
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Comprueba si un ticket ya fue registrado como parcialmente       |
//+------------------------------------------------------------------+
bool IsAlreadyPartiallyClosed(int ticket)
  {
   for(int k = 0; k < g_partialClosedCount; k++)
      if(g_partialClosedTickets[k] == ticket) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Cierre parcial: cierra PartialClosePercent% del lote cuando el   |
//| precio alcanza TP1Ratio (ej. 1:1) y deja el resto correr hasta    |
//| TP2Ratio (ej. 2:1) que va como TakeProfit de la orden.            |
//+------------------------------------------------------------------+
void ManageORBPartialClose()
  {
   if(!UsePartialClose || TP1Ratio <= 0) return;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue;
            if(OrderStopLoss() <= 0) continue;
            if(IsAlreadyPartiallyClosed(OrderTicket())) continue;

            double dist = 0;
            if(OrderType() == OP_BUY)  dist = OrderOpenPrice() - OrderStopLoss();
            else                       dist = OrderStopLoss() - OrderOpenPrice();
            if(dist <= 0) continue;

            double target = dist * TP1Ratio;
            double profit = 0;
            if(OrderType() == OP_BUY)  profit = Bid - OrderOpenPrice();
            else                       profit = OrderOpenPrice() - Ask;

            if(profit >= target)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;

               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  int origTicket = OrderTicket();
                  bool res = OrderClose(origTicket, lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
                  if(res)
                    {
                     if(g_partialClosedCount < 100)
                       {
                        g_partialClosedTickets[g_partialClosedCount] = origTicket;
                        g_partialClosedCount++;
                       }
                     Print("ORB: cierre parcial ejecutado (", lotToClose, " lotes) a TP", TP1Ratio, ":1.");
                     if(InpSendPush) SendNotification("ORB [" + Symbol() + "]: cierre parcial en TP1 alcanzado.");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Cierra todas las operaciones ORB abiertas                        |
//+------------------------------------------------------------------+
void CloseAllORBTrades(string reason)
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL)
              {
               bool res = OrderClose(OrderTicket(), OrderLots(), (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
               if(res) Print("ORB: cierre de ", reason, " (", (OrderType() == OP_BUY) ? "BUY" : "SELL", ") ejecutado.");
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia basada en EMAs (opcional)                   |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   if(!UseTrendFilter) return true;

   double fastEMA = iMA(Symbol(), TrendTF, FastEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), TrendTF, SlowEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);

   if(isBuy)
     {
      if(fastEMA > slowEMA) return true;
     }
   else
     {
      if(fastEMA < slowEMA) return true;
     }

   return false;
  }

//+------------------------------------------------------------------+
//| RVol (Volumen Relativo) - filtro #1 de Alex                      |
//| Compara el volumen de la vela indicada (shift) con el promedio   |
//| de la MISMA hora del dia en los RVolDays dias anteriores.        |
//| >1 = volumen sobre lo habitual (verde, continuacion probable).   |
//| <1 = volumen debil (rojo, probable falsa ruptura).               |
//+------------------------------------------------------------------+
double GetRVol(int shift)
  {
   if(shift < 0) return 0;

   datetime barTime = iTime(Symbol(), BreakoutTF, shift);
   if(barTime <= 0) return 0;

   int secondsOfDay = (int)(barTime % 86400);
   long currentVol = iVolume(Symbol(), BreakoutTF, shift);
   if(currentVol <= 0) return 0;

   datetime midnightBar = barTime - secondsOfDay;

   double sum = 0;
   double count = 0;

   for(int d = 1; d <= RVolDays; d++)
     {
      datetime target = midnightBar - d * 86400 + secondsOfDay;
      int s = iBarShift(Symbol(), BreakoutTF, target, true);
      if(s >= 0)
        {
         long v = iVolume(Symbol(), BreakoutTF, s);
         if(v > 0)
           {
            sum += (double)v;
            count++;
           }
        }
     }

   if(count <= 0) return 0;

   double avg = sum / count;
   if(avg <= 0) return 0;

   return currentVol / avg;
  }

//+------------------------------------------------------------------+
//| VWAP (Precio Medio Ponderado por Volumen) - filtro #2 de Alex    |
//| "Equilibrio del dia": suma(TP*vol) / suma(vol) desde la          |
//| medianoche del broker hasta la vela actual.                      |
//+------------------------------------------------------------------+
double GetVWAP()
  {
   datetime now = TimeCurrent();
   datetime midnight = now - (now % 86400);

   int start = iBarShift(Symbol(), BreakoutTF, midnight);
   if(start < 0) return 0;

   double cumPV = 0;
   double cumV = 0;

   for(int i = start; i >= 0; i--)
     {
      double h = iHigh(Symbol(), BreakoutTF, i);
      double l = iLow(Symbol(), BreakoutTF, i);
      double c = iClose(Symbol(), BreakoutTF, i);
      double tp = (h + l + c) / 3.0;
      long v = iVolume(Symbol(), BreakoutTF, i);
      cumPV += tp * (double)v;
      cumV += (double)v;
     }

   if(cumV <= 0) return 0;

   return cumPV / cumV;
  }

//+------------------------------------------------------------------+
//| Comprueba si la ruptura esta alineada con el VWAP (filtro Alex)  |
//| Alza  -> el precio debe estar POR ENCIMA del VWAP.               |
//| Baja  -> el precio debe estar POR DEBAJO del VWAP.               |
//+------------------------------------------------------------------+
bool IsVWAPAligned(bool isBuy)
  {
   if(!UseVWAPFilter) return true;

   double vwap = GetVWAP();
   if(vwap <= 0) return true; // sin datos, no bloqueamos

   double price = isBuy ? Ask : Bid;

   if(isBuy)  return price > vwap;
   else       return price < vwap;
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int todayKey = GetDateKey(TimeCurrent());

   datetime seenTimes[100];
   int seenTypes[100];
   ArrayInitialize(seenTimes, 0);
   ArrayInitialize(seenTypes, -1);
   int seenCount = 0;
   int count = 0;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }

   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
   return count;
  }

//+------------------------------------------------------------------+
//| Verificar si existe alguna operacion activa del EA               |
//+------------------------------------------------------------------+
bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Filtro de dias de la semana                                      |
//+------------------------------------------------------------------+
bool IsTradingDay(int dayOfWeek)
  {
   if(dayOfWeek == 1 && TradeMonday) return true;
   if(dayOfWeek == 2 && TradeTuesday) return true;
   if(dayOfWeek == 3 && TradeWednesday) return true;
   if(dayOfWeek == 4 && TradeThursday) return true;
   if(dayOfWeek == 5 && TradeFriday) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Calcular el rango ORB desde las velas del timeframe OrbTF que    |
//| cubren la ventana [g_windowStart, g_windowEnd).                  |
//+------------------------------------------------------------------+
bool ComputeORB()
  {
   int barStart = iBarShift(Symbol(), OrbTF, g_windowStart);
   int barEnd   = iBarShift(Symbol(), OrbTF, g_windowEnd - 1);

   if(barStart < 0 || barEnd < 0 || barStart <= barEnd) return false;

   int bars = barStart - barEnd + 1;
   int highestIdx = iHighest(Symbol(), OrbTF, MODE_HIGH, bars, barEnd);
   int lowestIdx  = iLowest(Symbol(), OrbTF, MODE_LOW, bars, barEnd);

   if(highestIdx < 0 || lowestIdx < 0) return false;

   g_orbHigh = iHigh(Symbol(), OrbTF, highestIdx);
   g_orbLow  = iLow(Symbol(), OrbTF, lowestIdx);
   g_orbMid  = (g_orbHigh + g_orbLow) / 2.0;
   g_orbSizePips = (g_orbHigh - g_orbLow) / Pip;

   if(g_orbHigh <= g_orbLow)
     {
      Print("ORB: rango invalido. Dia saltado.");
      return false;
     }

   if(g_orbSizePips < MinRangePips || g_orbSizePips > MaxRangePips)
     {
      Print("ORB: rango de ", DoubleToStr(g_orbSizePips, 1), " pips fuera de limites [",
            DoubleToStr(MinRangePips, 1), ", ", DoubleToStr(MaxRangePips, 1), "]. Dia saltado.");
      return false;
     }

   Print("ORB: rango del dia High=", DoubleToStr(g_orbHigh, Digits),
         " Low=", DoubleToStr(g_orbLow, Digits),
         " Mid=", DoubleToStr(g_orbMid, Digits),
         " (" , DoubleToStr(g_orbSizePips, 1), " pips).");
   return true;
  }

//+------------------------------------------------------------------+
//| Dibuja el rectangulo del rango ORB en el grafico                 |
//+------------------------------------------------------------------+
void DrawORBBox()
  {
   if(!DrawORBBox) return;

   string name = "ORBBox_" + Symbol();

   if(ObjectFind(name) < 0)
      ObjectCreate(0, name, OBJ_RECTANGLE, 0, g_windowStart, g_orbHigh, g_windowEnd, g_orbLow);
   else
     {
      ObjectMove(0, name, 0, g_windowStart, g_orbHigh);
      ObjectMove(0, name, 1, g_windowEnd, g_orbLow);
     }

   ObjectSetInteger(0, name, OBJPROP_COLOR, clrDodgerBlue);
   ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_SOLID);
   ObjectSetInteger(0, name, OBJPROP_WIDTH, 1);
   ObjectSetInteger(0, name, OBJPROP_BACK, true);
  }

//+------------------------------------------------------------------+
//| Borra el rectangulo del rango ORB                                |
//+------------------------------------------------------------------+
void DeleteORBBox()
  {
   string name = "ORBBox_" + Symbol();
   if(ObjectFind(name) >= 0) ObjectDelete(0, name);
  }

//+------------------------------------------------------------------+
//| Intenta ejecutar la entrada por ruptura confirmada               |
//+------------------------------------------------------------------+
void TryBreakoutEntry()
  {
   // Solo al abrir una nueva vela del timeframe de ruptura
   datetime curBar = iTime(Symbol(), BreakoutTF, 0);
   if(curBar == g_lastBreakoutBar) return;
   g_lastBreakoutBar = curBar;

   // La vela que acaba de cerrar (shift 1) debe haber cerrado FUERA del rango
   double closeC = iClose(Symbol(), BreakoutTF, 1);

   bool buySignal  = (closeC > g_orbHigh);
   bool sellSignal = (closeC < g_orbLow);
   if(!buySignal && !sellSignal) return;

   Print("ORB: ruptura detectada. Close=", DoubleToStr(closeC, Digits),
         " (Alto=", DoubleToStr(g_orbHigh, Digits), " Bajo=", DoubleToStr(g_orbLow, Digits), ").");

   // Filtro de tendencia
   if(!IsTrendAligned(buySignal))
     {
      Print("ORB: entrada bloqueada por filtro de tendencia.");
      return;
     }

   // Filtro #1 de Alex: Volumen Relativo (RVol) en la vela de ruptura
   if(UseRVolFilter)
     {
      double rvol = GetRVol(1);
      if(rvol < MinRVol)
        {
         Print("ORB: ruptura bloqueada por RVol (", DoubleToStr(rvol, 2), " < ", DoubleToStr(MinRVol, 2),
               "). Volumen debil = probable falsa ruptura.");
         return;
        }
      Print("ORB: RVol de la vela de ruptura = ", DoubleToStr(rvol, 2));
     }

   // Filtro #2 de Alex: alineacion con el VWAP
   if(!IsVWAPAligned(buySignal))
     {
      Print("ORB: ruptura bloqueada por VWAP (el precio no esta del lado correcto del equilibrio del dia).");
      return;
     }

   // Filtro de noticias
   if(UseNewsFilter && IsNewsTime())
     {
      Print("ORB: entrada bloqueada por filtro de noticias.");
      return;
     }

   if(HasActiveTrades()) return;
   if(GetTradesTodayCount() >= MaxTradesPerDay) return;

   RefreshRates();

   double sl = g_orbMid;
   double entry = 0;
   double slPips = 0;
   double tpPrice = 0;
   double useRatio = UsePartialClose ? TP2Ratio : TP1Ratio;

   if(buySignal)
     {
      entry = Ask;
      slPips = (entry - sl) / Pip;
      if(slPips < MinSLPips)
        {
         Print("ORB: SL demasiado corto (", DoubleToStr(slPips, 1), " pips). Entrada saltada.");
         return;
        }
      if(useRatio > 0) tpPrice = NormalizeDouble(entry + slPips * Pip * useRatio, Digits);
     }
   else
     {
      entry = Bid;
      slPips = (sl - entry) / Pip;
      if(slPips < MinSLPips)
        {
         Print("ORB: SL demasiado corto (", DoubleToStr(slPips, 1), " pips). Entrada saltada.");
         return;
        }
      if(useRatio > 0) tpPrice = NormalizeDouble(entry - slPips * Pip * useRatio, Digits);
     }

   double lot = CalculateLotSize(slPips);

   int ticket = OrderSend(Symbol(), buySignal ? OP_BUY : OP_SELL, lot,
                          buySignal ? Ask : Bid, 3, sl, tpPrice,
                          "ORB NY " + (buySignal ? "Buy" : "Sell"), MagicNumber, 0,
                          buySignal ? clrBlue : clrRed);

   if(ticket > 0)
     {
      g_entered = true;
      g_state = 3;
      Print("ORB: ", buySignal ? "COMPRA" : "VENTA", " ejecutada. Lote=", DoubleToStr(lot, 2),
            " SL=", DoubleToStr(sl, Digits), " TP=", DoubleToStr(tpPrice, Digits),
            " R:R=", DoubleToStr(useRatio, 1));
      if(InpSendPush) SendNotification("ORB [" + Symbol() + "]: " + (buySignal ? "COMPRA" : "VENTA") + " ejecutada.");
     }
   else
     {
      Print("ORB: error al abrir orden: ", GetLastError());
     }
  }

//+------------------------------------------------------------------+
//| Dibuja una linea vertical en el grafico indicando la noticia     |
//+------------------------------------------------------------------+
void DrawNewsLine(string name, color clr, double minsToNews)
  {
   if(minsToNews == EMPTY_VALUE || minsToNews == 0) return;

   datetime newsTime = TimeCurrent() + (int)(minsToNews * 60);

   if(ObjectFind(name) < 0)
     {
      ObjectCreate(0, name, OBJ_VLINE, 0, newsTime, 0);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_DASHDOT);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
     }
   else
     {
      ObjectSetInteger(0, name, OBJPROP_TIME, newsTime);
     }
  }

//+------------------------------------------------------------------+
//| News API Integration (Global Variables from News_Fetcher)        |
//+------------------------------------------------------------------+
bool IsNewsTime()
  {
   bool isNews = false;

   if(FilterHighImpact)
     {
      if(GlobalVariableCheck("SMC_News_High"))
        {
         double minsHigh = GlobalVariableGet("SMC_News_High");
         DrawNewsLine("SMC_News_High", clrRed, minsHigh);
         if(minsHigh <= MinsBeforeNews && minsHigh >= -MinsAfterNews) isNews = true;
        }
     }

   if(FilterMedImpact)
     {
      if(GlobalVariableCheck("SMC_News_Med"))
        {
         double minsMed = GlobalVariableGet("SMC_News_Med");
         DrawNewsLine("SMC_News_Med", clrOrange, minsMed);
         if(minsMed <= MinsBeforeNews && minsMed >= -MinsAfterNews) isNews = true;
        }
     }

   return isNews;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   ManageTrailingStop();
   ManageAutoBreakEven();
   ManageORBPartialClose();

   int currentHour = Hour();
   int dayKey = GetDateKey(TimeCurrent());
   datetime now = TimeCurrent();

   // Cierre de fin de dia (Time Stop)
   if(CloseAtEndOfDay && currentHour >= EndOfDayHour)
      CloseAllORBTrades("fin de dia");

   // Cierre de fin de semana incondicional (Viernes 22:00) para evitar Gaps
   if(TimeDayOfWeek(now) == 5 && currentHour >= 22)
      CloseAllORBTrades("fin de semana");

   // Reset diario del estado
   if(dayKey != g_dayKey)
     {
      g_dayKey = dayKey;
      g_state = 0;
      g_entered = false;
      g_partialClosedCount = 0;
      DeleteORBBox();
     }

   int dayOfWeek = TimeDayOfWeek(now);
   if(!IsTradingDay(dayOfWeek)) return;

   // Ventana ORB del dia anclada a la medianoche del broker
   datetime midnight = now - (now % 86400);
   g_windowStart = midnight + SessionStartHour * 3600 + SessionStartMinute * 60;
   g_windowEnd   = g_windowStart + OrbMinutes * 60;

   // Maquina de estados
   if(g_state == 0)
     {
      if(now < g_windowEnd)
        {
         if(now >= g_windowStart) g_state = 1; // dentro de la ventana, esperamos a que cierre
         return;
        }
      // Ya paso la ventana (EA anadido tarde o primer tick tras la ventana)
      if(!ComputeORB())
        {
         g_state = 3;
         return;
        }
      g_state = 2;
      g_lastBreakoutBar = iTime(Symbol(), BreakoutTF, 0); // la confirmacion empieza en la proxima vela
      DrawORBBox();
     }
   else if(g_state == 1)
     {
      if(now >= g_windowEnd)
        {
         if(!ComputeORB())
           {
            g_state = 3;
            return;
           }
         g_state = 2;
         g_lastBreakoutBar = iTime(Symbol(), BreakoutTF, 0);
         DrawORBBox();
        }
      return;
     }

   if(g_state == 2)
     {
      if(g_entered || GetTradesTodayCount() >= MaxTradesPerDay)
        {
         g_state = 3;
         return;
        }
      if(currentHour >= MaxEntryHour)
        {
         Print("ORB: hora limite de entrada alcanzada (", currentHour, "). Dia terminado.");
         g_state = 3;
         return;
        }
      TryBreakoutEntry();
     }
  }
//+------------------------------------------------------------------+
