//+------------------------------------------------------------------+
//|                                                    SMC_Sell.mq4  |
//|                                         Generated by Antigravity |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property strict
#property show_inputs

input string   Settings = "--- AJUSTES DE RIESGO ---";
input double   RiskPercent = 1.0;         // Riesgo por operacion (%)
input bool     Auto_SL = true;            // SL automatico en el ultimo maximo
input int      Auto_SL_Bars = 15;         // Velas para buscar el maximo
input double   Manual_SL_Pips = 10.0;     // SL manual en pips (si Auto_SL es false)
input double   Target_RR = 2.0;           // Ratio Beneficio/Riesgo (0 = sin TP)
input int      MagicNumber = 0;           // 0 = Operacion manual (independiente del EA)

void OnStart()
  {
   double slPrice = 0;
   double slPips = 0;
   double tpPrice = 0;
   
   if(Auto_SL)
     {
      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, Auto_SL_Bars, 0);
      if(highestIdx < 0) { Print("Error buscando maximo."); return; }
      // SL 1 pip por encima del maximo (10 points)
      slPrice = NormalizeDouble(High[highestIdx] + 10 * Point, Digits);
      slPips = (slPrice - Bid) / (10 * Point);
      
      // Proteccion minima de 2 pips para que no de error
      if(slPips < 2.0) 
        {
         slPips = 2.0;
         slPrice = NormalizeDouble(Bid + slPips * 10 * Point, Digits);
        }
     }
   else
     {
      slPips = Manual_SL_Pips;
      slPrice = NormalizeDouble(Bid + slPips * 10 * Point, Digits);
     }
     
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   if(tickValue == 0) { Print("Error tickValue"); return; }
   
   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double slPoints = slPips * 10.0;
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   
   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;
   lot = MathFloor(lot / lotStep) * lotStep;
   
   if(Target_RR > 0)
     {
      tpPrice = NormalizeDouble(Bid - (slPips * 10 * Point * Target_RR), Digits);
     }
   
   int ticket = OrderSend(Symbol(), OP_SELL, lot, Bid, 3, slPrice, tpPrice, "SMC Manual Sell", MagicNumber, 0, clrRed);
   
   if(ticket > 0)
     {
      Print("SMC Venta ejecutada. Lote: ", DoubleToStr(lot, 2), " SL: ", DoubleToStr(slPips, 1), " pips.");
     }
   else
     {
      Print("Error al ejecutar venta SMC: ", GetLastError());
     }
  }
//+------------------------------------------------------------------+
