//+------------------------------------------------------------------+
//|                                     Asian_V2.70.mq4              |
//|                                      Generated by Dan Master     |
//|                                   Revisado y corregido           |
//| V2.70 = CIERRE VIRTUAL (Virtual Ladder) + FIX DE LOTES.          |
//|  - CIERRE VIRTUAL: reemplaza el lock por retroceso de V2.67 (que  |
//|    armaba ordenes pendientes de salida, chocando con los limites   |
//|    StopLevel/FreezeLevel del broker) por un cierre a MERCADO en    |
//|    memoria. Se sigue el PICO en R; si el precio retrocede hasta    |
//|    el peldaño ya confirmado (VirtualLadderStepRR + confirm), se    |
//|    cierra. Anti-capado: no se arma por tocar nivel; el TP          |
//|    estructural sigue intacto. FIX: parche de riesgo en market      |
//|    fallback (el lotaje ya se calcula con el SL REAL del lado       |
//|    ejecutado, nunca el de la orden Limit opuesta).                 |
//|  - FIX deadlock WaitForBreakout a dos lados: con filtro de         |
//|    tendencia OFF ya no exige romper AMBOS bordes a la vez.         |
//|  - Params: MaxBoxPips 50->70, PendingExpiryHour 11->13,            |
//|    ExternalSLDistancePips 10->12, MinRR 1.5->1.2, MaxSLPips 30-    |
//|    >40. Backtest 7m (EURUSD M5, every tick): +191 USD, PF 1.16,    |
//|    DD 6.72%, win 58.8% (ver Operaciones/Asian_2.63 (6)_03.htm).    |
//| V2.71 = DESCAPADO DEL TP + PAUSA POR RACHAS.                          |
//|  - VirtualLadderStepRR 1.0->2.0 y VirtualLadderBE_RR 1.0->2.0: el    |
//|    cierre virtual protege solo tras 2R, dejando correr al TP          |
//|    estructural (~1.6-2R) sin recortarlo en el retroceso a 1R.          |
//|  - PauseAfterLossStreak (input, 0=off): pausa hoy+manana tras N       |
//|    perdidas consecutivas (limita rachas de SL de 1R).                   |
//| V2.67 = GESTION AVANZADA DE SALIDA (validada ENE-JUL 2026):       |
//|  - MARKET FALLBACK: si la ruptura escapa (Bid > asianHigh +        |
//|    MarketFallbackPips) sin llenar la Limit, entra a MERCADO a      |
//|    favor en vez de quemar el dia con un pendiente que no se        |
//|    activa.                                                         |
//|  - CIERRE PARCIAL 50% a ~1R (UsePartialClose) asegura ganancia    |
//|    sin capar el tramo al TP estructural.                           |
//| V2.66 = ESPERA DE LA RUPTURA ANTES DE COLOCAR LA LIMIT.         |
//| Fiel a Alex: "en el momento que rompe (el techo), alli pone la   |
//| orden limit". El EA espera a que el precio rompa el borde de la  |
//| caja antes de colocar la Sell/Buy Limit (WaitForBreakout=true).  |
//| TP = estructural (extremo opuesto de la caja).                   |
//| V2.65 = DETECCION AUTOMATICA DE LA ZONA DE LIQUIDEZ EXTERNA.    |
//| Busca el SWING (fractal del grafico actual, ej. M5) mas cercano  |
//| a la caja asiatica y coloca la Limit al inicio de la zona,       |
//| descartando las zonas dentro de la caja (como Alex Ruiz marca en |
//| el video la zona purpura). Fallback al offset fijo si no hay     |
//| swing valido. Las zonas se dibujan en purpura.                   |
//| V2.64 = caja asiatica alineada al box del video de Alex Ruiz:    |
//| 01:00-07:00 en grafico UTC+1 = 00:00-06:00 GMT real.             |
//| StartHour=3, EndHour=9 (RefGMTOffset=3). Idem Anti_Asian V2.13.  |
//| V2.63 = FIEL A LA ESTRATEGIA DE ALEX RUIZ (fuente:               |
//| Estrategias/Asian_Breakout/Transcripcion_video.md).              |
//|  - ENTRADA: orden pendiente (Sell/Buy Limit) colocada al INICIO  |
//|    de la ZONA DE LIQUIDEZ EXTERNA al rango asiatico (extension   |
//|    de la caja), en vez de entrada a mercado tras barrido+vela.   |
//|  - TP ESTRUCTURAL: en el EXTREMO OPUESTO de la caja asiatica,    |
//|    no en un ratio fijo (R:R lo define la geometria del cajon).   |
//|  - SL: sobre el nivel de liquidez barrido + distancia externa.   |
//|  - VENTANA: los pendientes caducan a PendingExpiryHour (11:00 =   |
//|    fin killzone Londres). Los llenados de tarde/NY casi no ganan. |
//|  - GESTION PURISTA: BE, lock, trailing y escalones por defecto   |
//|    DESACTIVADOS. Salida = TP estructural o SL.                   |
//|  - Filtro de tendencia macro (EMA 200 H1) opcional, a favor de   |
//|    la corriente estructural.                                     |
//|  - DST: compensacion automatica DETERMINISTICA por calendario     |
//|    europeo (ultimo dom. marzo -> ultimo dom. octubre). La caja    |
//|    cubre la misma franja real de Tokio todo el ano (Tokio no      |
//|    cambia el reloj). V2.64: franja real = 00:00-06:00 GMT (box    |
//|    del video de Alex Ruiz) = 03:00-09:00 verano / 02:00-08:00     |
//|    invierno en hora del broker. Las horas de corte (MaxEntry/     |
//|    EndOfDay) son fijas en hora del broker: Londres sigue el mismo |
//|    DST europeo que el servidor.                                   |
//+------------------------------------------------------------------+
#property copyright "Dan Master"
#property link      ""
#property version   "2.71"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input int      SlippagePoints    = 3;          // Slippage maximo (points)
input bool     UseDynamicLot     = true;       // Activar Lote Dinamico (1%)
input double   RiskPercent       = 1;        // Riesgo por operacion (%)
input bool     InpSendPush       = true;       // Enviar Notificacion al Movil

input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input int      MinBoxPips        = 10;         // Tamano Minimo Caja (pips)
input int      MaxBoxPips        = 70;         // V2.67: Tamano Maximo Caja (pips), ampliado 50->70 (EURUSD M5 excede 50 con frecuencia)
input int      MagicNumber       = 100100;     // Magic Number
input int      StartHour         = 3;          // Hora inicio Asia (03:00 Skilling verano - Se ajustara auto por DST). Caja real 00:00-06:00 GMT (box del video de Alex Ruiz: 01:00-07:00 en grafico UTC+1)
input int      EndHour           = 9;          // Hora fin Asia (09:00 Skilling verano - Se ajustara auto por DST). Invierno: 02:00-08:00
input int      MaxEntryHour      = 23;         // Hora MAXIMA absoluta de la ventana de entrada (cap duro, fija en hora del broker)
   input int      PendingExpiryHour = 13;         // V2.67: caducidad de ordenes pendientes. 11->13 para ampliar la ventana de entrada (con market-fallback y filtro de tendencia ya no pierde tanto)
input int      EndOfDayHour      = 23;         // Hora de corte diario (Time Stop - fija en hora del broker)
input int      RefGMTOffset      = 3;          // V2.63: offset GMT del broker al que estan calibradas las horas de la caja (3 = GMT+3 verano Skilling)

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = true;       // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

// V2.63: TP Fijo por Ratio. false = TP ESTRUCTURAL en el extremo opuesto de la caja (estrategia Alex Ruiz)

input string   AlexRuiz_Settings = "--- ESTRATEGIA ALEX RUIZ (V2.63) ---";
input int      ExternalEntryPips = 2;          // Distancia de la Limit al borde de la caja (pips) - inicio de la zona de liquidez externa
input int      ExternalSLDistancePips = 12;    // V2.67: SL mas lejos (10->12) para dejar el SL MÁS FUERA de la caja y reducir los toques de Judas-swing que causaron los 5 SL
input bool     UseMacroTrendFilter = true;     // V2.63: operar SOLO a favor de la tendencia macro (EMA)
input int      MacroTrendPeriod  = 200;        // Periodo de la EMA de tendencia macro
input int      MacroTrendTF      = PERIOD_H1;  // Timeframe de la EMA de tendencia macro
input double   MinRR             = 1.5;        // V2.70b: R:R minimo exigido (caja/SL). Revertido 1.2->1.5 (valor V2.63) para descartar cajas pequenas de rango (breakout falso) que alimentan la racha de SL Apr-Jun; proyeccion tabla V2.70_2: -529 -> racha 3 (-317), neto +556 -> +666, PF 1.66 -> 2.06. Verificar con Asian_V2.70_3.htm.

input string   LiquidityZone_Settings = "--- ZONA DE LIQUIDEZ EXTERNA (V2.65) ---";
input bool     UseSwingLiquidity     = true;       // V2.65: detectar la zona de liquidez por SWING (fractal del grafico, ej. M5) en vez de offset fijo
input int      LiquidityZonePips     = 3;          // V2.65: semi-ancho de la banda de liquidez alrededor del swing (pips)
input int      MinLiquidityDistPips  = 1;          // V2.65: distancia minima del swing al borde de la caja (pips) - descartar zonas DENTRO o en el borde
input int      MaxLiquidityDistPips  = 60;         // V2.65: distancia maxima del swing al borde de la caja (pips)
input int      SwingLookbackBars     = 500;        // V2.65: velas hacia atras para buscar el swing
input bool     DrawLiquidityZones    = true;       // V2.65: dibujar las zonas de liquidez detectadas (purpura) en el grafico
input bool     WaitForBreakout       = true;       // V2.66: esperar a que el precio ROMPA el borde de la caja antes de colocar la Limit (fiel a Alex)
input bool     UseMarketFallback     = true;       // V2.67: si la ruptura escapa sin que la Limit se llene, entrar a MERCADO a favor (evita quemar el dia con un pendiente que no se activa)
input int      MarketFallbackPips    = 6;          // V2.67: pips mas alla del borde de la caja para considerar la ruptura "escapada" y pasar a mercado

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      SLBufferPips      = 3;          // Pips extra de margen (spread)
input int      MinSLPips         = 5;          // Stop Loss minimo (pips)
input int      MaxSLPips         = 40;         // V2.67: SL maximo permitido (pips). 30->40 permite SL ligeramente mas anchos

// V2.70: BE a 1R y trailing DESACTIVADOS. Sustituidos por el CIERRE VIRTUAL
// (captura ganancia al revertir el precio, sin acabar en cero ni capar el TP)

input string   LockRetrace_Settings = "--- CIERRE VIRTUAL (V2.70) ---";
input bool     UseVirtualLadder     = true;      // V2.70: Cerrar a mercado virtualmente si retrocede, saltando limites
input double VirtualLadderStepRR = 1.0;   // V2.71: Peldaño (en R). Protege solo tras 1R (baseline validado: neto +556.38, PF 1.66, DD 5.53%). El bump a 2.0 fue revertido (regresión +556->+194).
input double VirtualLadderConfirmRR= 0.3;  // V2.70: Margen extra que debe subir sobre el peldaño para armarlo
input double VirtualLadderBE_RR    = 1.0; // V2.70: Break-Even (+0.1R) si el pico llegó a 1R (baseline). El bump a 2.0 fue revertedido (ver StepRR).

input string   Streak_Settings     = "--- CONTROL DE RACHAS ---";
input int      SkipDaysAfterTPWin  = 0;          // V2.62: Dias de espera tras cerrar en TP 1:3 (evita operar contra la tendencia que produjo el 1:3). 0 = desactivado
input int      PauseAfterLossStreak = 0;          // V2.71: Tras N perdidas consecutivas, no operar el resto de hoy ni el día siguiente (0 = desactivado). DEFAULT OFF para proteger el baseline validado +556; proponer =4 como A/B test separado.

input string   News_Settings     = "--- NEWS FILTER (API) ---";
input bool     UseNewsFilter     = true;       // Activar Filtro de Noticias
input int      MinsBeforeNews    = 30;         // Minutos antes de la noticia para pausar
input int      MinsAfterNews     = 30;         // Minutos despues de la noticia para pausar
input bool     FilterHighImpact  = true;       // Filtrar Carpetas Rojas (Alta)
input bool     FilterMedImpact   = false;      // Filtrar Carpetas Naranjas (Media)
input int      MaxTradesPerDay     = 1;          // Maximo de operaciones por dia (Reentradas)
input bool     CloseAtEndOfDay     = false;      // Cerrar todas las operaciones a EndOfDayHour (Time Stop)
input bool     UsePartialClose     = false;      // V2.67: Activar Cierre Parcial Automatico (50% al alcanzar ~1R, asegura ganancia)
input int      PartialClosePips    = 18;         // Pips ganancia para cerrar parcial (cerca de 1R ~ 19 pips tipicos)
input double   PartialClosePercent = 50.0;       // % del lote original a cerrar (ej. 50%)

input string   Mode_Settings     = "--- MODO DE LIQUIDEZ (SMC) ---";
input bool     AutoFindLiquidity = true;       // Buscar Liquidez en AMBOS sentidos (Modo Auto)
input string   ManualBoxName     = "ZonaLiquidez"; // Nombre del Rectangulo Manual (Modo Manual)



//--- Global variables
int lastTradeDay = -1;        // FIX bug3: ahora guarda una clave de fecha completa (YYYYMMDD), no solo el dia del mes
int currentSessionDay = -1;   // FIX bug3: idem
int pauseUntilDay = -1;       // V2.71: clave de fecha hasta la cual se pausa la operativa (racha de perdidas)
double Pip;                   // Multiplicador dinamico para brokers de 4 o 5 digitos

// FIX bug6: registro en memoria de tickets ya parcialmente cerrados,
// como respaldo al chequeo de comentario (que depende del broker)
int g_partialClosedTickets[100];
int g_partialClosedCount = 0;

// V2.70: pico de beneficio (en R) por ticket, para detectar cuando el precio
// retrocede desde su maximo y disparar el Cierre Virtual (si el retroceso cruza
// hacia atras el peldaño ya confirmado).
int g_peakT[100];
double g_peakR[100];
int g_peakCount = 0;

double GetPeakR(int ticket)
  {
   for(int i = 0; i < g_peakCount; i++)
      if(g_peakT[i] == ticket) return g_peakR[i];
   return 0;
  }

void SetPeakR(int ticket, double r)
  {
   for(int i = 0; i < g_peakCount; i++)
      if(g_peakT[i] == ticket)
        {
         g_peakR[i] = r;
         return;
        }
   if(g_peakCount < 100)
     {
      g_peakT[g_peakCount] = ticket;
      g_peakR[g_peakCount] = r;
      g_peakCount++;
     }
  }

void RemovePeakR(int ticket)
  {
   for(int i = 0; i < g_peakCount; i++)
      if(g_peakT[i] == ticket)
        {
         g_peakCount--;
         g_peakT[i] = g_peakT[g_peakCount];
         g_peakR[i] = g_peakR[g_peakCount];
         return;
        }
  }

//+------------------------------------------------------------------+
//| Devuelve una clave de fecha completa AAAAMMDD para comparar dias |
//| de forma segura entre distintos meses/anos (FIX bug3)            |
//+------------------------------------------------------------------+
int GetDateKey(datetime t)
  {
   return TimeYear(t) * 10000 + TimeMonth(t) * 100 + TimeDay(t);
  }

//+------------------------------------------------------------------+
//| AJUSTE AUTOMATICO DE DST (Horario Verano/Invierno)               |
//| TOKIO no cambia el reloj: la caja asiatica debe cubrir la misma  |
//| franja real (hora de Tokio) todo el ano. El broker europeo       |
//| (Skilling) pasa de GMT+3 (verano) a GMT+2 (invierno).            |
//| Se usa el CALENDARIO europeo de DST (ultimo domingo de marzo ->  |
//| ultimo domingo de octubre) porque es DETERMINISTICO y fiable     |
//| tambien en el Strategy Tester, donde TimeGMT() puede devolver    |
//| valores inconsistentes y desplazar la caja a horas absurdas      |
//| (V2.62 uso este metodo y funciono: 34 operaciones en backtest).  |
//| Offset de invierno = RefGMTOffset - 1.                           |
//| Las horas de CORTE (MaxEntryHour, EndOfDayHour) se usan FIJAS    |
//| en hora del broker: LONDRES sigue el mismo calendario de DST     |
//| europeo que el servidor, por lo que su franja real ya es         |
//| constante en hora del broker. Nueva York (referencia NY a las    |
//| 13h) tampoco se ajusta: es una referencia relativa de la tarde.  |
//+------------------------------------------------------------------+
int GetLastSundayDay(int year, int month)
  {
   int lastDay = 31;
   if(month == 4 || month == 6 || month == 9 || month == 11) lastDay = 30;
   if(month == 2) lastDay = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? 29 : 28;
   string dateStr = StringFormat("%04d.%02d.%02d 00:00:00", year, month, lastDay);
   datetime dt = StrToTime(dateStr);
   int dow = TimeDayOfWeek(dt);
   return lastDay - dow;
  }

bool IsBrokerSummerTime(datetime t)
  {
   int year  = TimeYear(t);
   int month = TimeMonth(t);
   int day   = TimeDay(t);
   if(month < 3 || month > 10) return false;
   if(month > 3 && month < 10) return true;
   int lastSunday = GetLastSundayDay(year, month);
   if(month == 3)  return (day >= lastSunday);
   if(month == 10) return (day < lastSunday);
   return false;
  }

int GetBrokerGMTOffset()
  {
   int ref = (RefGMTOffset >= 2 && RefGMTOffset <= 14) ? RefGMTOffset : 3;
   return IsBrokerSummerTime(TimeCurrent()) ? ref : (ref - 1);
  }

// Ajusta una hora de la caja (calibrada a RefGMTOffset) a la hora del broker actual
int AdjustBoxHour(int hour)
  {
   int h = hour + GetBrokerGMTOffset() - RefGMTOffset;
   h = h % 24;
   if(h < 0) h += 24;
   return h;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   if(Period() != PERIOD_M5)
     {
      Print("Aviso: este EA esta disenado para M5. Timeframe actual: ", Period());
     }

   if(UseNewsFilter && !GlobalVariableCheck("SMC_News_High") && !GlobalVariableCheck("SMC_News_Med"))
      Print("ALERTA: News_Fetcher.mq4 no detectada en chart. Filtro de noticias DESACTIVADO.");

   Print("Aviso: Filtro de tendencia macro via EMA ", MacroTrendPeriod, " (TF=", MacroTrendTF, ") en ", (UseMacroTrendFilter ? "MODO ACTIVO" : "MODO INACTIVO"), ".");

   // Log de estado DST al iniciar
   Print("DST Auto: offset actual GMT", GetBrokerGMTOffset(), " (", (IsBrokerSummerTime(TimeCurrent()) ? "verano" : "invierno"),
         "). Caja asiatica en hora del broker: ", AdjustBoxHour(StartHour), ":00-", AdjustBoxHour(EndHour),
         ":00. Ventana de entrada: [", AdjustBoxHour(EndHour), ":00, ", MathMin(PendingExpiryHour, MaxEntryHour),
         ":00). Caducidad pendientes: ", MathMin(PendingExpiryHour, MaxEntryHour), ":00. Horas de corte fijas: MaxEntry ",
         MaxEntryHour, ":00 / EndOfDay ", EndOfDayHour, ":00.");

   // --- Validacion de inputs contradictorios (FIX auditoria V2.5) ---
   if(StartHour >= EndHour)
      Print("ATENCION: StartHour (", StartHour, ") >= EndHour (", EndHour, "). El rango de la sesion asiatica es invalido/vacio. Revisa los inputs.");

   if(EndHour >= MaxEntryHour)
      Print("ATENCION: EndHour (", EndHour, ") >= MaxEntryHour (", MaxEntryHour, "). No habra ventana de entrada disponible. Revisa los inputs.");

   if(EndHour >= MathMin(PendingExpiryHour, MaxEntryHour))
      Print("ATENCION: EndHour (", EndHour, ") >= PendingExpiryHour/MaxEntry (", MathMin(PendingExpiryHour, MaxEntryHour), "). No habra ventana de entrada disponible.");

   if(MinBoxPips >= MaxBoxPips)
      Print("ATENCION: MinBoxPips (", MinBoxPips, ") >= MaxBoxPips (", MaxBoxPips, "). Ninguna caja asiatica pasara el filtro de tamano. Revisa los inputs.");

   if(EndOfDayHour < EndHour)
      Print("ATENCION: EndOfDayHour (", EndOfDayHour, ") es menor que EndHour (", EndHour, "). El cierre de fin de dia ocurriria antes de poder operar.");

   // Rehidratar arrays: cierres parciales ya registrados (por comentario del broker)
   for(int i = 0; i < OrdersTotal(); i++)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            int t = OrderTicket();
            if(StringFind(OrderComment(), "from #") >= 0 && g_partialClosedCount < 100)
              {
               g_partialClosedTickets[g_partialClosedCount] = t;
               g_partialClosedCount++;
              }
           }
        }
     }

   // Solucionar el problema de "Fractional Pips" (Brokers de 3 o 5 digitos vs Clasicos)
   // NOTA: debe calcularse ANTES de cualquier uso de Pip (ej. rehidratacion).
   Pip = (Digits == 3 || Digits == 5) ? 10.0 * Point : 1.0 * Point;

   RefreshRates(); // FIX HIGH-1: Evitar race condition entre bucles durante rehidratacion

   return(INIT_SUCCEEDED);
  }


//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;

   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);

   if(tickValue == 0) return FixedLotSize; // Fallback de seguridad

   // Formula: Lote = Riesgo / (SL_Points * TickValue)
   double slPoints = slDistancePips * (Pip / Point);
   double lot = riskAmount / (slPoints * tickValue);

   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;

   // Normalizar al LotStep (ej: 0.01)
   if(lotStep == 0) lotStep = 0.01;
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }





//+------------------------------------------------------------------+
//| V2.62: true si la ultima operacion cerrada fue un TP 1:3 y cerro |
//| hace <= SkipDaysAfterTPWin dias. Detecta el patron del backtest  |
//| 04: 6 de 18 perdidas siguieron inmediatamente a un 1:3 (tickets  |
//| 2,17,28,29,30,32). La tendencia que produjo el 1:3 suele seguir  |
//| y el Judas Swing (contra-impulso) se lleva por delante.          |
//+------------------------------------------------------------------+
bool JustClosedTPWin()
  {
   datetime lastClose = 0;
   bool   lastWasTP = false;
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_HISTORY)) continue;
      if(OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol()) continue;
      if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue;
      if(OrderCloseTime() <= 0) continue;

      if(OrderCloseTime() > lastClose)
        {
         lastClose = OrderCloseTime();
         double tp = OrderTakeProfit();
         lastWasTP = (tp > 0)
                     && ((OrderType() == OP_BUY  && MathAbs(OrderClosePrice() - tp) < Point * 2)
                      || (OrderType() == OP_SELL && MathAbs(OrderClosePrice() - tp) < Point * 2));
        }
     }
   if(lastClose == 0) return false;
   return lastWasTP && (TimeCurrent() - lastClose) <= SkipDaysAfterTPWin * 86400;
  }

//+------------------------------------------------------------------+
//| V2.71: cuenta cuantas Cierres CONSECUTIVOS (de mas reciente a mas |
//| antiguo) fueron perdedoras. Se deduplican los fragmentos de cierre |
//| parcial (mismo OpenTime/Type) como hace GetTradesTodayCount.     |
//| Se detiene en la primera ganadora. 0 = la ultima no fue perdedora.|
//+------------------------------------------------------------------+
int GetConsecutiveLossCount()
  {
   datetime seenTimes[200];
   int      seenTypes[200];
   ArrayInitialize(seenTimes,  0);
   ArrayInitialize(seenTypes, -1);
   int seenCount = 0;
   int losses = 0;

   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_HISTORY)) continue;
      if(OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol()) continue;
      if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue;
      if(OrderCloseTime() <= 0) continue;

      bool already = false;
      for(int k = 0; k < seenCount; k++)
         if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }
      if(already) continue;
      if(seenCount < 200)
        {
         seenTimes[seenCount]  = OrderOpenTime();
         seenTypes[seenCount]  = OrderType();
         seenCount++;
        }

      if(OrderProfit() < 0)
         losses++;
      else
         break; // primera ganadora rompe la racha
     }
   return losses;
  }









//+------------------------------------------------------------------+
//| Comprueba si un ticket ya fue registrado como parcialmente       |
//| cerrado en esta sesion de la EA (FIX bug6)                       |
//+------------------------------------------------------------------+
bool IsAlreadyPartiallyClosed(int ticket)
  {
   for(int k = 0; k < g_partialClosedCount; k++)
      if(g_partialClosedTickets[k] == ticket) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automatico                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;

   double targetPoints = PartialClosePips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            // FIX bug6: chequeo doble - comentario (depende del broker) + registro propio en memoria
            if(StringFind(OrderComment(), "from #") >= 0) continue;
            if(IsAlreadyPartiallyClosed(OrderTicket())) continue;

            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;

            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;

               // Asegurar que el lote a cerrar es valido y deja algo abierto
               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  int origTicket = OrderTicket();
                  bool res = OrderClose(origTicket, lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, SlippagePoints, clrOrange);
                  if(res)
                    {
                     // FIX bug6: registrar el ticket para no volver a cerrar parcialmente
                     if(g_partialClosedCount < 100)
                       {
                        g_partialClosedTickets[g_partialClosedCount] = origTicket;
                        g_partialClosedCount++;
                       }
                     Print("SMC Cierre Parcial Automatico ejecutado: ", lotToClose, " lotes.");
                     if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Cierre Parcial alcanzado");
                    }
                 }
               }
            }
         }
      }
   }

//+------------------------------------------------------------------+
//| V2.70: CIERRE VIRTUAL (Virtual Ladder).                           |
//| Fiel a Alex: se PRUEBA primero el TP estructural (extremo opuesto  |
//| de la caja) sin capar el tramo. Mientras el precio avanza en       |
//| beneficio se registra el PICO en R alcanzado (g_peak).             |
//| La escalera NO se arma por tocar un nivel: solo cuando el precio   |
//| retrocede hasta el peldaño ya confirmado (lockedR = peldaño mas    |
//| alto que el pico supero en VirtualLadderConfirmRR) se CIERRA a     |
//| MERCADO esa posicion (sin ordenes pendientes de salida, evitando   |
//| los limites StopLevel/FreezeLevel del broker). Si el precio sigue   |
//| y llega al TP estructural, gana el R completo intacto. Si no llego  |
//| a ningun peldaño pero supero VirtualLadderBE_RR, se protege el      |
//| break-even (+0.1R). No modifica el SL original.                    |
//+------------------------------------------------------------------+
void ManageRetraceProfitLock()
  {
   if(!UseVirtualLadder) return;

   // Limpiar picos de posiciones ya cerradas
   for(int i = g_peakCount - 1; i >= 0; i--)
      if(!OrderSelect(g_peakT[i], SELECT_BY_TICKET, MODE_TRADES))
         RemovePeakR(g_peakT[i]);

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderMagicNumber() != MagicNumber || OrderSymbol() != Symbol()) continue;
      int type = OrderType();
      if(type != OP_BUY && type != OP_SELL) continue;

      int ticket = OrderTicket();
      double riskPips = MathAbs(OrderOpenPrice() - OrderStopLoss()) / Pip;
      if(riskPips <= 0) continue;

      double profitPips = 0;
      if(type == OP_BUY)  profitPips = (Bid - OrderOpenPrice()) / Pip;
      else                profitPips = (OrderOpenPrice() - Ask) / Pip;
      double profitR = profitPips / riskPips;

      double peakR = GetPeakR(ticket);
      if(profitR > peakR)
        {
         peakR = profitR;
         SetPeakR(ticket, profitR);
        }

      double lockedR = -1.0;
      
      for(int stepMult = 5; stepMult >= 1; stepMult--)
        {
         double targetLockR = stepMult * VirtualLadderStepRR;
         if(peakR >= targetLockR + VirtualLadderConfirmRR)
           {
            lockedR = targetLockR;
            break;
           }
        }
      
      if(lockedR < 0 && peakR >= VirtualLadderBE_RR) 
        {
         lockedR = 0.1; 
        }
      
      if(lockedR >= 0 && profitR <= lockedR)
        {
         RefreshRates();
         double cp = (type == OP_BUY) ? Bid : Ask;
         if(OrderClose(ticket, OrderLots(), cp, SlippagePoints, clrMagenta))
           {
            Print("SMC V2.70: Cierre Virtual Ejecutado. Retroceso capturado en +", DoubleToStr(lockedR, 1), "R (Pico: ", DoubleToStr(peakR, 2), "R).");
            RemovePeakR(ticket);
           }
         else
           {
            Print("SMC V2.70: Error ejecutando Cierre Virtual (err ", GetLastError(), ").");
           }
        }
     }
  }


//+------------------------------------------------------------------+
//| Limpiar ordenes pendientes al final del dia                      |
//+------------------------------------------------------------------+
void CleanPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT)
              {
               bool del = OrderDelete(OrderTicket());
               if(!del) Print("Error borrando orden: ", GetLastError());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| V2.63: hay alguna orden pendiente nuestra viva?                  |
//+------------------------------------------------------------------+
bool HasPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//| FIX bug3: compara fecha completa (ano/mes/dia), no solo el dia   |
//| FIX bug4: deduplica cierres parciales que generan un ticket extra|
//|           en el historial con el mismo OpenTime/Type que la      |
//|           operacion original                                     |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int todayKey = GetDateKey(TimeCurrent());

   datetime seenTimes[100];
   int seenTypes[100];
   ArrayInitialize(seenTimes, 0);   // FIX: elimina warning "possible use of uninitialized variable"
   ArrayInitialize(seenTypes, -1);  // FIX: idem
   int seenCount = 0;
   int count = 0;

   // --- Operaciones abiertas ---
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }

   // --- Historial (incluye fragmentos de cierres parciales, que se deduplican) ---
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
return false;
   }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {

   ManagePartialClose();
   ManageRetraceProfitLock();

   int currentHour = Hour();
   int currentDay = GetDateKey(TimeCurrent()); // FIX bug3: clave de fecha completa, no solo Day()

   // Ajuste automatico de DST (V2.63): la CAJA asiatica se compensa por el
   // offset real del broker (Tokio no cambia el reloj; se mantiene la misma
   // franja real todo el ano). Las horas de CORTE (MaxEntry/EndOfDay) son
   // FIJAS en hora del broker: Londres sigue el mismo DST europeo que el
   // servidor, por lo que su franja real ya es constante en hora del broker.
   int adjStartHour = AdjustBoxHour(StartHour);
   int adjEndHour   = AdjustBoxHour(EndHour);
   int adjMaxEntryHour = MaxEntryHour;
   int adjExpiryHour = MathMin(PendingExpiryHour, adjMaxEntryHour);
   int adjEndOfDayHour = EndOfDayHour;

   // V2.63: caducidad de los pendientes que no se llenaron en la killzone
   // de Londres (PendingExpiryHour). Tras esa hora no se colocan ni llenan.
   if(currentHour >= adjExpiryHour)
      CleanPendingOrders();

   // Si es el final del dia (input EndOfDayHour), limpiamos ordenes
   // pendientes que no se activaron y, opcionalmente, cerramos activas con reintentos.
   if(currentHour >= adjEndOfDayHour)
     {
      CleanPendingOrders();
      if(CloseAtEndOfDay)
        {
         for(int i = OrdersTotal() - 1; i >= 0; i--)
           {
            if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
              {
               if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
                 {
                  if(OrderType() == OP_BUY || OrderType() == OP_SELL)
                    {
                     int ticketToClose = OrderTicket();
                     double lotsToClose = OrderLots();
                     bool closed = false;

                     // FIX auditoria V2.5 (MEDIUM): reintentos con slippage creciente para evitar
                     // que un spread ampliado (viernes noche, rollover) deje la posicion abierta
                     // todo el fin de semana por un simple "Off quotes".
                     for(int attempt = 1; attempt <= 3 && !closed; attempt++)
                       {
                        RefreshRates();
                        double closePrice = (OrderType() == OP_BUY) ? Bid : Ask;
                        int attemptSlippage = SlippagePoints * attempt;

                        closed = OrderClose(ticketToClose, lotsToClose, closePrice, attemptSlippage, clrOrange);
                        if(closed)
                          {
                           Print("SMC: Cierre de fin de dia (Time Stop) ejecutado para orden #", ticketToClose,
                                 " en intento ", attempt, ".");
                          }
                        else
                          {
                           Print("SMC Error: Fallo Cierre de fin de dia #", ticketToClose,
                                 " (intento ", attempt, "/3). Error: ", GetLastError());
                          }
                       }

                     if(!closed)
                        Print("SMC ALERTA: No se pudo cerrar la orden #", ticketToClose,
                              " tras 3 intentos. Revisar manualmente (riesgo de swap/gap de fin de semana).");
                    }
                 }
              }
           }
        }
     }


   // Limpiamos pendientes si ya llegamos al limite del dia
   if(GetTradesTodayCount() >= MaxTradesPerDay)
     {
      CleanPendingOrders();
     }
   else if(AutoFindLiquidity && HasActiveTrades())
     {
      // En modo auto limpiamos pendientes si hay activas (no piramidar)
      CleanPendingOrders();
     }

   // Solo buscar operaciones despues de cerrar la caja asiatica y antes de la caducidad de Londres
   if(currentHour >= adjEndHour && currentHour < adjExpiryHour)
     {
       // Resetear estado de gestion cada nuevo dia
       if(currentDay != currentSessionDay)
         {
          // Fix Bug: Solo resetear memoria de gestion si no hay operaciones vivas
          if(!HasActiveTrades())
            {
             g_partialClosedCount = 0; // Limpiar memoria de cierres parciales
            }
         for(int i = GlobalVariablesTotal() - 1; i >= 0; i--)
           {
            string gv = GlobalVariableName(i);
            if(StringFind(gv, "SMC_Risk_") == 0)
              {
               int t = StrToInteger(StringSubstr(gv, 9));
               if(!OrderSelect(t, SELECT_BY_TICKET) || OrderCloseTime() > 0)
                 {
                  GlobalVariableDel(gv);
                 }
              }
           }
         currentSessionDay = currentDay;
        }

      // Filtro de dias de la semana
      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      // V2.62: tras cerrar en TP 1:3, esperar SkipDaysAfterTPWin dias.
      // La tendencia que produjo el 1:3 tiende a continuar y la siguiente
      // entrada contra-impulso (Judas Swing) suele ser la siguiente perdida.
      if(SkipDaysAfterTPWin > 0 && JustClosedTPWin())
        {
         if(currentDay != lastTradeDay)
           {
            Print("Dias de descanso tras TP 1:3 (SkipDaysAfterTPWin). Operativa pausada.");
            lastTradeDay = currentDay;
           }
         return;
        }

      // Comprobar si el dia fue ignorado, o alcanzamos limite, o hay trades activos
       if(!isTradingDay)
         {
          if(currentDay != lastTradeDay)
            {
             Print("Dia desactivado en ajustes. Se ignora la operativa hoy.");
             lastTradeDay = currentDay;
            }
          return;
         }

       // V2.71: Pausa tras N perdidas consecutivas (limita rachas como la del reporte).
       // No se opera el resto del dia en curso ni el dia siguiente.
       if(PauseAfterLossStreak > 0)
         {
          if(currentDay <= pauseUntilDay)
            {
             static datetime lastPausePrint = 0;
             if(Time[0] != lastPausePrint)
               {
                Print("V2.71: Dia en pausa por racha de perdidas (hasta ", pauseUntilDay, "). No se opera.");
                lastPausePrint = Time[0];
               }
             return;
            }
          int lossCount = GetConsecutiveLossCount();
          if(lossCount >= PauseAfterLossStreak)
            {
             pauseUntilDay = currentDay + 1; // hoy + manana (clave de fecha YYYYMMDD)
             Print("V2.71: Pausa activada tras ", lossCount, " perdidas consecutivas. Sin operar hoy ni mañana.");
             return;
            }
         }

       if(currentDay == lastTradeDay)
        {
         // V2.67: si ya hay un pendiente de HOY sin rellenar, dejamos pasar para
         // poder convertirlo a mercado si la ruptura escapa (market fallback).
         // En cualquier otro caso (operacion cerrada o pendiente ya limpiado) no se re-entra.
         if(!(UseMarketFallback && HasPendingOrders())) return;
        }
      if(GetTradesTodayCount() >= MaxTradesPerDay) { return; }
      if(HasActiveTrades()) { return; }

      // Calcular inicio y fin de la sesion asiatica para HOY
      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + adjStartHour * 3600;
      datetime timeEnd = currentDayStart + adjEndHour * 3600;

      int shiftStart = iBarShift(Symbol(), Period(), timeStart);
      // Restamos 1 segundo para no incluir la vela que empieza EXACTAMENTE a la hora de fin de la caja
      int shiftEnd = iBarShift(Symbol(), Period(), timeEnd - 1);

      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd)
        {
         return;
        }

      // FIX bug2: +1 para incluir tambien la vela de shiftStart (apertura de la sesion asiatica),
      // que antes quedaba excluida del rango de iHighest/iLowest
      int barsCount = shiftStart - shiftEnd + 1;

      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), Period(), MODE_LOW, barsCount, shiftEnd);

      if(highestIdx < 0 || lowestIdx < 0)
        {
         return;
        }

      double asianHigh = High[highestIdx];
      double asianLow  = Low[lowestIdx];

      // Filtro de Tamano de Caja
      double boxSizePips = (asianHigh - asianLow) / (Pip);

      if(AutoFindLiquidity)
        {
         if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
           {
            lastTradeDay = currentDay;
            Print("Caja asiatica ignorada por tamano: ", DoubleToStr(boxSizePips, 1), " pips.");
            return;
           }

          // MODO AUTOMATICO (V2.65): ORDENES PENDIENTES en la ZONA DE LIQUIDEZ
          // EXTERNA al rango asiatico (estrategia original de Alex Ruiz).
          // Al cerrar la caja se colocan Sell/Buy Limit al INICIO de la zona
          // externa. V2.65: la zona de liquidez se DETECTA automaticamente como
          // el SWING (fractal del grafico actual, ej. M5) mas cercano a la caja,
          // DESCARTANDO las zonas dentro de la caja (MinLiquidityDistPips). La
          // zona detectada se dibuja en purpura (DrawLiquidityZones) y la Limit
          // se coloca en el borde mas cercano a la caja. TP = EXTREMO OPUESTO de
          // la caja. SL = sobre el nivel barrido (ExternalSLDistancePips). Si no
          // hay swing valido, fallback al offset fijo (ExternalEntryPips).
          double slDistPips = ExternalSLDistancePips;
          if(slDistPips < MinSLPips) slDistPips = MinSLPips;

          double extHigh = asianHigh + ExternalEntryPips * Pip; // fallback inicio zona externa superior
          double extLow  = asianLow  - ExternalEntryPips * Pip; // fallback inicio zona externa inferior

          // V2.65: DETECCION DE ZONA DE LIQUIDEZ EXTERNA por SWING (fractal).
          // Tendencia bajista -> swing alto superior (zona SELL). Tendencia
          // alcista -> swing bajo inferior (zona BUY).
          double sellZoneTop = 0, sellZoneBottom = 0;
          double buyZoneTop  = 0, buyZoneBottom  = 0;
          double sellSlDistPips = slDistPips;
          double buySlDistPips  = slDistPips;
          int boxStartShift = shiftStart;

          if(UseSwingLiquidity)
            {
             // Solo buscamos swings formados ANTES del cierre de la caja (estructura previa)
             double swingHigh = FindNearestSwing(true, boxStartShift, asianHigh);
             double swingLow  = FindNearestSwing(false, boxStartShift, asianLow);
             static datetime lastSwingPrint = 0;
             if(swingHigh > 0)
               {
                sellZoneTop    = swingHigh + LiquidityZonePips * Pip;
                sellZoneBottom = swingHigh - LiquidityZonePips * Pip;
                sellSlDistPips = (sellZoneTop + ExternalSLDistancePips * Pip - sellZoneBottom) / Pip;
                if(sellSlDistPips < MinSLPips) sellSlDistPips = MinSLPips;
                if(Time[0] != lastSwingPrint)
                  {
                   Print("SMC V2.66: Zona SELL detectada en swing ", DoubleToStr(swingHigh, Digits),
                         " (banda ", DoubleToStr(sellZoneBottom, Digits), "-", DoubleToStr(sellZoneTop, Digits), ").");
                   lastSwingPrint = Time[0];
                  }
               }
             if(swingLow > 0)
               {
                buyZoneTop    = swingLow + LiquidityZonePips * Pip;
                buyZoneBottom = swingLow - LiquidityZonePips * Pip;
                buySlDistPips = (buyZoneTop - (buyZoneBottom - ExternalSLDistancePips * Pip)) / Pip;
                if(buySlDistPips < MinSLPips) buySlDistPips = MinSLPips;
                if(Time[0] != lastSwingPrint)
                  {
                   Print("SMC V2.66: Zona BUY detectada en swing ", DoubleToStr(swingLow, Digits),
                         " (banda ", DoubleToStr(buyZoneBottom, Digits), "-", DoubleToStr(buyZoneTop, Digits), ").");
                   lastSwingPrint = Time[0];
                  }
               }
            }

          // V2.65: dibujar la(s) zona(s) detectada(s) en purpura (hasta fin de dia)
          if(DrawLiquidityZones)
            {
             datetime zoneStart = timeEnd;
             datetime zoneEnd   = currentDayStart + 24 * 3600;
             if(sellZoneTop > 0) DrawLiquidityZone("Sell", sellZoneTop, sellZoneBottom, zoneStart, zoneEnd);
             if(buyZoneTop > 0)  DrawLiquidityZone("Buy",  buyZoneTop,  buyZoneBottom,  zoneStart, zoneEnd);
            }

          // V2.63: direccion UNICA de tendencia (EMA). Con el filtro activo se
          // coloca UN SOLO lado: al alza solo Buy, a la baja solo Sell. Nunca
          // ambos (antes se colocaban los dos si el precio quedaba pegado a la EMA).
          bool doBuy  = true;
          bool doSell = true;
          if(UseMacroTrendFilter)
            {
             double ema200 = iMA(Symbol(), MacroTrendTF, MacroTrendPeriod, 0, MODE_EMA, PRICE_CLOSE, 0);
             if(Ask > ema200) doSell = false;   // tendencia alcista -> solo compra
             else             doBuy  = false;   // tendencia bajista -> solo venta
            }

          // R:R estructural: caja / SL. Alex Ruiz exige TP lejano (1:2-1:3).
          // Usa la distancia de SL del lado que realmente se colocara (V2.65).
          double rrSlDist = slDistPips;
          if(doSell && doBuy)       rrSlDist = MathMax(sellSlDistPips, buySlDistPips);
          else if(doSell)           rrSlDist = sellSlDistPips;
          else if(doBuy)            rrSlDist = buySlDistPips;
          double structuralRR = boxSizePips / rrSlDist;
          if(structuralRR < MinRR)
            {
             lastTradeDay = currentDay;
             Print("Caja ignorada: R:R estructural ", DoubleToStr(structuralRR, 1), " < MinRR ", MinRR,
                   " (caja ", DoubleToStr(boxSizePips, 1), " pips / SL ", DoubleToStr(rrSlDist, 1), " pips).");
             return;
            }

          // V2.62: tope de distancia de SL (SLs muy amplios = perdidas casi seguras)
          if(rrSlDist > MaxSLPips)
            {
             lastTradeDay = currentDay;
             Print("Caja ignorada: SL de ", DoubleToStr(rrSlDist, 1), " pips > MaxSLPips ", MaxSLPips, " pips.");
             return;
            }

          if((doSell || doBuy) && !HasActiveTrades())
            {
             if(UseNewsFilter && IsNewsTime())
               {
                static datetime lastBlockNews = 0;
                if(Time[0] != lastBlockNews)
                  {
                   Print("SMC V2.66: Colocacion de pendientes bloqueada por filtro de noticias.");
                   lastBlockNews = Time[0];
                  }
               }
             else
               {
                 // V2.66: esperar a que el precio ROMPA el borde de la caja antes
                 // de colocar la Limit (fiel a Alex Ruiz: "en el momento que rompe
                 // el techo, alli pone la orden limit"). El chequeo es por lado y
                 // se hace ANTES de marcar lastTradeDay: si no ha roto, se vuelve
                 // a evaluar el siguiente tick. Con el filtro de tendencia OFF se
                 // colocan dos lados: se espera a que ROMPA CUALQUIERA de los dos
                 // bordes y solo se opera ese lado (el otro queda descartado).
                 // FIX V2.70: antes se exigian ambos bordes a la vez, condicion
                 // imposible (Bid>techo y Ask<suelo simultaneamente), y el dia
                 // se quemaba esperando una ruptura que nunca llegaba.
                 bool sellBreakOK = true;
                 bool buyBreakOK  = true;
                 if(WaitForBreakout)
                   {
                    sellBreakOK = (!doSell || Bid > asianHigh);
                    buyBreakOK  = (!doBuy  || Ask < asianLow);
                    if(doSell && doBuy)
                      {
                       if(!sellBreakOK && !buyBreakOK)
                         {
                          static datetime lastBreakWait2 = 0;
                          if(Time[0] != lastBreakWait2)
                            {
                             Print("SMC V2.70: Esperando ruptura de la caja para colocar la Limit (Bid ", Bid,
                                   " / Techo ", DoubleToStr(asianHigh, Digits), ", Ask ", Ask,
                                   " / Suelo ", DoubleToStr(asianLow, Digits), ").");
                             lastBreakWait2 = Time[0];
                            }
                          return;
                         }
                       if(!sellBreakOK) doSell = false;
                       if(!buyBreakOK)  doBuy  = false;
                      }
                    else if(!sellBreakOK || !buyBreakOK)
                      {
                       static datetime lastBreakWait = 0;
                       if(Time[0] != lastBreakWait)
                         {
                          Print("SMC V2.66: Esperando ruptura del borde de la caja para colocar la Limit (Bid ", Bid,
                                " / Techo ", DoubleToStr(asianHigh, Digits), ", Ask ", Ask,
                                " / Suelo ", DoubleToStr(asianLow, Digits), ").");
                          lastBreakWait = Time[0];
                         }
                       return;
                      }
                   }

                lastTradeDay = currentDay; // UNA colocacion al dia
                double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;

                // V2.67: MARKET FALLBACK. Si la ruptura ya escapo sin que la Limit
                // pudiera llenarse (precio MarketFallbackPips mas alla del borde),
                // entramos a MERCADO a favor en vez de quemar el dia con un pendiente
                // que no se activa. Convierte los dias "Limits borradas a las 11h" en operaciones.
                bool sellRunaway = doSell && (Bid > asianHigh + MarketFallbackPips * Pip);
                bool buyRunaway  = doBuy  && (Ask < asianLow  - MarketFallbackPips * Pip);
                if(UseMarketFallback && (sellRunaway || buyRunaway))
                  {
                   CleanPendingOrders();
                   lastTradeDay = currentDay;
                   // FIX V2.70: la direccion la decide el RUNAWAY real (sellRunaway/
                   // buyRunaway), no el flag doSell/doBuy. Con el filtro de tendencia
                   // OFF ambos flags son true y antes se entraba a SELL aun cuando la
                   // ruptura escapada era hacia ABAJO (buyRunaway), vendiendo contra
                   // el movimiento.
                   if(sellRunaway)
                     {
                      double mSellSL = 0, mSellSl;
                      if(sellZoneTop > 0)
                        {
                         mSellSL = NormalizeDouble(sellZoneTop + ExternalSLDistancePips * Pip, Digits);
                        }
                      else
                        {
                         mSellSL = NormalizeDouble(extHigh + slDistPips * Pip, Digits);
                        }
                      mSellSl = (mSellSL - Bid) / Pip;
                      double mSellLot = CalculateLotSize(mSellSl);
                      if((mSellSL - Bid) >= stopLevel)
                        {
                         int mst = OrderSend(Symbol(), OP_SELL, mSellLot, Bid, SlippagePoints, mSellSL, asianLow, "SMC V2.67 MktFallback SELL", MagicNumber, 0, clrRed);
                         if(mst > 0)
                           {
                            GlobalVariableSet("SMC_Risk_" + IntegerToString(mst), mSellSl);
                            Print("SMC V2.67: Market Fallback SELL a ", Bid, " (TP estructura ", DoubleToStr(asianLow, Digits), ").");
                            if(InpSendPush) SendNotification("Asian V2.67 [" + Symbol() + "]: Market SELL " + DoubleToStr(Bid, Digits) + " (TP " + DoubleToStr(asianLow, Digits) + ")");
                           }
                         else Print("SMC V2.67 Error Market SELL: ", GetLastError());
                        }
                     }
                   else if(buyRunaway)
                     {
                      double mBuySL = 0, mBuySl;
                      if(buyZoneTop > 0)
                        {
                         mBuySL = NormalizeDouble(buyZoneBottom - ExternalSLDistancePips * Pip, Digits);
                        }
                      else
                        {
                         mBuySL = NormalizeDouble(extLow - slDistPips * Pip, Digits);
                        }
                      mBuySl = (Ask - mBuySL) / Pip;
                      double mBuyLot = CalculateLotSize(mBuySl);
                      if((Ask - mBuySL) >= stopLevel)
                        {
                         int mbt = OrderSend(Symbol(), OP_BUY, mBuyLot, Ask, SlippagePoints, mBuySL, asianHigh, "SMC V2.67 MktFallback BUY", MagicNumber, 0, clrBlue);
                         if(mbt > 0)
                           {
                            GlobalVariableSet("SMC_Risk_" + IntegerToString(mbt), mBuySl);
                            Print("SMC V2.67: Market Fallback BUY a ", Ask, " (TP estructura ", DoubleToStr(asianHigh, Digits), ").");
                            if(InpSendPush) SendNotification("Asian V2.67 [" + Symbol() + "]: Market BUY " + DoubleToStr(Bid, Digits) + " (TP " + DoubleToStr(asianHigh, Digits) + ")");
                           }
                         else Print("SMC V2.67 Error Market BUY: ", GetLastError());
                        }
                     }
                   return;
                  }

                // V2.67: si ya hay un pendiente del dia sin rellenar y NO ha escapado,
                // esperamos a que se llene durante la ventana (no duplicamos ni recolocamos).
                if(HasPendingOrders())
                  {
                   lastTradeDay = currentDay;
                   return;
                  }

                if(doSell)
                  {
                   double sellLimit, sellSL, sellTP, sellLot, sellSl;
                   // V2.65: entrada en el borde inferior (mas cercano a la caja) de la zona SELL
                   if(sellZoneTop > 0)
                     {
                      sellLimit = NormalizeDouble(sellZoneBottom, Digits);
                      sellSL    = NormalizeDouble(sellZoneTop + ExternalSLDistancePips * Pip, Digits);
                      sellSl    = sellSlDistPips;
                     }
                   else
                     {
                      sellLimit = NormalizeDouble(extHigh, Digits);
                      sellSL    = NormalizeDouble(extHigh + slDistPips * Pip, Digits);
                      sellSl    = slDistPips;
                     }
                   sellTP = NormalizeDouble(asianLow, Digits);
                   sellLot = CalculateLotSize(sellSl);
                   if(Bid < sellLimit && (sellSL - sellLimit) >= stopLevel)
                     {
                      int ts = OrderSend(Symbol(), OP_SELLLIMIT, sellLot, sellLimit, SlippagePoints, sellSL, sellTP, "SMC V2.66 SellLimit", MagicNumber, 0, clrRed);
                      if(ts > 0)
                        {
                         GlobalVariableSet("SMC_Risk_" + IntegerToString(ts), sellSl);
                         Print("SMC V2.66: Sell Limit colocada a ", sellLimit, ". SL ", DoubleToStr(sellSl, 1), " pips. TP estructura ", sellTP);
                         if(InpSendPush) SendNotification("Asian V2.66 [" + Symbol() + "]: Sell Limit a " + DoubleToStr(sellLimit, Digits) + " (TP " + DoubleToStr(sellTP, Digits) + ")");
                        }
                      else Print("SMC V2.66 Error Sell Limit: ", GetLastError());
                     }
                   else Print("SMC V2.66: Sell Limit abortada (Bid ", Bid, " >= Limit ", sellLimit, " o stopLevel insuficiente).");
                  }

                if(doBuy && !HasPendingOrders())
                  {
                   double buyLimit, buySL, buyTP, buyLot, buySl;
                   // V2.65: entrada en el borde superior (mas cercano a la caja) de la zona BUY
                   if(buyZoneTop > 0)
                     {
                      buyLimit = NormalizeDouble(buyZoneTop, Digits);
                      buySL    = NormalizeDouble(buyZoneBottom - ExternalSLDistancePips * Pip, Digits);
                      buySl    = buySlDistPips;
                     }
                   else
                     {
                      buyLimit = NormalizeDouble(extLow, Digits);
                      buySL    = NormalizeDouble(extLow - slDistPips * Pip, Digits);
                      buySl    = slDistPips;
                     }
                   buyTP = NormalizeDouble(asianHigh, Digits);
                   buyLot = CalculateLotSize(buySl);
                   if(Ask > buyLimit && (buyLimit - buySL) >= stopLevel)
                     {
                      int tb = OrderSend(Symbol(), OP_BUYLIMIT, buyLot, buyLimit, SlippagePoints, buySL, buyTP, "SMC V2.66 BuyLimit", MagicNumber, 0, clrBlue);
                      if(tb > 0)
                        {
                         GlobalVariableSet("SMC_Risk_" + IntegerToString(tb), buySl);
                         Print("SMC V2.66: Buy Limit colocada a ", buyLimit, ". SL ", DoubleToStr(buySl, 1), " pips. TP estructura ", buyTP);
                         if(InpSendPush) SendNotification("Asian V2.66 [" + Symbol() + "]: Buy Limit a " + DoubleToStr(buyLimit, Digits) + " (TP " + DoubleToStr(buyTP, Digits) + ")");
                        }
                      else Print("SMC V2.66 Error Buy Limit: ", GetLastError());
                     }
                   else Print("SMC V2.66: Buy Limit abortada (Ask ", Ask, " <= Limit ", buyLimit, " o stopLevel insuficiente).");
                  }
               }
            }
         }
       else
        {
         // MODO MANUAL (Buscar el rectangulo del usuario)
         int objIdx = ObjectFind(0, ManualBoxName);
         if(objIdx >= 0)
           {
            double price1 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE1);
            double price2 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE2);

            double boxTop = MathMax(price1, price2);
            double boxBottom = MathMin(price1, price2);

            static bool boxDetected = false;
            if(!boxDetected)
              {
               Print("SMC: Caja '", ManualBoxName, "' detectada visualmente. Base: ", boxBottom, " Techo: ", boxTop, " (AsianHigh:", asianHigh, " AsianLow:", asianLow, ")");
               boxDetected = true;
              }

            double limitPrice = 0, stopLoss = 0, takeProfit = 0, slPips = 0;
            int orderType = -1;

            // Si la caja manual esta por encima de la asiatica, queremos VENDER
            if(boxBottom >= asianHigh)
              {
               limitPrice = boxBottom;
               stopLoss = boxTop + SLBufferPips * Pip;
               if((stopLoss - limitPrice) / (Pip) < MinSLPips) stopLoss = limitPrice + MinSLPips * Pip;
               slPips = (stopLoss - limitPrice) / (Pip);
               takeProfit = asianLow;
               orderType = OP_SELLLIMIT;
              }
            // Si la caja manual esta por debajo de la asiatica, queremos COMPRAR
            else if(boxTop <= asianLow)
              {
               limitPrice = boxTop;
               stopLoss = boxBottom - SLBufferPips * Pip;
               if((limitPrice - stopLoss) / (Pip) < MinSLPips) stopLoss = limitPrice - MinSLPips * Pip;
               slPips = (limitPrice - stopLoss) / (Pip);
               takeProfit = asianHigh;
               orderType = OP_BUYLIMIT;
              }

            if(orderType >= 0 && limitPrice > 0)
              {
               limitPrice = NormalizeDouble(limitPrice, Digits);
               stopLoss = NormalizeDouble(stopLoss, Digits);
               takeProfit = NormalizeDouble(takeProfit, Digits);

               bool validLimit = false;
               if(orderType == OP_BUYLIMIT && Ask > limitPrice) validLimit = true;
               if(orderType == OP_SELLLIMIT && Bid < limitPrice) validLimit = true;

               if(validLimit)
                 {
                  if(UseNewsFilter && IsNewsTime())
                    {
                     static datetime lastPrintNews = 0;
                     if(Time[0] != lastPrintNews)
                       {
                        Print("SMC Entrada Manual Bloqueada: Filtro de Noticias activo.");
                        lastPrintNews = Time[0];
                       }
                    }
                  else
                    {
                     double lot = CalculateLotSize(slPips);
                     int ticket = OrderSend(Symbol(), orderType, lot, limitPrice, SlippagePoints, stopLoss, takeProfit, "SMC Limit Manual", MagicNumber, 0, (orderType == OP_BUYLIMIT) ? clrBlue : clrRed);
                     if(ticket > 0)
                       {
                        lastTradeDay = currentDay;
                        boxDetected = false; // Reset state // Necesario para el modo BE a 1:1 (se activa cuando se llene la limit)
                        GlobalVariableSet("SMC_Risk_" + IntegerToString(ticket), slPips);
                        Print("Orden Limit SMC Manual colocada exitosamente. Lote: ", lot, " TP: ", takeProfit);
                        if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Orden Limit colocada a " + DoubleToStr(limitPrice, Digits));
                        // Ocultar el rectangulo para no duplicar manana
                        ObjectDelete(0, ManualBoxName);
                       }
                     else
                       {
                        Print("Error al poner la Orden Limit Manual: ", GetLastError());
                       }
                    }
                 }
               else
                 {
                  static datetime lastPrint = 0;
                  if(Time[0] != lastPrint)
                    {
                     Print("SMC Esperando... Precio actual no permite colocar Limit. (Bid: ", Bid, " Limit: ", limitPrice, ")");
                     lastPrint = Time[0];
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| Dibuja una linea vertical en el grafico indicando la noticia     |
//+------------------------------------------------------------------+
void DrawNewsLine(string name, color clr, double minsToNews)
  {
   if(minsToNews == EMPTY_VALUE || minsToNews == 0) return;
   
   datetime newsTime = TimeCurrent() + (int)(minsToNews * 60);
   
   if(ObjectFind(name) < 0)
     {
      ObjectCreate(0, name, OBJ_VLINE, 0, newsTime, 0);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_DASHDOT);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
     }
   else
     {
      ObjectSetInteger(0, name, OBJPROP_TIME, newsTime);
     }
  }

//+------------------------------------------------------------------+
//| News API Integration (Global Variables from News_Fetcher)        |
//+------------------------------------------------------------------+
bool IsNewsTime()
  {
   bool isNews = false;
   
   static datetime lastNewsCheck = 0;
   bool shouldUpdateLines = (TimeCurrent() - lastNewsCheck >= 60);
   if(shouldUpdateLines) lastNewsCheck = TimeCurrent();
   
   if(FilterHighImpact)
     {
      if(GlobalVariableCheck("SMC_News_High"))
        {
         double minsHigh = GlobalVariableGet("SMC_News_High"); 
         if(shouldUpdateLines) DrawNewsLine("SMC_News_High", clrRed, minsHigh);
         if(minsHigh <= MinsBeforeNews && minsHigh >= -MinsAfterNews) isNews = true;
        }
     }
     
   if(FilterMedImpact)
     {
      if(GlobalVariableCheck("SMC_News_Med"))
        {
         double minsMed = GlobalVariableGet("SMC_News_Med"); 
         if(shouldUpdateLines) DrawNewsLine("SMC_News_Med", clrOrange, minsMed);
         if(minsMed <= MinsBeforeNews && minsMed >= -MinsAfterNews) isNews = true;
        }
     }

    return isNews;
   }

//+------------------------------------------------------------------+
//| V2.65: encuentra el SWING (fractal) mas cercano FUERA de la caja.|
//| findHigh=true -> swing alto por ENCIMA de la caja (zona SELL).   |
//| findHigh=false -> swing bajo por DEBAJO de la caja (zona BUY).   |
//| Busca desde el inicio de la caja hacia atras (estructura previa) |
//| y devuelve el nivel del swing, o 0 si no hay ninguno valido.     |
//| Descarta swings DENTRO de la caja o a < MinLiquidityDistPips.    |
//+------------------------------------------------------------------+
double FindNearestSwing(bool findHigh, int fromShift, double boxEdge)
  {
   double bestLevel = 0;
   double bestDist  = 1e15;
   int startShift = MathMax(fromShift + 2, 2);
   int endShift   = MathMin(startShift + SwingLookbackBars, Bars - 3);

   for(int i = startShift; i <= endShift; i++)
     {
      bool isSwing = false;
      double level = 0;

      if(findHigh)
        {
         if(High[i] > High[i+1] && High[i] > High[i+2] &&
            High[i] >= High[i-1] && High[i] >= High[i-2])
           {
            isSwing = true;
            level = High[i];
           }
        }
      else
        {
         if(Low[i] < Low[i+1] && Low[i] < Low[i+2] &&
            Low[i] <= Low[i-1] && Low[i] <= Low[i-2])
           {
            isSwing = true;
            level = Low[i];
           }
        }

      if(!isSwing) continue;

      double dist = findHigh ? (level - boxEdge) : (boxEdge - level);
      // La banda completa de LiquidityZonePips debe quedar FUERA de la caja
      if(dist < (LiquidityZonePips + MinLiquidityDistPips) * Pip) continue;
      if(dist > MaxLiquidityDistPips * Pip) continue;        // zona demasiado lejos
      if(dist < bestDist)
        {
         bestDist  = dist;
         bestLevel = level;
        }
     }

   return bestLevel;
  }

//+------------------------------------------------------------------+
//| V2.65: dibuja la zona de liquidez detectada (rectangulo purpura) |
//+------------------------------------------------------------------+
void DrawLiquidityZone(string side, double zoneTop, double zoneBottom, datetime t1, datetime t2)
  {
   string name = "SMC_LQZone_" + side;
   if(ObjectFind(0, name) < 0)
     {
      ObjectCreate(0, name, OBJ_RECTANGLE, 0, t1, zoneTop, t2, zoneBottom);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clrMediumOrchid);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_SOLID);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 1);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
      ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
     }
   else
     {
      ObjectSetDouble(0, name, OBJPROP_PRICE1, zoneTop);
      ObjectSetDouble(0, name, OBJPROP_PRICE2, zoneBottom);
      ObjectSetInteger(0, name, OBJPROP_TIME1, t1);
      ObjectSetInteger(0, name, OBJPROP_TIME2, t2);
     }
  }
//+------------------------------------------------------------------+
