//+------------------------------------------------------------------+
//|                                       AsianBreakout_100D_v5.mq4 |
//|                                      Generated by Antigravity |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "5.00"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input bool     UseDynamicLot     = true;       // Activar Lote Dinámico (1%)
input double   RiskPercent       = 1.0;        // Riesgo por operación (%)
input double   MinRewardRiskRatio= 2.0;        // Ratio R:R Mínimo Teórico
input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input bool     WaitCandleClose   = true;       // Esperar Cierre de Vela M5
input int      MinBoxPips        = 10;         // Tamaño Mínimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamaño Máximo Caja (pips)
input int      MagicNumber       = 100100;     // Magic Number
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling)
input int      EndHour           = 8;          // Hora fin Asia (08:00 Skilling)

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = true;       // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = false;      // Activar Trailing Stop (False = Purista)
input int      TrailingPips      = 15;         // Distancia del Trailing (pips)

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      SLBufferPips      = 3;          // Pips extra de margen (spread)
input int      MinSLPips         = 5;          // Stop Loss mínimo (pips)

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = false;      // Activar Auto Break-Even (False = Purista)
input int      BreakEvenActivation = 10;         // Pips ganancia para activar BE
input int      BreakEvenExtraPips  = 1;          // Pips extra sobre SL para asegurar comisiones

input int      MaxTradesPerDay     = 2;          // Maximo de operaciones por dia (Reentradas)
input bool     UsePartialClose     = false;      // Activar Cierre Parcial Automático (False = Purista)
input int      PartialClosePips    = 10;         // Pips ganancia para cerrar parcial
input double   PartialClosePercent = 50.0;       // % del lote original a cerrar (ej. 50%)

input string   Mode_Settings     = "--- MODO DE LIQUIDEZ ---";
input bool     AutoFindLiquidity = false;      // Buscar Liquidez en AMBOS sentidos (Backtest)
input int      HoursToLookBack   = 12;         // Horas previas a la caja (Modo Auto)
input string   ManualBoxName     = "ZonaLiquidez"; // Nombre del Rectángulo Manual (Modo Manual)

input string   Trend_Settings    = "--- FILTRO DE TENDENCIA ---";
input bool     UseTrendFilter    = true;       // Activar Filtro EMA (Modo Auto)
input ENUM_TIMEFRAMES TrendTF    = PERIOD_H1;  // Temporalidad de Tendencia
input int      FastEMAPeriod     = 50;         // Periodo EMA Rapida
input int      SlowEMAPeriod     = 200;        // Periodo EMA Lenta

//--- Global variables
int lastTradeDay = -1;
int currentSessionDay = -1;
bool sweptHigh = false;
bool sweptLow = false;
double peakHigh = 0;
double troughLow = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;
   
   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   
   if(tickValue == 0) return FixedLotSize; // Fallback de seguridad
   
   // Formula: Lote = Riesgo / (SL_Points * TickValue)
   double slPoints = slDistancePips * 10.0;
   double lot = riskAmount / (slPoints * tickValue);
   
   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
   
   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;
   
   // Normalizar al LotStep (ej: 0.01)
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;
   
   double trailingPoints = TrailingPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2) // Solo si mejora el SL en más de 2 puntos
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0) // Solo si baja el SL
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;
   
   double activationPoints = BreakEvenActivation * 10.0 * Point;
   double extraPoints = BreakEvenExtraPips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid) // Solo subir SL si mejora y no choca con el Bid
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) // Solo bajar SL
                    {
                     int mod = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automático                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;
   
   double targetPoints = PartialClosePips * 10.0 * Point;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            // Evitar múltiples cierres parciales de la misma orden revisando el comentario
            if(StringFind(OrderComment(), "from #") >= 0) continue; 
            
            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;
            
            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
               
               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;
               
               // Asegurar que el lote a cerrar es válido y deja algo abierto
               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  bool res = OrderClose(OrderTicket(), lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, 3, clrOrange);
                  if(res) Print("SMC Cierre Parcial Automático ejecutado: ", lotToClose, " lotes.");
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   if(!UseTrendFilter) return true;
   
   double fastEMA = iMA(Symbol(), TrendTF, FastEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double slowEMA = iMA(Symbol(), TrendTF, SlowEMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
   double currentPrice = iClose(Symbol(), TrendTF, 1); // Cierre de la vela anterior H1
   
   if(isBuy)
     {
      // Tendencia alcista: EMA rapida arriba de la lenta, precio arriba de lenta
      if(fastEMA > slowEMA && currentPrice > slowEMA) return true;
     }
   else
     {
      // Tendencia bajista: EMA rapida abajo de la lenta, precio abajo de lenta
      if(fastEMA < slowEMA && currentPrice < slowEMA) return true;
     }
     
   return false;
  }

//+------------------------------------------------------------------+
//| Limpiar ordenes pendientes al final del día                      |
//+------------------------------------------------------------------+
void CleanPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT)
              {
               bool del = OrderDelete(OrderTicket());
               if(!del) Print("Error borrando orden: ", GetLastError());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int currentDay = Day();
   int count = 0;
   
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay)
              {
               count++;
              }
           }
        }
     }
     
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && TimeDay(OrderOpenTime()) == currentDay)
              {
               count++;
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Llamada al gestor de Trailing Stop continuo
   ManageTrailingStop();
   ManageAutoBreakEven();
   ManagePartialClose();
   
   int currentHour = Hour();
   int currentDay = Day();
   
   // Si es el final del día (ej. hora 23), limpiamos ordenes pendientes que no se activaron
   if(currentHour >= 23)
     {
      CleanPendingOrders();
     }

   // Limpiamos pendientes si ya llegamos al limite del dia o hay activas
   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      CleanPendingOrders();
     }

   // Solo buscar operaciones despues de cerrar la caja asiatica
   if(currentHour >= EndHour && currentHour < 23)
     {
      // Resetear variables de barrido cada nuevo día
      if(currentDay != currentSessionDay)
        {
         sweptHigh = false;
         sweptLow = false;
         peakHigh = 0;
         troughLow = 0;
         currentSessionDay = currentDay;
        }

      // Comprobar si el dia fue ignorado, o alcanzamos limite, o hay trades activos
      if(currentDay == lastTradeDay || GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades()) return;

      // Calcular inicio y fin de la sesion asiatica para HOY
      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + StartHour * 3600;
      datetime timeEnd = currentDayStart + EndHour * 3600;
      
      int shiftStart = iBarShift(Symbol(), Period(), timeStart);
      int shiftEnd = iBarShift(Symbol(), Period(), timeEnd);
      
      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd) return;
      
      int barsCount = shiftStart - shiftEnd;
      
      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), Period(), MODE_LOW, barsCount, shiftEnd);
      
      if(highestIdx < 0 || lowestIdx < 0) return;
      
      double asianHigh = High[highestIdx];
      double asianLow  = Low[lowestIdx];
      
      // Filtro de Tamano de Caja
      double boxSizePips = (asianHigh - asianLow) / (10 * Point);
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         Print("Caja asiatica ignorada por tamano: ", DoubleToStr(boxSizePips, 1), " pips.");
         return;
        }
      
      if(AutoFindLiquidity)
        {
         // MODO AUTOMATICO: Vigilar Ruptura y Reversión (Asian Sweep)
         // 1. Detectar si el precio rompe el techo o el suelo
         if(Bid > asianHigh || High[0] > asianHigh)
           {
            sweptHigh = true;
            peakHigh = MathMax(peakHigh, High[0]);
           }
         if(Ask < asianLow || Low[0] < asianLow)
           {
            sweptLow = true;
            if(troughLow == 0) troughLow = Low[0];
            else troughLow = MathMin(troughLow, Low[0]);
           }
         
         // 2. Operar la reversión
         bool triggerSell = false;
         bool triggerBuy = false;
         
         static datetime lastBarTime = 0;
         bool isNewBar = false;
         if(Time[0] != lastBarTime)
           {
            isNewBar = true;
            lastBarTime = Time[0];
           }
           
         if(WaitCandleClose)
           {
            if(isNewBar)
              {
               if(sweptHigh && Close[1] < asianHigh) triggerSell = true;
               if(sweptLow && Close[1] > asianLow) triggerBuy = true;
              }
           }
         else
           {
            if(sweptHigh && Bid < asianHigh) triggerSell = true;
            if(sweptLow && Ask > asianLow) triggerBuy = true;
           }

         if(triggerSell)
           {
            if(!IsTrendAligned(false))
              {
               Print("Venta SMC Bloqueada: Tendencia macro alcista detectada.");
               triggerSell = false; // Bloquear
              }
            else
              {
               // Reversión bajista -> VENDER
               double baseSL = peakHigh + SLBufferPips * 10 * Point;
               double slPips = (baseSL - Bid) / (10 * Point);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Bid + slPips * 10 * Point;
                 }
               double sl = NormalizeDouble(baseSL, Digits);
               
               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opción B: Sin límite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Bid - (slPips * 10 * Point * FixedRiskReward), Digits);
                    }
                  
                  if(Bid < sl)
                    {
                     int t = OrderSend(Symbol(), OP_SELL, calculatedLot, Bid, 3, sl, actualTP, "SMC Reversion Sell", MagicNumber, 0, clrRed);
                     if(t > 0)
                       {
                        Print("Venta SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        // lastTradeDay = currentDay; removido para permitir reentradas
                       }
                     else Print("Error abriendo Venta SMC: ", GetLastError());
                    }
                 }
              }
           }
           
         if(triggerBuy)
           {
            if(!IsTrendAligned(true))
              {
               Print("Compra SMC Bloqueada: Tendencia macro bajista detectada.");
               triggerBuy = false; // Bloquear
              }
            else
              {
               // Reversión alcista -> COMPRAR
               double baseSL = troughLow - SLBufferPips * 10 * Point;
               double slPips = (Ask - baseSL) / (10 * Point);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Ask - slPips * 10 * Point;
                 }
               double sl = NormalizeDouble(baseSL, Digits);
               
               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opción B: Sin límite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Ask + (slPips * 10 * Point * FixedRiskReward), Digits);
                    }
                  
                  if(Ask > sl)
                    {
                     int t = OrderSend(Symbol(), OP_BUY, calculatedLot, Ask, 3, sl, actualTP, "SMC Reversion Buy", MagicNumber, 0, clrBlue);
                     if(t > 0)
                       {
                        Print("Compra SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        // lastTradeDay = currentDay; removido para permitir reentradas
                       }
                     else Print("Error abriendo Compra SMC: ", GetLastError());
                    }
                 }
              }
           }
        }
      else
        {
         // MODO MANUAL (Buscar el rectangulo del usuario)
         if(ObjectFind(0, ManualBoxName) >= 0)
           {
            double price1 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE1);
            double price2 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE2);
            
            double boxTop = MathMax(price1, price2);
            double boxBottom = MathMin(price1, price2);
            
            static bool boxDetected = false;
            if(!boxDetected)
              {
               Print("SMC: Caja '", ManualBoxName, "' detectada visualmente. Base: ", boxBottom, " Techo: ", boxTop);
               boxDetected = true;
              }
            
            double limitPrice = 0, stopLoss = 0, takeProfit = 0, slPips = 0;
            int orderType = -1;
            
            // Si la caja manual esta por encima de la asiatica, queremos VENDER
            if(boxBottom >= asianHigh)
              {
               limitPrice = boxBottom; 
               stopLoss = boxTop + SLBufferPips * 10 * Point; 
               if((stopLoss - limitPrice) / (10 * Point) < MinSLPips) stopLoss = limitPrice + MinSLPips * 10 * Point;
               slPips = (stopLoss - limitPrice) / (10 * Point);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice - (slPips * 10 * Point * FixedRiskReward), Digits);
               else takeProfit = asianLow;  
               orderType = OP_SELLLIMIT;
              }
            // Si la caja manual esta por debajo de la asiatica, queremos COMPRAR
            else if(boxTop <= asianLow)
              {
               limitPrice = boxTop; 
               stopLoss = boxBottom - SLBufferPips * 10 * Point; 
               if((limitPrice - stopLoss) / (10 * Point) < MinSLPips) stopLoss = limitPrice - MinSLPips * 10 * Point;
               slPips = (limitPrice - stopLoss) / (10 * Point);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice + (slPips * 10 * Point * FixedRiskReward), Digits);
               else takeProfit = asianHigh; 
               orderType = OP_BUYLIMIT;
              }
              
            if(orderType >= 0 && limitPrice > 0)
              {
               limitPrice = NormalizeDouble(limitPrice, Digits);
               stopLoss = NormalizeDouble(stopLoss, Digits);
               takeProfit = NormalizeDouble(takeProfit, Digits);
               
               bool validLimit = false;
               if(orderType == OP_BUYLIMIT && Ask > limitPrice) validLimit = true;
               if(orderType == OP_SELLLIMIT && Bid < limitPrice) validLimit = true;
               
               if(validLimit)
                 {
                  double lot = CalculateLotSize(slPips);
                  int ticket = OrderSend(Symbol(), orderType, lot, limitPrice, 3, stopLoss, takeProfit, "SMC Limit Manual", MagicNumber, 0, (orderType == OP_BUYLIMIT) ? clrBlue : clrRed);
                  if(ticket > 0)
                    {
                     lastTradeDay = currentDay;
                     boxDetected = false; // Reset state
                     Print("Orden Limit SMC Manual colocada exitosamente. Lote: ", lot, " TP: ", takeProfit);
                     // Ocultar el rectángulo para no duplicar mañana
                     ObjectDelete(0, ManualBoxName);
                    }
                  else
                    {
                     Print("Error al poner la Orden Limit Manual: ", GetLastError());
                    }
                 }
               else
                 {
                  static datetime lastPrint = 0;
                  if(Time[0] != lastPrint)
                    {
                     Print("SMC Esperando... Precio actual no permite colocar Limit. (Bid: ", Bid, " Limit: ", limitPrice, ")");
                     lastPrint = Time[0];
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
