//+------------------------------------------------------------------+
//|                                     Asian_V2.61.mq4              |
//|                                      Generated by Antigravity     |
//|                                   Revisado y corregido           |
//| V2.61 = V2.6 + Fix A1 (EscalonadoRR2 = 1.5) + Fix A2 (lock      |
//| condicional por retroceso de 0.5R desde el pico).                |
//| - Estado 1 (1:1): recoloca SL a BE + buffer.                     |
//| - Estado 2 (EscalonadoRR2): recoloca SL a +1R SOLO si el precio  |
//|   retrocede EscalonadoPullbackPips (0.5R por defecto) desde su   |
//|   pico. Si la tendencia continua hacia TP 1:3, no se toca el SL.|
//|   Esto elimina el corte prematuro de ganadoras (Categoria B)     |
//|   manteniendo el rescate de perdedoras (Categoria A).            |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "2.61"
#property strict

//--- Input parameters
input string   General_Settings  = "--- AJUSTES GENERALES ---";
input int      SlippagePoints    = 3;          // Slippage maximo (points)
#define SLIPPAGE SlippagePoints
input bool     UseDynamicLot     = true;       // Activar Lote Dinamico (1%)
input double   RiskPercent       = 1;        // Riesgo por operacion (%)
input bool     InpSendPush       = true;       // Enviar Notificacion al Movil

input double   FixedLotSize      = 0.10;       // Lote Fijo (si Auto es false)
input int      MinBoxPips        = 10;         // Tamano Minimo Caja (pips)
input int      MaxBoxPips        = 50;         // Tamano Maximo Caja (pips)
input int      MagicNumber       = 100100;     // Magic Number
input int      StartHour         = 2;          // Hora inicio Asia (02:00 Skilling - Se ajustara auto por DST)
input int      EndHour           = 8;          // Hora fin Asia (08:00 Skilling - Se ajustara auto por DST)
input int      MaxEntryHour      = 23;         // Hora maxima para cazar ruptura (Fin Londres - Se ajustara auto por DST)
input int      EndOfDayHour      = 23;         // Hora de corte diario (Time Stop - Se ajustara auto por DST)

input string   Days_Settings     = "--- FILTRO DE DIAS ---";
input bool     TradeMonday       = true;       // Operar Lunes
input bool     TradeTuesday      = true;       // Operar Martes
input bool     TradeWednesday    = true;       // Operar Miercoles
input bool     TradeThursday     = true;       // Operar Jueves
input bool     TradeFriday       = false;      // Operar Viernes

input string   Target_Settings   = "--- OBJETIVOS DE BENEFICIO ---";
input double   FixedRiskReward   = 3.0;        // Ratio R:R Fijo (ej. 3.0 para 1:3)
input bool     UseFixedRR        = true;       // Activar TP Fijo por Ratio (Sobrescribe Trailing)

input string   Trailing_Settings = "--- TRAILING STOP ---";
input bool     UseTrailingStop   = false;      // Activar Trailing Stop (False = Purista)
input int      TrailingPips      = 0;          // Distancia del Trailing (pips)

input string   StopLoss_Settings = "--- AJUSTES DE STOP LOSS ---";
input int      SLBufferPips      = 3;          // Pips extra de margen (spread)
input int      MinSLPips         = 5;          // Stop Loss minimo (pips)

input string   Management_Settings = "--- GESTION DE OPERACIONES ---";
input bool     UseAutoBreakEven    = false;      // Activar Auto Break-Even por PIPS FIJOS (ignorado si UseBreakEvenAt1R=true)
input int      BreakEvenActivation = 10;         // Pips ganancia para activar BE (solo si UseBreakEvenAt1R=false)
input int      BreakEvenExtraPips  = 1;          // Pips extra sobre SL para asegurar comisiones
input bool     UseBreakEvenAt1R    = false;      // Mover a BE al alcanzar 1:1 (R) y activar trailing por pips despues

input string   Escalonado_Settings = "--- TP ESCALONADO ---";
input bool     UseEscalonadoTP     = true;       // Activar TP Escalonado a 1:1 (BE en 1:1, deja correr al TP 1:3)
input double   EscalonadoRR1       = 1.0;        // Ratio para activar Break-Even (default 1.0)
input double   EscalonadoRR2       = 1.5;        // V2.61 FIX A1: 1.5R (era 2.0R en V2.6). Con A2 la activation ya no dispara por toque sino por retroceso de 0.5R desde el pico.
input bool     EscalonadoMoveSLto1R = true;      // V2.61 FIX A2: activado por defecto. El lock a +1R solo se ejecuta cuando el precio RETROCEDE 0.5R desde su pico tras haber tocado EscalonadoRR2.
input double   EscalonadoPullbackPips = 0.5;     // V2.61 FIX A2: retroceso minimo (en unidades de R) desde el pico, necesario para activar el lock a +1R. Default 0.5R.

input string   News_Settings     = "--- NEWS FILTER (API) ---";
input bool     UseNewsFilter     = true;       // Activar Filtro de Noticias
input int      MinsBeforeNews    = 30;         // Minutos antes de la noticia para pausar
input int      MinsAfterNews     = 30;         // Minutos despues de la noticia para pausar
input bool     FilterHighImpact  = true;       // Filtrar Carpetas Rojas (Alta)
input bool     FilterMedImpact   = false;      // Filtrar Carpetas Naranjas (Media)
input int      MaxTradesPerDay     = 1;          // Maximo de operaciones por dia (Reentradas)
input bool     CloseAtEndOfDay     = false;      // Cerrar todas las operaciones a EndOfDayHour (Time Stop)
input bool     UsePartialClose     = false;      // Activar Cierre Parcial Automatico (False = Purista)
input int      PartialClosePips    = 15;         // Pips ganancia para cerrar parcial
input double   PartialClosePercent = 50.0;       // % del lote original a cerrar (ej. 50%)

input string   Mode_Settings     = "--- MODO DE LIQUIDEZ (SMC) ---";
input bool     AutoFindLiquidity = true;       // Buscar Liquidez en AMBOS sentidos (Modo Auto)
input int      MinBreakoutBodyPips = 2;        // Min pips cuerpo vela de ruptura (Vela Decidida)
input double   MinReversalCandlePips = 8.0;    // Min pips TOTALES de la vela de entrada (Filtro Ruido NY)
input double   MinDojiSizePips   = 2.0;        // Min pips TOTALES para considerar un Doji plano
input int      MaxCandlesOutside = 6;          // Max velas fuera de caja antes de reversion (30m)
input int      MaxMinutesForReversal = 60;     // Max. minutos absolutos para caducar (1h)
input string   ManualBoxName     = "ZonaLiquidez"; // Nombre del Rectangulo Manual (Modo Manual)



//--- Global variables
int lastTradeDay = -1;        // FIX bug3: ahora guarda una clave de fecha completa (YYYYMMDD), no solo el dia del mes
int currentSessionDay = -1;   // FIX bug3: idem
double Pip;                   // Multiplicador dinamico para brokers de 4 o 5 digitos

bool sweptHigh = false;
bool sweptLow = false;
bool burnedHigh = false;
bool burnedLow = false;
bool patternFoundHigh = false;
bool patternFoundLow = false;
double peakHigh = 0;
double troughLow = 0;
datetime timeSweptHigh = 0;
datetime timeSweptLow = 0;

// FIX bug6: registro en memoria de tickets ya parcialmente cerrados,
// como respaldo al chequeo de comentario (que depende del broker)
int g_partialClosedTickets[100];
int g_partialClosedCount = 0;

// Seguimiento por ticket para el modo "BE a 1:1 + trailing" (UseBreakEvenAt1R)
// NOTA: al igual que g_partialClosedTickets, esto vive en memoria y se pierde
// si el EA se recarga/reinicia a mitad de una operacion abierta.
int    g_mgmtTickets[200];
double g_mgmtRiskPips[200];
bool   g_mgmtBEDone[200];
bool   g_mgmtFlag1[200];
bool   g_mgmtFlag2[200];
// V2.61 FIX A2: tracking del pico de profit para detectar retrocesos reales.
bool   g_mgmtFlag2Armed[200];       // true una vez que el precio ha alcanzado EscalonadoRR2 * riskPips en algun tick.
double g_peakProfitLong[200];        // max Bid visto para tickets BUY (mientras Estado 1 ya activo).
double g_peakProfitShort[200];       // min Ask visto para tickets SELL (mientras Estado 1 ya activo).
int    g_mgmtCount = 0;

//+------------------------------------------------------------------+
//| Devuelve una clave de fecha completa AAAAMMDD para comparar dias |
//| de forma segura entre distintos meses/anos (FIX bug3)            |
//+------------------------------------------------------------------+
int GetDateKey(datetime t)
  {
   return TimeYear(t) * 10000 + TimeMonth(t) * 100 + TimeDay(t);
  }

//+------------------------------------------------------------------+
//| AJUSTE AUTOMATICO DE DST (Horario Verano/Invierno Europeo)       |
//| Los brokers como Skilling siguen el DST europeo:                 |
//|   - Verano (CEST): GMT+3 (ultimo domingo marzo -> ultimo dom oct)|
//|   - Invierno (CET): GMT+2 (resto del ano)                       |
//| Los inputs de horas estan calibrados para VERANO (GMT+3).        |
//| En invierno se resta 1h para compensar el desfase del servidor.  |
//+------------------------------------------------------------------+
int GetLastSundayDay(int year, int month)
  {
   // Ultimo dia del mes
   int lastDay = 31;
   if(month == 4 || month == 6 || month == 9 || month == 11) lastDay = 30;
   if(month == 2) lastDay = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? 29 : 28;

   // Retroceder desde el ultimo dia hasta encontrar un domingo (dow=0)
   string dateStr = StringFormat("%04d.%02d.%02d 00:00:00", year, month, lastDay);
   datetime dt = StrToTime(dateStr);
   int dow = TimeDayOfWeek(dt);
   return lastDay - dow;
  }

bool IsBrokerSummerTime(datetime t)
  {
   int year  = TimeYear(t);
   int month = TimeMonth(t);
   int day   = TimeDay(t);

   if(month < 3 || month > 10) return false;  // Nov-Feb = invierno seguro
   if(month > 3 && month < 10) return true;   // Abr-Sep = verano seguro

   int lastSunday = GetLastSundayDay(year, month);

   if(month == 3)  return (day >= lastSunday); // Marzo: verano desde ultimo domingo
   if(month == 10) return (day < lastSunday);  // Octubre: invierno desde ultimo domingo

   return false;
  }

int GetDSTAdjustedHour(int hour)
  {
   if(!IsBrokerSummerTime(TimeCurrent()))
     {
      hour = hour - 1;
      if(hour < 0) hour += 24;
     }
   return hour;
  }

// Forward declaration: RegisterInitialRisk se usa en OnInit() (rehidratacion de
// g_mgmtTickets tras un reinicio) pero su definicion completa esta mas abajo,
// junto al resto de helpers de gestion BE a 1:1.
void RegisterInitialRisk(int ticket, double riskPips);

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   if(Period() != PERIOD_M5)
     {
      Print("Aviso: este EA esta disenado para M5. Timeframe actual: ", Period());
     }

   if(UseBreakEvenAt1R)
      Print("Modo BE a 1:1 activo: 'UseAutoBreakEven' y 'BreakEvenActivation' quedan ignorados. ",
            "El SL se mueve a breakeven al alcanzar 1:1 y luego usa 'TrailingPips' como distancia de trailing.");

   if(UseBreakEvenAt1R && UseEscalonadoTP)
      Print("ATENCION: Ambos UseBreakEvenAt1R y UseEscalonadoTP activos. UseEscalonadoTP tiene prioridad y se ignorara UseBreakEvenAt1R.");
   
   if(UseAutoBreakEven && UseBreakEvenAt1R)
      Print("ATENCION: Ambos modos de BE activos. Solo se aplicara 'UseBreakEvenAt1R' (ignora 'UseAutoBreakEven').");

   if(UseNewsFilter && !GlobalVariableCheck("SMC_News_High") && !GlobalVariableCheck("SMC_News_Med"))
      Print("ALERTA: News_Fetcher.mq4 no detectada en chart. Filtro de noticias DESACTIVADO.");

   Print("Aviso: Filtro de tendencia macro DESHABILITADO por diseno (Judas Swing requiere operar contra el impulso). IsTrendAligned siempre retorna true.");

   // Log de estado DST al iniciar
   if(IsBrokerSummerTime(TimeCurrent()))
      Print("DST Auto: Horario de VERANO detectado (GMT+3). Horas de sesion sin ajuste. Asia: ", StartHour, ":00-", EndHour, ":00");
   else
      Print("DST Auto: Horario de INVIERNO detectado (GMT+2). Horas ajustadas -1h. Asia: ", StartHour-1, ":00-", EndHour-1, ":00");

   // --- Validacion de inputs contradictorios (FIX auditoria V2.5) ---
   if(StartHour >= EndHour)
      Print("ATENCION: StartHour (", StartHour, ") >= EndHour (", EndHour, "). El rango de la sesion asiatica es invalido/vacio. Revisa los inputs.");

   if(EndHour >= MaxEntryHour)
      Print("ATENCION: EndHour (", EndHour, ") >= MaxEntryHour (", MaxEntryHour, "). No habra ventana de entrada disponible. Revisa los inputs.");

   if(MinBoxPips >= MaxBoxPips)
      Print("ATENCION: MinBoxPips (", MinBoxPips, ") >= MaxBoxPips (", MaxBoxPips, "). Ninguna caja asiatica pasara el filtro de tamano. Revisa los inputs.");

   if(EndOfDayHour < EndHour)
      Print("ATENCION: EndOfDayHour (", EndOfDayHour, ") es menor que EndHour (", EndHour, "). El cierre de fin de dia ocurriria antes de poder operar.");

   // Rehidratar arrays: cierres parciales ya registrados (por comentario del broker)
   for(int i = 0; i < OrdersTotal(); i++)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            int t = OrderTicket();
            if(StringFind(OrderComment(), "from #") >= 0 && g_partialClosedCount < 100)
              {
               g_partialClosedTickets[g_partialClosedCount] = t;
               g_partialClosedCount++;
              }
           }
        }
     }

   // Solucionar el problema de "Fractional Pips" (Brokers de 3 o 5 digitos vs Clasicos)
   // NOTA: debe calcularse ANTES de rehidratar g_mgmt* porque esa rehidratacion usa Pip.
   Pip = (Digits == 3 || Digits == 5) ? 10.0 * Point : 1.0 * Point;

   RefreshRates(); // FIX HIGH-1: Evitar race condition entre bucles durante rehidratacion

   // Rehidratar seguimiento de gestion BE a 1:1 (g_mgmtTickets) para operaciones vivas
   // que sobreviven a un reinicio del EA (crash, redeploy, reinicio de VPS).
   // FIX auditoria V2.5 (HIGH): antes de este fix, una operacion viva perdia por completo
   // su seguimiento de riesgo inicial y nunca recibia BE/trailing tras un reinicio.
   // Aproximacion aceptada: el riesgo inicial se recalcula como la distancia actual
   // OpenPrice<->StopLoss. Si el SL ya se habia movido (BE/trailing) antes del reinicio,
   // el riesgo recalculado sera menor al original; es una limitacion conocida y aceptada
   // (mejor una aproximacion que perder el tracking por completo).
   if(UseBreakEvenAt1R || UseEscalonadoTP)
     {
      for(int j = 0; j < OrdersTotal(); j++)
        {
         if(OrderSelect(j, SELECT_BY_POS, MODE_TRADES))
           {
            if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
              {
               if(OrderType() == OP_BUY || OrderType() == OP_SELL)
                 {
                  if(OrderStopLoss() > 0)
                    {
                     double riskPips = MathAbs(OrderOpenPrice() - OrderStopLoss()) / Pip;
                     if(riskPips > 0)
                       {
                        RegisterInitialRisk(OrderTicket(), riskPips);
                        Print("Rehidratado seguimiento BE/Escalonado para ticket #", OrderTicket(),
                              " (riesgo aproximado: ", DoubleToStr(riskPips, 1), " pips).");
                        
                        if(UseEscalonadoTP)
                          {
                           double profitPips = 0;
                           if(OrderType() == OP_BUY) profitPips = (Bid - OrderOpenPrice()) / Pip;
                           else profitPips = (OrderOpenPrice() - Ask) / Pip;
                           
                           int idx = FindMgmtIndex(OrderTicket());
                           if(idx >= 0)
                             {
                              if(profitPips >= EscalonadoRR1 * riskPips) g_mgmtFlag1[idx] = true;
                              if(profitPips >= EscalonadoRR2 * riskPips) g_mgmtFlag2[idx] = true;
                             }
                          }
                       }
                    }
                  else
                    {
                     Print("ATENCION: ticket #", OrderTicket(), " vivo sin StopLoss al reiniciar. ",
                           "No se puede rehidratar riesgo inicial.");
                    }
                 }
              }
           }
        }
     }

   return(INIT_SUCCEEDED);
  }


//+------------------------------------------------------------------+
//| Calcular Lotaje Dinamico basado en el Riesgo y Stop Loss         |
//+------------------------------------------------------------------+
double CalculateLotSize(double slDistancePips)
  {
   if(!UseDynamicLot || slDistancePips <= 0) return FixedLotSize;

   double riskAmount = AccountBalance() * (RiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);

   if(tickValue == 0) return FixedLotSize; // Fallback de seguridad

   // Formula: Lote = Riesgo / (SL_Points * TickValue)
   double slPoints = slDistancePips * (Pip / Point);
   double lot = riskAmount / (slPoints * tickValue);

   double minLot = MarketInfo(Symbol(), MODE_MINLOT);
   double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
   double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

   if(lot < minLot) lot = minLot;
   if(lot > maxLot) lot = maxLot;

   // Normalizar al LotStep (ej: 0.01)
   lot = MathFloor(lot / lotStep) * lotStep;
   return lot;
  }

//+------------------------------------------------------------------+
//| Helpers de seguimiento por ticket para UseBreakEvenAt1R          |
//+------------------------------------------------------------------+
int FindMgmtIndex(int ticket)
  {
   for(int i = 0; i < g_mgmtCount; i++)
      if(g_mgmtTickets[i] == ticket) return i;
   return -1;
  }

void RegisterInitialRisk(int ticket, double riskPips)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx >= 0)
     {
      g_mgmtRiskPips[idx] = riskPips;
      g_mgmtBEDone[idx] = false;
      g_mgmtFlag2Armed[idx] = false;
      // No reseteamos peaks: si el ticket ya venia del Estado 1 desde antes,
      // los peaks anteriores se preservan. Si quieres reset total,
      // hazlo manualmente llamando ResetManagement().
      return;
     }
   if(g_mgmtCount < 200)
     {
      int i = g_mgmtCount;
      g_mgmtTickets[i] = ticket;
      g_mgmtRiskPips[i] = riskPips;
      g_mgmtBEDone[i] = false;
      g_mgmtFlag1[i] = false;
      g_mgmtFlag2[i] = false;
      g_mgmtFlag2Armed[i] = false;       // V2.61 FIX A2
      g_peakProfitLong[i]  = 0.0;          // V2.61 FIX A2
      g_peakProfitShort[i] = 999999.99;    // V2.61 FIX A2 (sentinel alto para SELL)
      g_mgmtCount++;
     }
  }

double GetInitialRisk(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx < 0) return -1;
   return g_mgmtRiskPips[idx];
  }

bool IsBEActivated(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx < 0) return false;
   return g_mgmtBEDone[idx];
  }

void SetBEActivated(int ticket)
  {
   int idx = FindMgmtIndex(ticket);
   if(idx >= 0) g_mgmtBEDone[idx] = true;
  }

//+------------------------------------------------------------------+
//| Mover a Break-Even al alcanzar 1:1 (R) y activar trailing por    |
//| pips fijos a partir de ahi. Sustituye a ManageAutoBreakEven() +  |
//| ManageTrailingStop() mientras UseBreakEvenAt1R = true.           |
//+------------------------------------------------------------------+
void ManageBreakEvenAt1R()
  {
   if(!UseBreakEvenAt1R) return;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue; // solo posiciones de mercado

            int ticket = OrderTicket();
            double riskPips = GetInitialRisk(ticket);
            if(riskPips <= 0) continue; // no se registro riesgo inicial para este ticket

            double profitPips = 0;
            if(OrderType() == OP_BUY)  profitPips = (Bid - OrderOpenPrice()) / (Pip);
            else                       profitPips = (OrderOpenPrice() - Ask) / (Pip);

            if(!IsBEActivated(ticket))
              {
               // --- Fase 1: esperar a alcanzar 1:1 (profit >= riesgo inicial) ---
               if(profitPips >= riskPips)
                 {
                  double newSL;
                  bool okMove = false;

                  if(OrderType() == OP_BUY)
                    {
                     newSL = NormalizeDouble(OrderOpenPrice() + BreakEvenExtraPips * Pip, Digits);
                     if((OrderStopLoss() < newSL || OrderStopLoss() == 0) && newSL < Bid) okMove = true;
                    }
                  else
                    {
                     newSL = NormalizeDouble(OrderOpenPrice() - BreakEvenExtraPips * Pip, Digits);
                     if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) okMove = true;
                    }

                  if(okMove)
                    {
                     if(OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue))
                       {
                        SetBEActivated(ticket);
                        Print("BE a 1:1 activado en ticket #", ticket, ". SL movido a breakeven+buffer.");
                       }
                    }
                 }
              }
            else
              {
               // --- Fase 2: ya en breakeven, aplicar trailing por pips fijos ---
               if(TrailingPips <= 0) continue;
               double trailingPoints = TrailingPips * Pip;

               if(OrderType() == OP_BUY)
                 {
                  if(Bid - OrderOpenPrice() > trailingPoints)
                    {
                     double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                     if(newSL - OrderStopLoss() > Point * 2)
                       {
                        double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                        if(Bid - newSL >= stopLevel)
                          {
                           bool res = OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                           if(!res) Print("Error modificando SL (Trailing Buy): ", GetLastError());
                          }
                       }
                    }
                 }
               else
                 {
                  if(OrderOpenPrice() - Ask > trailingPoints)
                    {
                     double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                     if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0)
                       {
                        double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                        if(newSL - Ask >= stopLevel)
                          {
                           bool res = OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                           if(!res) Print("Error modificando SL (Trailing Sell): ", GetLastError());
                          }
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Trailing Stop para operaciones abiertas                |
//| (Solo se usa cuando UseBreakEvenAt1R = false)                    |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(!UseTrailingStop || TrailingPips <= 0) return;

   double trailingPoints = TrailingPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Bid - trailingPoints, Digits);
                  if(newSL - OrderStopLoss() > Point * 2) // Solo si mejora el SL en mas de 2 puntos
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error TrailingStop BUY #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask > trailingPoints)
                 {
                  double newSL = NormalizeDouble(Ask + trailingPoints, Digits);
                  if(OrderStopLoss() - newSL > Point * 2 || OrderStopLoss() == 0) // Solo si baja el SL
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen);
                        if(!res) Print("Error TrailingStop SELL #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Gestionar Auto Break-Even                                        |
//+------------------------------------------------------------------+
void ManageAutoBreakEven()
  {
   if(!UseAutoBreakEven || BreakEvenActivation <= 0) return;

   double activationPoints = BreakEvenActivation * Pip;
   double extraPoints = BreakEvenExtraPips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY)
              {
               if(Bid - OrderOpenPrice() >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() + extraPoints, Digits);
                  if(OrderStopLoss() < newSL && newSL < Bid) // Solo subir SL si mejora y no choca con el Bid
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(Bid - newSL >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                        if(!res) Print("Error AutoBE BUY #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
            else if(OrderType() == OP_SELL)
              {
               if(OrderOpenPrice() - Ask >= activationPoints)
                 {
                  double newSL = NormalizeDouble(OrderOpenPrice() - extraPoints, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) // Solo bajar SL
                    {
                     double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                     if(newSL - Ask >= stopLevel)
                       {
                        bool res = OrderModify(OrderTicket(), OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue);
                        if(!res) Print("Error AutoBE SELL #", OrderTicket(), ": ", GetLastError());
                       }
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Comprueba si un ticket ya fue registrado como parcialmente       |
//| cerrado en esta sesion de la EA (FIX bug6)                       |
//+------------------------------------------------------------------+
bool IsAlreadyPartiallyClosed(int ticket)
  {
   for(int k = 0; k < g_partialClosedCount; k++)
      if(g_partialClosedTickets[k] == ticket) return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Gestionar Cierre Parcial Automatico                              |
//+------------------------------------------------------------------+
void ManagePartialClose()
  {
   if(!UsePartialClose || PartialClosePips <= 0) return;

   double targetPoints = PartialClosePips * Pip;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            // FIX bug6: chequeo doble - comentario (depende del broker) + registro propio en memoria
            if(StringFind(OrderComment(), "from #") >= 0) continue;
            if(IsAlreadyPartiallyClosed(OrderTicket())) continue;

            double profitPoints = 0;
            if(OrderType() == OP_BUY)  profitPoints = Bid - OrderOpenPrice();
            if(OrderType() == OP_SELL) profitPoints = OrderOpenPrice() - Ask;

            if(profitPoints >= targetPoints)
              {
               double lotToClose = OrderLots() * (PartialClosePercent / 100.0);
               double minLot = MarketInfo(Symbol(), MODE_MINLOT);
               double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);

               lotToClose = MathFloor(lotToClose / lotStep) * lotStep;

               // Asegurar que el lote a cerrar es valido y deja algo abierto
               if(lotToClose >= minLot && (OrderLots() - lotToClose) >= minLot)
                 {
                  int origTicket = OrderTicket();
                  bool res = OrderClose(origTicket, lotToClose, (OrderType() == OP_BUY) ? Bid : Ask, SLIPPAGE, clrOrange);
                  if(res)
                    {
                     // FIX bug6: registrar el ticket para no volver a cerrar parcialmente
                     if(g_partialClosedCount < 100)
                       {
                        g_partialClosedTickets[g_partialClosedCount] = origTicket;
                        g_partialClosedCount++;
                       }
                     Print("SMC Cierre Parcial Automatico ejecutado: ", lotToClose, " lotes.");
                     if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Cierre Parcial alcanzado");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Evaluar la tendencia macro basada en EMAs                        |
//+------------------------------------------------------------------+
bool IsTrendAligned(bool isBuy)
  {
   return true; // Filtro de tendencia eliminado (las EMAs arruinan el Judas Swing)
  }

//+------------------------------------------------------------------+
//| Limpiar ordenes pendientes al final del dia                      |
//+------------------------------------------------------------------+
void CleanPendingOrders()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUYLIMIT || OrderType() == OP_SELLLIMIT)
              {
               bool del = OrderDelete(OrderTicket());
               if(!del) Print("Error borrando orden: ", GetLastError());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Contar operaciones del dia y verificar activas                   |
//| FIX bug3: compara fecha completa (ano/mes/dia), no solo el dia   |
//| FIX bug4: deduplica cierres parciales que generan un ticket extra|
//|           en el historial con el mismo OpenTime/Type que la      |
//|           operacion original                                     |
//+------------------------------------------------------------------+
int GetTradesTodayCount()
  {
   int todayKey = GetDateKey(TimeCurrent());

   datetime seenTimes[100];
   int seenTypes[100];
   ArrayInitialize(seenTimes, 0);   // FIX: elimina warning "possible use of uninitialized variable"
   ArrayInitialize(seenTypes, -1);  // FIX: idem
   int seenCount = 0;
   int count = 0;

   // --- Operaciones abiertas ---
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }

   // --- Historial (incluye fragmentos de cierres parciales, que se deduplican) ---
   for(int i = OrdersHistoryTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_HISTORY))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if((OrderType() == OP_BUY || OrderType() == OP_SELL) && GetDateKey(OrderOpenTime()) == todayKey)
              {
               bool already = false;
               for(int k = 0; k < seenCount; k++)
                  if(seenTimes[k] == OrderOpenTime() && seenTypes[k] == OrderType()) { already = true; break; }

               if(!already && seenCount < 100)
                 {
                  seenTimes[seenCount] = OrderOpenTime();
                  seenTypes[seenCount] = OrderType();
                  seenCount++;
                  count++;
                 }
              }
           }
        }
     }
   return count;
  }

bool HasActiveTrades()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() == OP_BUY || OrderType() == OP_SELL) return true;
           }
        }
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Patrones de Reversion SMC (Alex Ruiz)                            |
//+------------------------------------------------------------------+
bool isBearishReversal(int shift)
  {
   double open = Open[shift];
   double close = Close[shift];
   double high = High[shift];
   double low = Low[shift];

   // Filtro de ruido EXCLUSIVO para la tarde (Nueva York):
   // Por la manana (Londres) cualquier vela es valida porque la manipulacion es mas fiable.
   double totalSize = (high - low) / (Pip);
   if(TimeHour(Time[shift]) >= 13 && totalSize < MinReversalCandlePips) return false;

   // La vela de gatillo idealmente debe cerrar bajista o plana
   if(close > open) return false;

   double body = MathAbs(open - close);
   double upperWick = high - MathMax(open, close);
   double lowerWick = MathMin(open, close) - low;

   // 1. Pinbar Bajista (Martillo invertido / Shooting star)
   bool isPinbar = false;
   if(body > 0)
     {
      if(upperWick >= 1.5 * body && lowerWick <= body * 1.5) isPinbar = true;
     }
   else
     {
      // Si es un Doji plano
      if(upperWick > MinDojiSizePips * Pip && lowerWick < upperWick * 0.5) isPinbar = true;
     }

   // 2. Envolvente Bajista (Bearish Engulfing) - Ajustado para Forex
   double prevOpen = Open[shift+1];
   double prevClose = Close[shift+1];
   bool isBullishPrev = prevClose >= prevOpen; // Permite que la anterior sea un Doji plano
   bool isEngulfing = isBullishPrev && (close < prevOpen) && (body > MathAbs(prevClose - prevOpen));

   return isPinbar || isEngulfing;
  }

bool isBullishReversal(int shift)
  {
   double open = Open[shift];
   double close = Close[shift];
   double high = High[shift];
   double low = Low[shift];

   // Filtro de ruido EXCLUSIVO para la tarde (Nueva York):
   // Por la manana (Londres) cualquier vela es valida porque la manipulacion es mas fiable.
   double totalSize = (high - low) / (Pip);
   if(TimeHour(Time[shift]) >= 13 && totalSize < MinReversalCandlePips) return false;

   // La vela de gatillo idealmente debe cerrar alcista o plana
   if(close < open) return false;

   double body = MathAbs(close - open);
   double upperWick = high - MathMax(open, close);
   double lowerWick = MathMin(open, close) - low;

   // 1. Pinbar Alcista (Martillo)
   bool isPinbar = false;
   if(body > 0)
     {
      if(lowerWick >= 1.5 * body && upperWick <= body * 1.5) isPinbar = true;
     }
   else
     {
      // Si es un Doji plano
      if(lowerWick > MinDojiSizePips * Pip && upperWick < lowerWick * 0.5) isPinbar = true;
     }

   // 2. Envolvente Alcista (Bullish Engulfing) - Ajustado para Forex
   double prevOpen = Open[shift+1];
   double prevClose = Close[shift+1];
   bool isBearishPrev = prevOpen >= prevClose; // Permite que la anterior sea un Doji plano o roja
   bool isEngulfing = isBearishPrev && (close > prevOpen) && (body > MathAbs(prevOpen - prevClose));

   return isPinbar || isEngulfing;
  }

//+------------------------------------------------------------------+
//| Gestionar Take Profit Escalonado (Opcion A3: BE a 1:1, deja      |
//| correr al TP 1:3 del broker).                                    |
//| Estado 1 (1:1): recoloca SL a BE + buffer.                       |
//| Estado 2 (1:2): solo si EscalonadoMoveSLto1R=true, recoloca SL   |
//|                 a +1R (OrderOpenPrice + riskPips). De lo         |
//|                 contrario, se deja correr al TP 1:3 del broker.   |
//+------------------------------------------------------------------+
void ManageEscalonadoTP()
  {
   if(!UseEscalonadoTP) return;

   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
        {
         if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
           {
            if(OrderType() != OP_BUY && OrderType() != OP_SELL) continue;

            int ticket = OrderTicket();
            double riskPips = GetInitialRisk(ticket);
            if(riskPips <= 0) continue;

            int idx = FindMgmtIndex(ticket);
            if(idx < 0) continue;

            double profitPips = 0;
            if(OrderType() == OP_BUY)  profitPips = (Bid - OrderOpenPrice()) / Pip;
            else                       profitPips = (OrderOpenPrice() - Ask) / Pip;

            // ESTADO 1: Alcanzo 1:1 -> recolocar SL a Break-Even + buffer
            if(!g_mgmtFlag1[idx] && profitPips >= EscalonadoRR1 * riskPips)
              {
               double newSL;
               bool okMove = false;

               if(OrderType() == OP_BUY)
                 {
                  newSL = NormalizeDouble(OrderOpenPrice() + BreakEvenExtraPips * Pip, Digits);
                  if((OrderStopLoss() < newSL || OrderStopLoss() == 0) && newSL < Bid) okMove = true;
                 }
               else
                 {
                  newSL = NormalizeDouble(OrderOpenPrice() - BreakEvenExtraPips * Pip, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) okMove = true;
                 }

               if(okMove)
                 {
                  double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                  bool distOk = false;
                  if(OrderType() == OP_BUY  && (Bid - newSL) >= stopLevel) distOk = true;
                  if(OrderType() == OP_SELL && (newSL - Ask) >= stopLevel) distOk = true;

                  if(distOk)
                    {
                     if(OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrBlue))
                       {
                        // FIX bug robustez flag1: solo marcar tras OrderModify exitoso.
                        // Si falla, dejamos flag1=false para reintentar el siguiente tick.
                        g_mgmtFlag1[idx] = true;
                        Print("Escalado 1:1 alcanzado en ticket #", ticket, ". SL movido a Break-Even.");
                       }
                     else
                       Print("Aviso: No se pudo mover SL a BE en ticket #", ticket, " (OrderModify fallo: ", GetLastError(), "). Reintentando proximo tick.");
                    }
                  else
                    {
                     Print("Aviso: No se pudo mover SL a BE en ticket #", ticket, " por StopLevel. Reintentando proximo tick.");
                    }
                 }
              }

            // V2.61 FIX A2 (sub-bloque "arming"): una vez que el Estado 1 esta
            // activo, rastreamos el pico de profit visto y marcamos
            // g_mgmtFlag2Armed=true cuando el precio ALCANZA EscalonadoRR2 * riskPips
            // por primera vez. Esto preserva el evento aunque el precio siga subiendo
            // o retroceda entre ticks consecutivos.
            if(g_mgmtFlag1[idx] && !g_mgmtFlag2[idx])
              {
               if(OrderType() == OP_BUY)
                 {
                  if(Bid > g_peakProfitLong[idx]) g_peakProfitLong[idx] = Bid;
                  double maxProfitPipsLong = (g_peakProfitLong[idx] - OrderOpenPrice()) / Pip;
                  if(!g_mgmtFlag2Armed[idx] && maxProfitPipsLong >= EscalonadoRR2 * riskPips)
                    {
                     g_mgmtFlag2Armed[idx] = true;
                     Print("V2.61 A2: ticket #", ticket, " ha tocado ", EscalonadoRR2, "R. Esperando retroceso para lock a +1R.");
                    }
                 }
               else // OP_SELL
                 {
                  if(Ask < g_peakProfitShort[idx]) g_peakProfitShort[idx] = Ask;
                  double maxProfitPipsShort = (OrderOpenPrice() - g_peakProfitShort[idx]) / Pip;
                  if(!g_mgmtFlag2Armed[idx] && maxProfitPipsShort >= EscalonadoRR2 * riskPips)
                    {
                     g_mgmtFlag2Armed[idx] = true;
                     Print("V2.61 A2: ticket #", ticket, " ha tocado ", EscalonadoRR2, "R. Esperando retroceso para lock a +1R.");
                    }
                 }
              }

            // ESTADO 2 (V2.61 FIX A2): solo recoloca SL a +1R cuando se cumplen
            // las DOS condiciones:
            //   (a) g_mgmtFlag2Armed=true: el precio YA ha tocado EscalonadoRR2 * riskPips.
            //   (b) profitPips <= (pico_visto - EscalonadoPullbackPips * riskPips):
            //       el precio ha retrocedido al menos EscalonadoPullbackPips en unidades
            //       de R desde su pico.
            // Si el precio sigue subiendo hacia TP 1:3 sin retroceder, NO se toca el SL.
            // Esto elimina el corte prematuro de ganadoras (Categoria B).
            if(EscalonadoMoveSLto1R
               && g_mgmtFlag1[idx]
               && !g_mgmtFlag2[idx]
               && g_mgmtFlag2Armed[idx]
               && profitPips <= (EscalonadoRR2 - EscalonadoPullbackPips) * riskPips)
              {
               double newSL;
               bool okMove = false;

               if(OrderType() == OP_BUY)
                 {
                  // SL a +1R: OpenPrice + EscalonadoRR1 * riskPips * Pip
                  newSL = NormalizeDouble(OrderOpenPrice() + EscalonadoRR1 * riskPips * Pip, Digits);
                  if((OrderStopLoss() < newSL || OrderStopLoss() == 0) && newSL < Bid) okMove = true;
                 }
               else
                 {
                  newSL = NormalizeDouble(OrderOpenPrice() - EscalonadoRR1 * riskPips * Pip, Digits);
                  if((OrderStopLoss() > newSL || OrderStopLoss() == 0) && newSL > Ask) okMove = true;
                 }

               if(okMove)
                 {
                  double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                  bool distOk = false;
                  if(OrderType() == OP_BUY  && (Bid - newSL) >= stopLevel) distOk = true;
                  if(OrderType() == OP_SELL && (newSL - Ask) >= stopLevel) distOk = true;

                  if(distOk)
                    {
                     if(OrderModify(ticket, OrderOpenPrice(), newSL, OrderTakeProfit(), 0, clrGreen))
                       {
                        g_mgmtFlag2[idx] = true;
                        Print("V2.61 A2: ticket #", ticket, " retrocedio ", EscalonadoPullbackPips, "R desde pico. SL movido a +1R.");
                       }
                     else
                       Print("Aviso: No se pudo mover SL a +1R en ticket #", ticket, " (OrderModify fallo: ", GetLastError(), "). Reintentando proximo tick.");
                    }
                  else
                    {
                     Print("Aviso: No se pudo mover SL a +1R en ticket #", ticket, " por StopLevel. Reintentando proximo tick.");
                    }
                 }
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // TP Escalonado a 1:1 y 1:2
   if(UseEscalonadoTP)
     {
      ManageEscalonadoTP();
     }
   else if(UseBreakEvenAt1R)
     {
      ManageBreakEvenAt1R();
     }
   else
     {
      ManageTrailingStop();
      ManageAutoBreakEven();
     }
   ManagePartialClose();

   int currentHour = Hour();
   int currentDay = GetDateKey(TimeCurrent()); // FIX bug3: clave de fecha completa, no solo Day()

   // Ajuste automatico de DST: Aplica a la caja asiatica y a los limites horarios
   // para mantener la misma franja horaria real a lo largo del ano.
   int adjStartHour = GetDSTAdjustedHour(StartHour);
   int adjEndHour   = GetDSTAdjustedHour(EndHour);
   int adjMaxEntryHour = GetDSTAdjustedHour(MaxEntryHour);
   int adjEndOfDayHour = GetDSTAdjustedHour(EndOfDayHour);

   // Si es el final del dia (input EndOfDayHour), limpiamos ordenes
   // pendientes que no se activaron y, opcionalmente, cerramos activas con reintentos.
   if(currentHour >= adjEndOfDayHour)
     {
      CleanPendingOrders();
      if(CloseAtEndOfDay)
        {
         for(int i = OrdersTotal() - 1; i >= 0; i--)
           {
            if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
              {
               if(OrderMagicNumber() == MagicNumber && OrderSymbol() == Symbol())
                 {
                  if(OrderType() == OP_BUY || OrderType() == OP_SELL)
                    {
                     int ticketToClose = OrderTicket();
                     double lotsToClose = OrderLots();
                     bool closed = false;

                     // FIX auditoria V2.5 (MEDIUM): reintentos con slippage creciente para evitar
                     // que un spread ampliado (viernes noche, rollover) deje la posicion abierta
                     // todo el fin de semana por un simple "Off quotes".
                     for(int attempt = 1; attempt <= 3 && !closed; attempt++)
                       {
                        RefreshRates();
                        double closePrice = (OrderType() == OP_BUY) ? Bid : Ask;
                        int attemptSlippage = SLIPPAGE * attempt;

                        closed = OrderClose(ticketToClose, lotsToClose, closePrice, attemptSlippage, clrOrange);
                        if(closed)
                          {
                           Print("SMC: Cierre de fin de dia (Time Stop) ejecutado para orden #", ticketToClose,
                                 " en intento ", attempt, ".");
                          }
                        else
                          {
                           Print("SMC Error: Fallo Cierre de fin de dia #", ticketToClose,
                                 " (intento ", attempt, "/3). Error: ", GetLastError());
                          }
                       }

                     if(!closed)
                        Print("SMC ALERTA: No se pudo cerrar la orden #", ticketToClose,
                              " tras 3 intentos. Revisar manualmente (riesgo de swap/gap de fin de semana).");
                    }
                 }
              }
           }
        }
     }


   // Limpiamos pendientes si ya llegamos al limite del dia o hay activas
   if(GetTradesTodayCount() >= MaxTradesPerDay || HasActiveTrades())
     {
      CleanPendingOrders();
     }

   // Solo buscar operaciones despues de cerrar la caja asiatica y antes del limite (Killzone Londres)
   if(currentHour >= adjEndHour && currentHour < adjMaxEntryHour)
     {
      // Resetear variables de barrido cada nuevo dia
      if(currentDay != currentSessionDay)
        {
         sweptHigh = false;
         sweptLow = false;
         burnedHigh = false;
         burnedLow = false;
         patternFoundHigh = false;
         patternFoundLow = false;
         peakHigh = 0;
         troughLow = 0;
         timeSweptHigh = 0;
         timeSweptLow = 0;
         
         // Fix Bug: Solo resetear memoria de gestion si no hay operaciones vivas
         if(!HasActiveTrades())
           {
            g_partialClosedCount = 0; // Limpiar memoria de cierres parciales
            g_mgmtCount = 0;          // Limpiar memoria de gestion BreakEven/Trailing
           }
         currentSessionDay = currentDay;
        }

      // Filtro de dias de la semana
      int dayOfWeek = TimeDayOfWeek(TimeCurrent());
      bool isTradingDay = false;
      if(dayOfWeek == 1 && TradeMonday) isTradingDay = true;
      else if(dayOfWeek == 2 && TradeTuesday) isTradingDay = true;
      else if(dayOfWeek == 3 && TradeWednesday) isTradingDay = true;
      else if(dayOfWeek == 4 && TradeThursday) isTradingDay = true;
      else if(dayOfWeek == 5 && TradeFriday) isTradingDay = true;

      // Comprobar si el dia fue ignorado, o alcanzamos limite, o hay trades activos
      if(!isTradingDay)
        {
         if(currentDay != lastTradeDay)
           {
            Print("Dia desactivado en ajustes. Se ignora la operativa hoy.");
            lastTradeDay = currentDay;
           }
         return;
        }

      if(currentDay == lastTradeDay) { return; }
      if(GetTradesTodayCount() >= MaxTradesPerDay) { return; }
      if(HasActiveTrades()) { return; }

      // Calcular inicio y fin de la sesion asiatica para HOY
      datetime currentDayStart = iTime(Symbol(), PERIOD_D1, 0);
      datetime timeStart = currentDayStart + adjStartHour * 3600;
      datetime timeEnd = currentDayStart + adjEndHour * 3600;

      int shiftStart = iBarShift(Symbol(), Period(), timeStart);
      // Restamos 1 segundo para no incluir la vela que empieza EXACTAMENTE a las 08:00
      int shiftEnd = iBarShift(Symbol(), Period(), timeEnd - 1);

      if(shiftStart < 0 || shiftEnd < 0 || shiftStart <= shiftEnd)
        {
         return;
        }

      // FIX bug2: +1 para incluir tambien la vela de shiftStart (apertura de la sesion asiatica),
      // que antes quedaba excluida del rango de iHighest/iLowest
      int barsCount = shiftStart - shiftEnd + 1;

      int highestIdx = iHighest(Symbol(), Period(), MODE_HIGH, barsCount, shiftEnd);
      int lowestIdx  = iLowest(Symbol(), Period(), MODE_LOW, barsCount, shiftEnd);

      if(highestIdx < 0 || lowestIdx < 0)
        {
         return;
        }

      double asianHigh = High[highestIdx];
      double asianLow  = Low[lowestIdx];

      // Filtro de Tamano de Caja
      double boxSizePips = (asianHigh - asianLow) / (Pip);
      if(boxSizePips < MinBoxPips || boxSizePips > MaxBoxPips)
        {
         lastTradeDay = currentDay;
         Print("Caja asiatica ignorada por tamano: ", DoubleToStr(boxSizePips, 1), " pips.");
         return;
        }

      if(AutoFindLiquidity)
        {
         // MODO AUTOMATICO: Vigilar Ruptura y Reversion (Asian Sweep - Alex Ruiz SMC)
         bool triggerSell = false;
         bool triggerBuy = false;

         static datetime lastBarTime = 0;
         bool isNewBar = false;
         if(Time[0] != lastBarTime)
           {
            isNewBar = true;
            lastBarTime = Time[0];
           }

         if(isNewBar)
           {
            // 1. Detectar si la vela anterior rompio CON ENERGIA (Cerrando fuera)
            // Se requiere Close[2] dentro de la caja para garantizar que es el momento EXACTO de la ruptura,
            // evitando que se reinicien trampas caducadas si el precio sigue flotando fuera.
            if(Close[1] > asianHigh && Close[2] <= asianHigh && !burnedHigh)
              {
               if(!sweptHigh)
                 {
                  double bodyPips = MathAbs(Close[1] - Open[1]) / (Pip);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptHigh = Time[1]; // Registrar inicio de la manipulacion
                     sweptHigh = true;
                     peakHigh = High[1];
                     Print("SMC: Ruptura Alcista detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
              }
            else if(sweptHigh && Close[1] > asianHigh)
              {
               if(High[1] > peakHigh) peakHigh = High[1]; // Mantener el pico mas alto mientras estemos fuera
              }

            if(Close[1] < asianLow && Close[2] >= asianLow && !burnedLow)
              {
               if(!sweptLow)
                 {
                  double bodyPips = MathAbs(Close[1] - Open[1]) / (Pip);
                  if(bodyPips >= MinBreakoutBodyPips)
                    {
                     timeSweptLow = Time[1]; // Registrar inicio de la manipulacion
                     sweptLow = true;
                     troughLow = Low[1];
                     Print("SMC: Ruptura Bajista detectada. Cuerpo: ", DoubleToStr(bodyPips, 1), " pips.");
                    }
                 }
              }
            else if(sweptLow && Close[1] < asianLow)
              {
               if(troughLow == 0 || Low[1] < troughLow) troughLow = Low[1]; // Mantener el valle mas bajo mientras estemos fuera
              }

            // 1.5 Validar si la trampa ha caducado por tiempo o velas (Killzones)
            // FIX auditoria V2.5 (HIGH): iBarShift puede devolver -1 si timeSweptHigh/Low
            // quedo residual de una sesion anterior y ya no esta dentro de la profundidad
            // de historial cargada. Antes, barsPassed=-1 nunca superaba MaxCandlesOutside
            // y el sweep podia quedar "vivo" indefinidamente, arrastrando una trampa
            // fantasma de un dia anterior al dia siguiente. Ahora tratamos barsPassed<0
            // como caducidad forzosa (invalidar sweep).
            if(sweptHigh)
              {
               int barsPassed = iBarShift(Symbol(), Period(), timeSweptHigh);
               bool caducadoPorVelas = (barsPassed < 0) || (barsPassed > MaxCandlesOutside);
               bool caducadoPorTiempo = (Time[0] - timeSweptHigh > MaxMinutesForReversal * 60);
               if(caducadoPorVelas || caducadoPorTiempo)
                 {
                  if(barsPassed < 0)
                     Print("SMC: sweptHigh invalidado por iBarShift(-1) (timeSweptHigh fuera de historial cargado).");
                  sweptHigh = false;
                  burnedHigh = true; // FIX: Quemar el techo para el resto del dia
                  patternFoundHigh = false; // Reset
                  peakHigh = 0;
                 }
               else
                 {
                  // Buscar el patron MIENTRAS estamos fuera (al cierre de cada vela)
                  if(!patternFoundHigh && isBearishReversal(1)) patternFoundHigh = true;
                 }
              }
            if(sweptLow)
              {
               int barsPassed = iBarShift(Symbol(), Period(), timeSweptLow);
               bool caducadoPorVelas = (barsPassed < 0) || (barsPassed > MaxCandlesOutside);
               bool caducadoPorTiempo = (Time[0] - timeSweptLow > MaxMinutesForReversal * 60);
               if(caducadoPorVelas || caducadoPorTiempo)
                 {
                  if(barsPassed < 0)
                     Print("SMC: sweptLow invalidado por iBarShift(-1) (timeSweptLow fuera de historial cargado).");
                  sweptLow = false;
                  burnedLow = true; // FIX: Quemar el suelo para el resto del dia
                  patternFoundLow = false; // Reset
                  troughLow = 0;
                 }
               else
                 {
                  // Buscar el patron MIENTRAS estamos fuera (al cierre de cada vela)
                  if(!patternFoundLow && isBullishReversal(1)) patternFoundLow = true;
                 }
              }

            // 2. Esperar Gatillo: Cierre dentro de la caja HABIENDO encontrado el patron previamente
            if(sweptHigh && Close[1] < asianHigh)
              {
               if(patternFoundHigh || isBearishReversal(1)) triggerSell = true;
               else
                 {
                  sweptHigh = false; // Si volvio a entrar sin haber hecho un patron nunca, invalidar
                  patternFoundHigh = false;
                 }
              }

            if(sweptLow && Close[1] > asianLow)
              {
               if(patternFoundLow || isBullishReversal(1)) triggerBuy = true;
               else
                 {
                  sweptLow = false; // Si volvio a entrar sin haber hecho un patron nunca, invalidar
                  patternFoundLow = false;
                 }
              }
           } // CIERRE DEL BLOQUE isNewBar
           
         if(UseNewsFilter && IsNewsTime())
           {
            if(triggerBuy || triggerSell) Print("SMC Entrada Bloqueada: Filtro de Noticias activo.");
            triggerBuy = false;
            triggerSell = false;
           }

         if(triggerSell)
           {
            if(!IsTrendAligned(false))
              {
               Print("Venta SMC Bloqueada: Tendencia macro alcista detectada.");
               triggerSell = false; // Bloquear
               sweptHigh = false; // Invalidar para no entrar tarde si la tendencia cambia luego
               patternFoundHigh = false;
              }
            else
              {
               // Reversion bajista -> VENDER
               double baseSL = peakHigh + SLBufferPips * Pip;
               double slPips = (baseSL - Bid) / (Pip);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Bid + slPips * Pip;
                 }
               double sl = NormalizeDouble(baseSL, Digits);

               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opcion B: Sin limite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Bid - (slPips * Pip * FixedRiskReward), Digits);
                    }

                  double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                  if(Bid < sl && (sl - Bid) >= stopLevel)
                    {
                     int t = OrderSend(Symbol(), OP_SELL, calculatedLot, Bid, SLIPPAGE, sl, actualTP, "SMC Reversion Sell", MagicNumber, 0, clrRed);
                     if(t > 0)
                       {
                        Print("Venta SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        RegisterInitialRisk(t, slPips); // Necesario para el modo BE a 1:1
                        if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: VENTA Auto abierta a " + DoubleToStr(Bid, Digits));
                        // Resetear el barrido tras entrar para obligar a buscar uno nuevo si hay reentradas
                        sweptHigh = false;
                        patternFoundHigh = false;
                       }
                     else Print("Error abriendo Venta SMC: ", GetLastError());
                    }
                  else
                    {
                     Print("Venta SMC abortada: SL demasiado cerca del precio actual (stopLevel = ", stopLevel/Point, " points)");
                    }
                 }
              }
           }

         if(triggerBuy)
           {
            if(!IsTrendAligned(true))
              {
               Print("Compra SMC Bloqueada: Tendencia macro bajista detectada.");
               triggerBuy = false; // Bloquear
               sweptLow = false; // Invalidar para no entrar tarde si la tendencia cambia luego
               patternFoundLow = false;
              }
            else
              {
               // Reversion alcista -> COMPRAR
               double baseSL = troughLow - SLBufferPips * Pip;
               double slPips = (Ask - baseSL) / (Pip);
               if(slPips < MinSLPips)
                 {
                  slPips = MinSLPips;
                  baseSL = Ask - slPips * Pip;
                 }
               double sl = NormalizeDouble(baseSL, Digits);

               if(slPips > 0)
                 {
                  double calculatedLot = CalculateLotSize(slPips);
                  double actualTP = 0; // Opcion B: Sin limite, gestionado por Trailing Stop
                  if(UseFixedRR)
                    {
                     actualTP = NormalizeDouble(Ask + (slPips * Pip * FixedRiskReward), Digits);
                    }

                  double stopLevel = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
                  if(Ask > sl && (Ask - sl) >= stopLevel)
                    {
                     int t = OrderSend(Symbol(), OP_BUY, calculatedLot, Ask, SLIPPAGE, sl, actualTP, "SMC Reversion Buy", MagicNumber, 0, clrBlue);
                     if(t > 0)
                       {
                        Print("Compra SMC ejecutada. Lote: ", calculatedLot, " SL: ", slPips, " pips. (Sin TP fijo)");
                        RegisterInitialRisk(t, slPips); // Necesario para el modo BE a 1:1
                        if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: COMPRA Auto abierta a " + DoubleToStr(Ask, Digits));
                        // Resetear el barrido tras entrar para obligar a buscar uno nuevo si hay reentradas
                        sweptLow = false;
                        patternFoundLow = false; // FIX bug1: faltaba este reset (simetria con el caso de venta)
                       }
                     else Print("Error abriendo Compra SMC: ", GetLastError());
                    }
                  else
                    {
                     Print("Compra SMC abortada: SL demasiado cerca del precio actual (stopLevel = ", stopLevel/Point, " points)");
                    }
                 }
              }
           }
        }
      else
        {
         // MODO MANUAL (Buscar el rectangulo del usuario)
         int objIdx = ObjectFind(0, ManualBoxName);
         if(objIdx >= 0)
           {
            double price1 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE1);
            double price2 = ObjectGetDouble(0, ManualBoxName, OBJPROP_PRICE2);

            double boxTop = MathMax(price1, price2);
            double boxBottom = MathMin(price1, price2);

            static bool boxDetected = false;
            if(!boxDetected)
              {
               Print("SMC: Caja '", ManualBoxName, "' detectada visualmente. Base: ", boxBottom, " Techo: ", boxTop, " (AsianHigh:", asianHigh, " AsianLow:", asianLow, ")");
               boxDetected = true;
              }

            double limitPrice = 0, stopLoss = 0, takeProfit = 0, slPips = 0;
            int orderType = -1;

            // Si la caja manual esta por encima de la asiatica, queremos VENDER
            if(boxBottom >= asianHigh)
              {
               limitPrice = boxBottom;
               stopLoss = boxTop + SLBufferPips * Pip;
               if((stopLoss - limitPrice) / (Pip) < MinSLPips) stopLoss = limitPrice + MinSLPips * Pip;
               slPips = (stopLoss - limitPrice) / (Pip);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice - (slPips * Pip * FixedRiskReward), Digits);
               else takeProfit = asianLow;
               orderType = OP_SELLLIMIT;
              }
            // Si la caja manual esta por debajo de la asiatica, queremos COMPRAR
            else if(boxTop <= asianLow)
              {
               limitPrice = boxTop;
               stopLoss = boxBottom - SLBufferPips * Pip;
               if((limitPrice - stopLoss) / (Pip) < MinSLPips) stopLoss = limitPrice - MinSLPips * Pip;
               slPips = (limitPrice - stopLoss) / (Pip);
               if(UseFixedRR) takeProfit = NormalizeDouble(limitPrice + (slPips * Pip * FixedRiskReward), Digits);
               else takeProfit = asianHigh;
               orderType = OP_BUYLIMIT;
              }

            if(orderType >= 0 && limitPrice > 0)
              {
               limitPrice = NormalizeDouble(limitPrice, Digits);
               stopLoss = NormalizeDouble(stopLoss, Digits);
               takeProfit = NormalizeDouble(takeProfit, Digits);

               bool validLimit = false;
               if(orderType == OP_BUYLIMIT && Ask > limitPrice) validLimit = true;
               if(orderType == OP_SELLLIMIT && Bid < limitPrice) validLimit = true;

               if(validLimit)
                 {
                  double lot = CalculateLotSize(slPips);
                  int ticket = OrderSend(Symbol(), orderType, lot, limitPrice, SLIPPAGE, stopLoss, takeProfit, "SMC Limit Manual", MagicNumber, 0, (orderType == OP_BUYLIMIT) ? clrBlue : clrRed);
                  if(ticket > 0)
                    {
                     lastTradeDay = currentDay;
                     boxDetected = false; // Reset state
                     RegisterInitialRisk(ticket, slPips); // Necesario para el modo BE a 1:1 (se activa cuando se llene la limit)
                     Print("Orden Limit SMC Manual colocada exitosamente. Lote: ", lot, " TP: ", takeProfit);
                     if(InpSendPush) SendNotification("Asian Breakout [" + Symbol() + "]: Orden Limit colocada a " + DoubleToStr(limitPrice, Digits));
                     // Ocultar el rectangulo para no duplicar manana
                     ObjectDelete(0, ManualBoxName);
                    }
                  else
                    {
                     Print("Error al poner la Orden Limit Manual: ", GetLastError());
                    }
                 }
               else
                 {
                  static datetime lastPrint = 0;
                  if(Time[0] != lastPrint)
                    {
                     Print("SMC Esperando... Precio actual no permite colocar Limit. (Bid: ", Bid, " Limit: ", limitPrice, ")");
                     lastPrint = Time[0];
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| Dibuja una linea vertical en el grafico indicando la noticia     |
//+------------------------------------------------------------------+
void DrawNewsLine(string name, color clr, double minsToNews)
  {
   if(minsToNews == EMPTY_VALUE || minsToNews == 0) return;
   
   datetime newsTime = TimeCurrent() + (int)(minsToNews * 60);
   
   if(ObjectFind(name) < 0)
     {
      ObjectCreate(0, name, OBJ_VLINE, 0, newsTime, 0);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_DASHDOT);
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
      ObjectSetInteger(0, name, OBJPROP_BACK, true);
     }
   else
     {
      ObjectSetInteger(0, name, OBJPROP_TIME, newsTime);
     }
  }

//+------------------------------------------------------------------+
//| News API Integration (Global Variables from News_Fetcher)        |
//+------------------------------------------------------------------+
bool IsNewsTime()
  {
   bool isNews = false;
   
   static datetime lastNewsCheck = 0;
   bool shouldUpdateLines = (TimeCurrent() - lastNewsCheck >= 60);
   if(shouldUpdateLines) lastNewsCheck = TimeCurrent();
   
   if(FilterHighImpact)
     {
      if(GlobalVariableCheck("SMC_News_High"))
        {
         double minsHigh = GlobalVariableGet("SMC_News_High"); 
         if(shouldUpdateLines) DrawNewsLine("SMC_News_High", clrRed, minsHigh);
         if(minsHigh <= MinsBeforeNews && minsHigh >= -MinsAfterNews) isNews = true;
        }
     }
     
   if(FilterMedImpact)
     {
      if(GlobalVariableCheck("SMC_News_Med"))
        {
         double minsMed = GlobalVariableGet("SMC_News_Med"); 
         if(shouldUpdateLines) DrawNewsLine("SMC_News_Med", clrOrange, minsMed);
         if(minsMed <= MinsBeforeNews && minsMed >= -MinsAfterNews) isNews = true;
        }
     }

   return isNews;
  }
//+------------------------------------------------------------------+
