//+------------------------------------------------------------------+
//|                                              News_Fetcher.mq4    |
//|                                      Generated by Antigravity    |
//+------------------------------------------------------------------+
#property strict
#property description "Descarga noticias XML nativamente y usa Variables Globales"

input string   Config_Label      = "--- CONFIGURACION DE NOTICIAS ---";
input string   TargetCurrencies  = "EUR,USD"; // Monedas separadas por coma
input int      RefreshMinutes    = 60;        // Frecuencia de actualizaciÃ³n
input int      TimeOffsetHours   = 7;         // Diferencia de horas (ForexFactory -> Broker) Ej: RoboForex suele ser +7/+8

int OnInit()
  {
   EventSetTimer(RefreshMinutes * 60);
   FetchNews();
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   EventKillTimer();
  }

void OnTimer()
  {
   FetchNews();
  }

void FetchNews()
  {
   string url = "https://nfs.faireconomy.media/ff_calendar_thisweek.xml"; // Usamos HTTPS
   char post[], result[];
   string res_headers;
   // EngaÃ±amos al servidor fingiendo ser un navegador Chrome moderno para evitar el Error 403 (Cloudflare)
   string req_headers = "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36\r\n";
   
   int res = WebRequest("GET", url, req_headers, 5000, post, result, res_headers);
   
   if(res == 200)
     {
      string data = CharArrayToString(result);
      ParseXML(data);
     }
   else
     {
      Print("Error descargando noticias. Codigo: ", res, ". Asegúrate de añadir https://nfs.faireconomy.media a WebRequest en Opciones.");
     }
  }

void ParseXML(string xml)
  {
   int pos = 0;
   double minHigh = 999999;
   double minMed = 999999;
   datetime now = TimeCurrent();
   
   while((pos = StringFind(xml, "<event>", pos)) != -1)
     {
      int endEvent = StringFind(xml, "</event>", pos);
      if(endEvent == -1) break;
      
      string eventStr = StringSubstr(xml, pos, endEvent - pos);
      pos = endEvent + 8;
      
      string country = GetTag(eventStr, "country");
      string impact = GetTag(eventStr, "impact");
      string dateStr = GetTag(eventStr, "date");
      string timeStr = GetTag(eventStr, "time");
      
      if(StringFind(TargetCurrencies, country) == -1) continue;
      if(timeStr == "All Day" || timeStr == "Tentative") continue;
      
      datetime eventTime = ParseFFTime(dateStr, timeStr);
      if(eventTime == 0) continue;
      
      // Ajustar por la diferencia horaria entre ForexFactory y el Broker
      eventTime += TimeOffsetHours * 3600;
      
      double mins = (double)(eventTime - now) / 60.0;
      
      // Guardar el evento MÃS PRÃ“XIMO (incluso si pasÃ³ hace poco)
      if(mins > -120) // Ignorar noticias de hace mÃ¡s de 2 horas
        {
         if(impact == "High" && (minHigh == 999999 || (mins > 0 && mins < minHigh) || (mins < 0 && minHigh < 0 && mins > minHigh))) minHigh = mins;
         if(impact == "Medium" && (minMed == 999999 || (mins > 0 && mins < minMed) || (mins < 0 && minMed < 0 && mins > minMed))) minMed = mins;
        }
     }
     
   if(minHigh != 999999) GlobalVariableSet("SMC_News_High", minHigh);
   if(minMed != 999999) GlobalVariableSet("SMC_News_Med", minMed);
   
   Print("SMC News Fetcher: Actualizado. Minutos hasta High: ", (minHigh==999999?"Ninguna":DoubleToStr(minHigh,0)));
  }

string GetTag(string src, string tag)
  {
   string startTag = "<" + tag + ">";
   string endTag = "</" + tag + ">";
   int start = StringFind(src, startTag);
   if(start == -1) return "";
   start += StringLen(startTag);
   int end = StringFind(src, endTag, start);
   if(end == -1) return "";
   return StringSubstr(src, start, end - start);
  }

datetime ParseFFTime(string dateStr, string timeStr)
  {
   string m = StringSubstr(dateStr, 0, 2);
   string d = StringSubstr(dateStr, 3, 2);
   string y = StringSubstr(dateStr, 6, 4);
   
   int colon = StringFind(timeStr, ":");
   if(colon == -1) return 0;
   
   string h = StringSubstr(timeStr, 0, colon);
   string min = StringSubstr(timeStr, colon + 1, 2);
   string ampm = StringSubstr(timeStr, StringLen(timeStr) - 2, 2);
   
   int hour = (int)StringToInteger(h);
   if(ampm == "pm" || ampm == "PM") { if(hour < 12) hour += 12; }
   if(ampm == "am" || ampm == "AM") { if(hour == 12) hour = 0; }
   
   string formattedTime = StringFormat("%s.%s.%s %02d:%s:00", y, m, d, hour, min);
   return StrToTime(formattedTime);
  }
//+------------------------------------------------------------------+

